// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"google.golang.org/protobuf/types/known/timestamppb"
	"hmans.de/chatto/internal/core"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// Union of every typed event payload exposed by GraphQL.
type EventType interface {
	IsEventType()
}

// Union of all notification types.
// Clients should check __typename to determine the notification type.
type NotificationItem interface {
	IsNotificationItem()
}

// Point-in-time storage-account limits and usage. Intended for operator diagnostics.
type AccountInfo struct {
	// Memory limit in bytes (-1 for unlimited)
	Memory int `json:"memory"`
	// Memory used in bytes
	MemoryUsed int `json:"memoryUsed"`
	// Storage limit in bytes (-1 for unlimited)
	Storage int `json:"storage"`
	// Storage used in bytes
	StorageUsed int `json:"storageUsed"`
	// Stream limit (-1 for unlimited)
	Streams int32 `json:"streams"`
	// Streams in use
	StreamsUsed int32 `json:"streamsUsed"`
	// Consumer limit (-1 for unlimited)
	Consumers int32 `json:"consumers"`
	// Consumers in use
	ConsumersUsed int32 `json:"consumersUsed"`
}

// Input for adding an emoji reaction to a message.
type AddReactionInput struct {
	// The ID of the room containing the message.
	RoomID string `json:"roomId"`
	// The event ID of the message to react to.
	MessageEventID string `json:"messageEventId"`
	// The emoji shortcode name (e.g., 'thumbsup', 'heart').
	Emoji string `json:"emoji"`
}

// Admin mutations for security and user management.
type AdminMutations struct {
	// Update the newline-separated blocked-username list and return the effective saved value. Requires `server.manage`.
	UpdateBlockedUsernames string `json:"updateBlockedUsernames"`
	// Update a user's login and/or display name. Bypasses the 30-day login change cooldown but otherwise reuses the same validation as updateProfile.
	UpdateUser *corev1.User `json:"updateUser"`
	// Clear the 30-day login change cooldown for a user, allowing them to immediately rename themselves. Idempotent.
	ClearUsernameCooldown bool `json:"clearUsernameCooldown"`
}

// Admin-console query namespace. Returns null unless the viewer is authenticated.
type AdminQueries struct {
	// Get point-in-time operator diagnostics for connection, storage, and deployment counts. Requires the owner role.
	SystemInfo *SystemInfo `json:"systemInfo"`
	// Get server configuration. Requires `server.manage`.
	ServerConfig *AdminServerConfig `json:"serverConfig"`
	// Browse the durable event log newest-first for operator diagnostics. `limit` defaults to 50, max 200. `before` is a sequence string; entries returned will have sequence < before.
	EventLog *EventLogConnection `json:"eventLog"`
	// Fetch a single diagnostic event-log entry by sequence. Returns null if the sequence doesn't exist.
	EventLogEntry *EventLogEntry `json:"eventLogEntry,omitempty"`
	// Inspect point-in-time runtime state and rough memory estimates for event-sourced projections.
	Projections []*ProjectionState `json:"projections"`
	// List active room bans. Requires server-scope `room.ban-member`.
	RoomBans []*RoomBan `json:"roomBans"`
	// RBAC editor and inspection queries.
	Rbac *RbacQueries `json:"rbac"`
	// Resolve the explicit grants and denials configured for a role on a
	// specific room group. Returns empty arrays if neither side has any keys.
	GroupRolePermissions *RoomGroupRolePermissions `json:"groupRolePermissions"`
	// Resolve the explicit grants and denials configured for a user on a
	// specific room group (user-level overrides at room-group scope).
	GroupUserPermissions *RoomGroupUserPermissions `json:"groupUserPermissions"`
}

// Server configuration section.
type AdminServerConfig struct {
	// Welcome message shown on the login page (markdown supported).
	WelcomeMessage *string `json:"welcomeMessage,omitempty"`
	// Server name, displayed in page titles. Defaults to 'Chatto' if not set.
	ServerName string `json:"serverName"`
	// Message of the Day, displayed in the header bar.
	Motd *string `json:"motd,omitempty"`
	// Blocked usernames (newline-separated). Users cannot register with these names.
	BlockedUsernames *string `json:"blockedUsernames,omitempty"`
	// Short description of this server, used for OG link-preview metadata and the welcome card.
	Description *string `json:"description,omitempty"`
}

// Input for AdminMutations.updateUser. At least one of login or displayName must be set.
type AdminUpdateUserInput struct {
	// ID of the user to update.
	UserID string `json:"userId"`
	// New login (username). When set, bypasses the 30-day cooldown but still validates against the blocked-username list and login rules.
	Login *string `json:"login,omitempty"`
	// New display name.
	DisplayName *string `json:"displayName,omitempty"`
}

// Input for archiving a room.
type ArchiveRoomInput struct {
	// The ID of the room to archive.
	RoomID string `json:"roomId"`
}

// A protected asset URL and the time its embedded access ticket expires.
type AssetURL struct {
	// URL to the asset on the owning host.
	URL string `json:"url"`
	// Time after which the embedded access ticket is no longer valid.
	ExpiresAt *timestamppb.Timestamp `json:"expiresAt"`
}

// Input for assigning an server role to a user.
type AssignRoleInput struct {
	// The ID of the user to assign the role to.
	UserID string `json:"userId"`
	// The name of the role to assign.
	RoleName string `json:"roleName"`
}

// Input for banning another member from a channel room.
type BanRoomMemberInput struct {
	// The ID of the channel room to ban the member from.
	RoomID string `json:"roomId"`
	// The ID of the user to ban from the room.
	UserID string `json:"userId"`
	// Moderator-entered reason stored for audit.
	Reason string `json:"reason"`
	// Optional expiry for a temporary ban. Null means indefinite.
	ExpiresAt *timestamppb.Timestamp `json:"expiresAt,omitempty"`
}

// A participant currently in a voice call.
type CallParticipant struct {
	// The user currently participating in the call.
	User *corev1.User `json:"user"`
	// When the user joined the call.
	JoinedAt *timestamppb.Timestamp `json:"joinedAt"`
}

// Input for clearing permission state on a role.
type ClearPermissionStateInput struct {
	// The role to clear permission state for.
	RoleName string `json:"roleName"`
	// The permission identifier to clear.
	Permission string `json:"permission"`
}

// Input for clearing a room-level permission override.
type ClearRoomPermissionInput struct {
	// The ID of the room.
	RoomID string `json:"roomId"`
	// The role to clear the permission for.
	RoleName string `json:"roleName"`
	// The permission identifier to clear.
	Permission string `json:"permission"`
}

// Input for clearing both grant and denial of a permission on a user.
// Same scope rules as `GrantUserPermissionInput`.
type ClearUserPermissionStateInput struct {
	// The user whose permission state to clear.
	UserID string `json:"userId"`
	// The permission identifier to clear.
	Permission string `json:"permission"`
	// Optional room ID. Mutually exclusive with `groupId`.
	RoomID *string `json:"roomId,omitempty"`
	// Optional room-group ID. Mutually exclusive with `roomId`.
	GroupID *string `json:"groupId,omitempty"`
}

// Input for AdminMutations.clearUsernameCooldown.
type ClearUsernameCooldownInput struct {
	// The user whose username cooldown to clear.
	UserID string `json:"userId"`
}

// Point-in-time diagnostic information about the backing message broker connection.
type ConnectionInfo struct {
	// Whether the connection to NATS is currently active.
	Connected bool `json:"connected"`
	// Unique identifier of the connected NATS server.
	ServerID string `json:"serverId"`
	// Human-readable name of the connected NATS server.
	ServerName string `json:"serverName"`
	// NATS server version string.
	Version string `json:"version"`
	// Maximum message payload size in bytes.
	MaxPayload int `json:"maxPayload"`
	// Round-trip time to the NATS server (e.g., '1.234ms').
	Rtt string `json:"rtt"`
}

// Input for creating a new role.
type CreateRoleInput struct {
	// Role identifier (lowercase alphanumeric + underscores, max 32 chars).
	Name string `json:"name"`
	// Human-readable display name.
	DisplayName string `json:"displayName"`
	// Role description.
	Description string `json:"description"`
	// Whether @role pings notify users assigned to this role. Defaults to false.
	Pingable *bool `json:"pingable,omitempty"`
}

// Input for creating a new room group.
type CreateRoomGroupInput struct {
	// Display name for the new room group (e.g., 'Engineering', 'Public').
	Name string `json:"name"`
	// Optional operator-facing description.
	Description *string `json:"description,omitempty"`
}

// Input for creating a new room.
type CreateRoomInput struct {
	// The name of the new room.
	Name string `json:"name"`
	// Optional description of the room's purpose.
	Description *string `json:"description,omitempty"`
	// Room group ID to place the new channel room in. Channel room creation
	// requires an explicit group; DM rooms are created through the DM APIs and
	// do not use this input.
	GroupID string `json:"groupId"`
}

// Input for deleting an attachment from a message.
type DeleteAttachmentInput struct {
	// The ID of the room containing the message.
	RoomID string `json:"roomId"`
	// The event ID of the message containing the attachment.
	EventID string `json:"eventId"`
	// The ID of the attachment to delete.
	AttachmentID string `json:"attachmentId"`
}

// Input for deleting a user avatar.
type DeleteAvatarInput struct {
	// The ID of the user whose avatar to delete. Caller must be self or have admin permission.
	UserID string `json:"userId"`
}

// Input for deleting a link preview from a message.
type DeleteLinkPreviewInput struct {
	// The ID of the room containing the message.
	RoomID string `json:"roomId"`
	// The event ID of the message containing the link preview.
	EventID string `json:"eventId"`
	// The URL of the link preview to delete.
	URL string `json:"url"`
}

// Input for deleting a message.
type DeleteMessageInput struct {
	// The ID of the room containing the message.
	RoomID string `json:"roomId"`
	// The event ID of the message to delete.
	EventID string `json:"eventId"`
}

// Input for deleting the current user's account.
type DeleteMyAccountInput struct {
	// Confirmation token obtained from requestAccountDeletion.
	ConfirmationToken string `json:"confirmationToken"`
}

// Input for deleting an server role.
type DeleteRoleInput struct {
	// The name of the role to delete.
	Name string `json:"name"`
}

// Input for deleting a room group. Fails if the room group still contains any rooms.
type DeleteRoomGroupInput struct {
	// The room group's ID.
	ID string `json:"id"`
}

// Input for denying a permission for a role.
type DenyPermissionInput struct {
	// The role to deny the permission for.
	RoleName string `json:"roleName"`
	// The permission identifier to deny.
	Permission string `json:"permission"`
}

// Input for denying a room-level permission for a role.
type DenyRoomPermissionInput struct {
	// The ID of the room.
	RoomID string `json:"roomId"`
	// The role to deny the permission for.
	RoleName string `json:"roleName"`
	// The permission identifier to deny.
	Permission string `json:"permission"`
}

// Input for denying a permission directly to a user. Same scope rules as
// `GrantUserPermissionInput`.
type DenyUserPermissionInput struct {
	// The user to deny the permission for.
	UserID string `json:"userId"`
	// The permission identifier to deny.
	Permission string `json:"permission"`
	// Optional room ID. Mutually exclusive with `groupId`.
	RoomID *string `json:"roomId,omitempty"`
	// Optional room-group ID. Mutually exclusive with `roomId`.
	GroupID *string `json:"groupId,omitempty"`
}

// Input for dismissing a notification.
type DismissNotificationInput struct {
	// The ID of the notification to dismiss.
	NotificationID string `json:"notificationId"`
}

// A page of diagnostic event-log entries, newest first.
type EventLogConnection struct {
	// Entries on this page, ordered newest → oldest.
	Entries []*EventLogEntry `json:"entries"`
	// True if older entries exist beyond this page.
	HasOlder bool `json:"hasOlder"`
	// Pass as the next call's `before` to fetch the next (older) page. Null when there are no older entries.
	EndCursor *string `json:"endCursor,omitempty"`
	// Total messages currently in EVT, serialized as Int64 so large event logs do not overflow GraphQL Int.
	TotalCount int64 `json:"totalCount"`
}

// One diagnostic entry in the durable event log. Use this for operator inspection, not as a machine-parsed product feed.
type EventLogEntry struct {
	// Monotonic event-log sequence, serialized as a String so large values do not overflow GraphQL Int.
	Sequence string `json:"sequence"`
	// Diagnostic storage subject. Useful for operators, but clients should not parse it as a stable product contract.
	Subject string `json:"subject"`
	// Diagnostic aggregate category derived from storage metadata.
	AggregateType string `json:"aggregateType"`
	// Diagnostic aggregate identifier derived from storage metadata.
	AggregateID string `json:"aggregateId"`
	// Diagnostic event variant label. Empty if the payload cannot be classified.
	EventType string `json:"eventType"`
	// Per-event unique identifier from event.id.
	EventID string `json:"eventId"`
	// ID of the actor who triggered the event. May also be a synthetic actor like 'system:migration' or 'system:bootstrap'.
	ActorID string `json:"actorId"`
	// When the event was created (per the event payload, not the stream).
	CreatedAt *timestamppb.Timestamp `json:"createdAt"`
	// Raw payload rendered as JSON for human inspection. Do not build clients that depend on this shape.
	PayloadJSON string `json:"payloadJson"`
}

// Input for following a thread.
type FollowThreadInput struct {
	// The ID of the room containing the thread.
	RoomID string `json:"roomId"`
	// The event ID of the thread root message.
	ThreadRootEventID string `json:"threadRootEventId"`
}

// Paginated list of followed threads with metadata.
type FollowedThreadsConnection struct {
	// The followed threads in this page.
	Threads []*FollowedThread `json:"threads"`
	// Total count of followed threads before pagination.
	TotalCount int32 `json:"totalCount"`
	// Whether there are more followed threads beyond this page.
	HasMore bool `json:"hasMore"`
}

// Input for granting a permission to a role.
type GrantPermissionInput struct {
	// The role to grant the permission to.
	RoleName string `json:"roleName"`
	// The permission identifier to grant.
	Permission string `json:"permission"`
}

// Input for granting a room-level permission to a role.
type GrantRoomPermissionInput struct {
	// The ID of the room.
	RoomID string `json:"roomId"`
	// The role to grant the permission to.
	RoleName string `json:"roleName"`
	// The permission identifier to grant.
	Permission string `json:"permission"`
}

// Input for granting a permission directly to a user. Exactly one of
// `roomId` or `groupId` may be provided; with neither, the grant applies
// at server scope.
type GrantUserPermissionInput struct {
	// The user to grant the permission to.
	UserID string `json:"userId"`
	// The permission identifier to grant.
	Permission string `json:"permission"`
	// Optional room ID for a room-scoped grant. Mutually exclusive with
	// `groupId`. Only works for permissions that support room scope.
	RoomID *string `json:"roomId,omitempty"`
	// Optional room-group ID for a group-scoped grant. Mutually exclusive
	// with `roomId`. Only works for permissions that support group scope.
	GroupID *string `json:"groupId,omitempty"`
}

// Input for granting a permission on a room group. The subject is either a role
// (by name) or a user (by ID).
type GroupPermissionInput struct {
	// The room group to scope the grant to.
	GroupID string `json:"groupId"`
	// Role name or user ID. (Role names are lowercase letters; user IDs start with `U`.)
	Subject string `json:"subject"`
	// Permission identifier (e.g., 'message.post').
	Permission string `json:"permission"`
}

// Input for joining every joinable room in a group.
type JoinGroupInput struct {
	// The ID of the room group whose rooms the caller wants to join.
	GroupID string `json:"groupId"`
}

// Input for joining a room.
type JoinRoomInput struct {
	// The ID of the room to join.
	RoomID string `json:"roomId"`
}

// Input for leaving a room.
type LeaveRoomInput struct {
	// The ID of the room to leave.
	RoomID string `json:"roomId"`
}

// Input type for passing link preview data from client to server.
// The client fetches preview metadata via the linkPreview query, then includes
// the data in the postMessage mutation so it can be attached to the message.
type LinkPreviewInput struct {
	// The URL that was previewed.
	URL string `json:"url"`
	// The page title.
	Title *string `json:"title,omitempty"`
	// The page description.
	Description *string `json:"description,omitempty"`
	// Asset ID of the preview image (from the linkPreview query response).
	ImageAssetID *string `json:"imageAssetId,omitempty"`
	// The site name.
	SiteName *string `json:"siteName,omitempty"`
	// Type of embed: 'generic', 'youtube', 'vimeo', etc.
	EmbedType *string `json:"embedType,omitempty"`
	// Embed ID for rich embeds (e.g., YouTube video ID).
	EmbedID *string `json:"embedId,omitempty"`
}

// Input for marking a room as read.
type MarkRoomAsReadInput struct {
	// The ID of the room to mark as read.
	RoomID string `json:"roomId"`
	// Optional event ID to mark as the read cursor. If provided, the marker is
	// set to this event (advance-only — never regresses past a more recent
	// marker). If omitted, the server uses the room's current latest event.
	UpToEventID *string `json:"upToEventId,omitempty"`
}

// Result of marking a room as read.
type MarkRoomAsReadResult struct {
	// The timestamp of the last-read event (null if no messages in room).
	LastReadAt *timestamppb.Timestamp `json:"lastReadAt,omitempty"`
	// The timestamp of the previously-read event (null if first time reading this room).
	PreviousLastReadAt *timestamppb.Timestamp `json:"previousLastReadAt,omitempty"`
}

// Input for marking a thread as read.
type MarkThreadAsReadInput struct {
	// The ID of the room containing the thread.
	RoomID string `json:"roomId"`
	// The event ID of the thread root message.
	ThreadRootEventID string `json:"threadRootEventId"`
	// Optional event ID (root or reply) to anchor the read cursor at. If
	// provided, the server records that event's timestamp (advance-only). If
	// omitted, the server records the current wall-clock time.
	UpToEventID *string `json:"upToEventId,omitempty"`
}

// Result of marking a thread as read.
type MarkThreadAsReadResult struct {
	// The timestamp when the thread was previously read (null if never read before).
	PreviousReadAt *timestamppb.Timestamp `json:"previousReadAt,omitempty"`
}

// Input for moving a room into a different room group. Requires room.manage in
// both the source and target room group.
type MoveRoomToGroupInput struct {
	// The room to move.
	RoomID string `json:"roomId"`
	// The destination room group.
	GroupID string `json:"groupId"`
}

// Root mutation type for modifying data.
type Mutation struct {
}

// Diagnostic state for one storage consumer. Raw consumer names and subjects are operator-facing diagnostics, not product concepts.
type NatsConsumerInfo struct {
	// Stream this consumer belongs to.
	Stream string `json:"stream"`
	// Consumer name.
	Name string `json:"name"`
	// Durable name, empty for ephemeral consumers.
	Durable string `json:"durable"`
	// Single filter subject, if configured.
	FilterSubject string `json:"filterSubject"`
	// Multiple filter subjects, if configured.
	FilterSubjects []string `json:"filterSubjects"`
	// Ack policy, e.g. Explicit, All, or None.
	AckPolicy string `json:"ackPolicy"`
	// True for pull consumers; false for push consumers.
	PullBased bool `json:"pullBased"`
	// Whether a push consumer currently has an active subscription.
	PushBound bool `json:"pushBound"`
	// Messages matching the consumer that have not yet been delivered.
	Pending int `json:"pending"`
	// Delivered messages awaiting acknowledgement.
	AckPending int32 `json:"ackPending"`
	// Messages redelivered and still unacknowledged.
	Redelivered int32 `json:"redelivered"`
	// Active pull requests waiting for messages.
	Waiting int32 `json:"waiting"`
	// Most recently delivered consumer sequence.
	DeliveredConsumerSequence string `json:"deliveredConsumerSequence"`
	// Most recently delivered stream sequence.
	DeliveredStreamSequence string `json:"deliveredStreamSequence"`
	// Ack floor consumer sequence.
	AckFloorConsumerSequence string `json:"ackFloorConsumerSequence"`
	// Ack floor stream sequence.
	AckFloorStreamSequence string `json:"ackFloorStreamSequence"`
}

// Current stream and consumer diagnostics. Values are point-in-time and may change between refreshes.
type NatsStats struct {
	// Streams in the JetStream account.
	Streams []*NatsStreamInfo `json:"streams"`
	// Consumers across all streams.
	Consumers []*NatsConsumerInfo `json:"consumers"`
	// Total retained messages across listed streams.
	TotalMessages int `json:"totalMessages"`
	// Total retained bytes across listed streams.
	TotalBytes int `json:"totalBytes"`
	// Total consumer backlog across listed consumers.
	TotalConsumerPending int `json:"totalConsumerPending"`
	// Total delivered-but-unacknowledged messages across listed consumers.
	TotalAckPending int32 `json:"totalAckPending"`
}

// Diagnostic state for one retained storage stream. Raw names and subjects are operator-facing diagnostics, not product concepts.
type NatsStreamInfo struct {
	// Stream name.
	Name string `json:"name"`
	// Optional stream description.
	Description string `json:"description"`
	// Configured subject filters.
	Subjects []string `json:"subjects"`
	// Storage backend, e.g. File or Memory.
	Storage string `json:"storage"`
	// Messages currently retained.
	Messages int `json:"messages"`
	// Bytes currently retained.
	Bytes int `json:"bytes"`
	// First retained stream sequence.
	FirstSequence string `json:"firstSequence"`
	// Last stream sequence.
	LastSequence string `json:"lastSequence"`
	// Consumers currently attached to this stream.
	ConsumerCount int32 `json:"consumerCount"`
	// Configured replica count.
	Replicas int32 `json:"replicas"`
	// Cluster leader when running clustered JetStream, otherwise empty.
	ClusterLeader string `json:"clusterLeader"`
}

// Paginated list of notifications with metadata.
type NotificationsConnection struct {
	// The notifications in this page, newest first.
	Items []NotificationItem `json:"items"`
	// Total count of notifications before pagination.
	TotalCount int32 `json:"totalCount"`
	// Whether there are more notifications beyond this page.
	HasMore bool `json:"hasMore"`
}

// The complete explanation for one permission for one user at one scope.
// Mirrors the algorithm of the permission resolver: the first trace entry
// is the winning decision; subsequent entries are also-saw context.
type PermissionExplanation struct {
	// The permission identifier (e.g., 'message.post').
	Permission string `json:"permission"`
	// Overall outcome (allow, deny, or none if no role had an explicit decision).
	State PermissionDecisionKind `json:"state"`
	// The level of the winning decision; null if state is none.
	DecidedAt *PermissionLevel `json:"decidedAt,omitempty"`
	// The role that produced the winning decision; null if state is none.
	DecidedByRole *string `json:"decidedByRole,omitempty"`
	// Full ordered trace; the head is the winning decision.
	Trace []*PermissionTraceEntry `json:"trace"`
}

// One cell of the user-permission matrix: the per-permission, per-scope
// intersection.
type PermissionMatrixCell struct {
	// Permission identifier (e.g. `message.post`).
	Permission string `json:"permission"`
	// Scope id (matches `PermissionMatrixScope.id`).
	ScopeID string `json:"scopeId"`
	// The **explicit user-level override** at this scope, or NONE if the user
	// has no override here. NONE cells display only the inherited effective
	// state; ALLOW / DENY cells display as a solid override.
	Override PermissionMatrixDecision `json:"override"`
	// The **effective** decision the resolver would emit at this scope for
	// this user-permission pair, after walking room → group → server with
	// user-level overrides applied first. Drives the cell's tint.
	Effective PermissionMatrixDecision `json:"effective"`
}

// A user's permission state across every scope where it can be configured —
// the data the User Permissions page renders as a matrix.
//
// Each cell answers two questions:
//  1. What's the **effective** decision after the full resolver walk (this
//     is what governs runtime behavior)?
//  2. Does the user have an **explicit user-level override** at this scope
//     (and which way)? Cells with an override render solid; cells driven
//     only by inheritance render faded.
type PermissionMatrixScope struct {
	// Stable identifier for this scope:
	//   - `server` for the server tier (no group/room context),
	//   - `group:{groupID}` for a room-group scope,
	//   - `room:{roomID}` for a per-room scope.
	// Clients use it as a column key.
	ID string `json:"id"`
	// Human-readable label for the scope (group name, room name, or 'Server').
	Label string `json:"label"`
	// Scope kind. The frontend uses this to lay out columns (server tier first,
	// groups expandable, rooms nested under their group).
	Kind PermissionMatrixScopeKind `json:"kind"`
	// For room scopes, the parent group's ID — so the UI can nest rooms under
	// their group column. Empty string for server / group scopes.
	ParentGroupID string `json:"parentGroupId"`
}

// A single step in the permission resolution trace.
// Only explicit allow or deny entries are emitted; roles with no decision at the
// level being checked are silent.
type PermissionTraceEntry struct {
	// The level at which this decision was observed.
	Level PermissionLevel `json:"level"`
	// The role that produced this decision.
	RoleName string `json:"roleName"`
	// Whether the role allowed or denied the permission at this level.
	Decision PermissionDecisionKind `json:"decision"`
	// Whether this entry is the winning decision (matches the trace head).
	Applied bool `json:"applied"`
}

// Input for posting a message to a room.
type PostMessageInput struct {
	// The ID of the room to post to.
	RoomID string `json:"roomId"`
	// The message content. Optional if attachments are provided.
	Body *string `json:"body,omitempty"`
	// Optional file attachments (images, videos, etc.).
	Attachments []*graphql.Upload `json:"attachments,omitempty"`
	// Event ID of the thread root message. Determines thread membership and controls permission check (message.start_thread vs message.post_in_thread vs message.post).
	ThreadRootEventID *string `json:"threadRootEventId,omitempty"`
	// Event ID of the message this responds to (attribution only, does not affect routing or permissions).
	InReplyTo *string `json:"inReplyTo,omitempty"`
	// Also echo this thread reply to the main channel for visibility (requires message.echo permission).
	AlsoSendToChannel *bool `json:"alsoSendToChannel,omitempty"`
	// Short-lived token returned after a large mention confirmation prompt. Authorizes sending this exact message even if the current recipient count drifts.
	MentionConfirmationToken *string `json:"mentionConfirmationToken,omitempty"`
	// Link preview data from the composer. Server stores this directly without fetching.
	LinkPreview *LinkPreviewInput `json:"linkPreview,omitempty"`
}

// One named diagnostic count/byte bucket for a projection.
type ProjectionMetric struct {
	// Diagnostic metric identifier, e.g. 'timeline_entries' or 'event_id_index'. Names may evolve with projection implementation.
	Name string `json:"name"`
	// Count associated with this metric.
	Value int `json:"value"`
	// Estimated bytes associated with this metric. Zero when the metric is count-only.
	Bytes int `json:"bytes"`
}

// Point-in-time runtime state for one event-sourced projection.
type ProjectionState struct {
	// Human-readable projection name.
	Name string `json:"name"`
	// Diagnostic storage subject filters consumed by this projection.
	Subjects []string `json:"subjects"`
	// Whether the projector run loop has started.
	Started bool `json:"started"`
	// Highest event-log sequence applied by this projection, serialized as String to avoid GraphQL Int overflow.
	LastAppliedSequence string `json:"lastAppliedSequence"`
	// Highest event-log sequence currently matching this projection's subject filters.
	MatchingStreamSequence string `json:"matchingStreamSequence"`
	// Highest sequence in the event log, regardless of whether this projection consumes it.
	StreamLastSequence string `json:"streamLastSequence"`
	// Unapplied matching events, computed as matchingStreamSequence - lastAppliedSequence.
	Lag int `json:"lag"`
	// Whether this projection has stopped after a fatal decode or apply error.
	Failed bool `json:"failed"`
	// Failed event-log sequence, serialized as String. Zero when the projection has not failed.
	FailedSequence string `json:"failedSequence"`
	// Operator-facing failure summary. Empty when the projection has not failed.
	Failure string `json:"failure"`
	// Primary projected entry count for this projection.
	EntryCount int `json:"entryCount"`
	// Estimated bytes held in memory by this projection.
	EstimatedBytes int `json:"estimatedBytes"`
	// estimatedBytes divided by entryCount, or zero when entryCount is zero.
	AverageEntryBytes int `json:"averageEntryBytes"`
	// Breakdown of the projection's current state.
	Metrics []*ProjectionMetric `json:"metrics"`
}

// Input for subscribing to Web Push notifications.
// All fields come from the PushSubscription object returned by the browser's Push API.
type PushSubscriptionInput struct {
	// The push service endpoint URL (from PushSubscription.endpoint)
	Endpoint string `json:"endpoint"`
	// The client's P-256 ECDH public key for message encryption (from PushSubscription.keys.p256dh)
	P256dh string `json:"p256dh"`
	// Authentication secret for message encryption (from PushSubscription.keys.auth)
	Auth string `json:"auth"`
	// Optional user agent string for device identification
	UserAgent *string `json:"userAgent,omitempty"`
}

// Root query type for fetching data.
type Query struct {
}

// RBAC tooling namespace for role, permission, and permission inspection screens.
// Individual fields enforce their own finer-grained authorization gates, such as
// `role.manage` or `room.manage`.
type RbacQueries struct {
	// Return the full role-permission matrix at a tier: every applicable role
	// with its override and inherited baseline.
	//
	// Pass `roomId` for per-room override editing, `groupId` for room-group-scope
	// editing, or neither for server-scope editing. Passing both is rejected.
	RolePermissionTierMatrix *TierRoles `json:"rolePermissionTierMatrix,omitempty"`
	// Permission matrix for a specific role. Authorization: viewer must hold
	// `role.manage` at server scope.
	RolePermissionMatrix *RolePermissionMatrix `json:"rolePermissionMatrix,omitempty"`
	// Permission matrix for a specific user. Authorization mirrors user-level
	// permission mutations: viewer must hold `role.manage` and strictly outrank
	// the target. Self-introspection is not allowed.
	UserPermissionMatrix *UserPermissionMatrix `json:"userPermissionMatrix,omitempty"`
	// Explain every applicable permission for a user at the given scope.
	// Authorization: admin/tooling-only, with no self-inspection path.
	PermissionExplanation []*PermissionExplanation `json:"permissionExplanation"`
}

// Input for removing an emoji reaction from a message.
type RemoveReactionInput struct {
	// The ID of the room containing the message.
	RoomID string `json:"roomId"`
	// The event ID of the message to remove the reaction from.
	MessageEventID string `json:"messageEventId"`
	// The emoji shortcode name (e.g., 'thumbsup', 'heart').
	Emoji string `json:"emoji"`
}

// Input for reordering server roles.
type ReorderRolesInput struct {
	// Ordered list of custom role names. System roles should not be included.
	RoleNames []string `json:"roleNames"`
}

// Input for reordering all room groups. The order must include every existing
// room group ID exactly once; partial or unknown lists are rejected.
type ReorderRoomGroupsInput struct {
	// Room group IDs in the desired display order, first to last.
	OrderedIds []string `json:"orderedIds"`
}

// Input for reordering rooms inside a single group. The ID list must be a
// permutation of the group's current rooms — partial or unknown lists are
// rejected.
type ReorderRoomsInGroupInput struct {
	// The group whose room order is being rewritten.
	GroupID string `json:"groupId"`
	// Room IDs in the desired display order, first to last.
	OrderedRoomIds []string `json:"orderedRoomIds"`
}

// Input for revoking a permission from a role.
type RevokePermissionInput struct {
	// The role to revoke the permission from.
	RoleName string `json:"roleName"`
	// The permission identifier to revoke.
	Permission string `json:"permission"`
}

// Input for revoking an server role from a user.
type RevokeRoleInput struct {
	// The ID of the user to revoke the role from.
	UserID string `json:"userId"`
	// The name of the role to revoke.
	RoleName string `json:"roleName"`
}

// A role's permission state across every scope where it can be configured —
// the data the Role Permissions page renders as a matrix.
//
// Each cell answers two questions:
//  1. What's the role's **explicit override** at this scope (ALLOW / DENY /
//     NONE)? Solid cells have an override; faded cells inherit from a
//     broader scope.
//  2. What's the **effective** decision the resolver would walk to for THIS
//     role at this scope (room → group → server), considering only this
//     role's own grants? Drives the faded baseline color.
type RolePermissionMatrix struct {
	// The role this matrix describes.
	RoleName string `json:"roleName"`
	// Permissions to render as rows. Same identifiers used by the user
	// matrix, so the frontend can reuse its grouping / display-name
	// metadata.
	ApplicablePermissions []string `json:"applicablePermissions"`
	// Scopes to render as columns. Server scope first, then groups, then
	// rooms grouped under their parent group via `parentGroupId`.
	Scopes []*PermissionMatrixScope `json:"scopes"`
	// One cell per (permission, scope) intersection. Sparse: a cell is
	// included iff the permission applies at that scope's tier.
	Cells []*PermissionMatrixCell `json:"cells"`
}

// Room-level permission configuration for a single role.
// Shows grants and denials that are specific to this room (not inherited from
// the role's server-level state).
type RoleRoomPermissions struct {
	// Role identifier
	RoleName string `json:"roleName"`
	// Human-readable display name
	DisplayName string `json:"displayName"`
	// Whether this is a system-defined role
	IsSystem bool `json:"isSystem"`
	// Hierarchy position (higher = higher rank; see Role.position).
	Position int32 `json:"position"`
	// Permissions granted at room level
	Permissions []string `json:"permissions"`
	// Permissions denied at room level
	PermissionDenials []string `json:"permissionDenials"`
}

// An active room ban shown in server-admin moderation tools.
type RoomBan struct {
	// The event ID that created the active ban.
	ID string `json:"id"`
	// The channel room this ban applies to.
	RoomID string `json:"roomId"`
	// The room this ban applies to, if it still exists.
	Room *corev1.Room `json:"room,omitempty"`
	// The banned user.
	UserID string `json:"userId"`
	// The banned user, if the account still exists.
	User *corev1.User `json:"user,omitempty"`
	// The moderator who created the ban.
	ModeratorID string `json:"moderatorId"`
	// The moderator who created the ban, if the account still exists.
	Moderator *corev1.User `json:"moderator,omitempty"`
	// Moderator-entered reason retained for audit.
	Reason string `json:"reason"`
	// When the ban was created.
	CreatedAt *timestamppb.Timestamp `json:"createdAt"`
	// When this ban expires. Null means indefinite.
	ExpiresAt *timestamppb.Timestamp `json:"expiresAt,omitempty"`
}

// Result of fetching events around a specific target event. `startCursor`
// and `endCursor` are opaque pagination cursors usable on `Room.events`.
type RoomEventsAroundResult struct {
	// The events in the window, in chronological order.
	Events []core.EventEnvelope `json:"events"`
	// The index of the target event within the events array.
	TargetIndex int32 `json:"targetIndex"`
	// Opaque cursor of the first event in this window (null if empty).
	StartCursor *string `json:"startCursor,omitempty"`
	// Opaque cursor of the last event in this window (null if empty).
	EndCursor *string `json:"endCursor,omitempty"`
	// Whether there are older events before this window.
	HasOlder bool `json:"hasOlder"`
	// Whether there are newer events after this window.
	HasNewer bool `json:"hasNewer"`
}

// Paginated chronological events with metadata indicating whether more events
// exist in either direction. `startCursor` and `endCursor` are opaque pagination
// cursors — pass them as `before` / `after` on the same field that returned them.
// Both are null when `events` is empty.
type RoomEventsConnection struct {
	// The events in chronological order.
	Events []core.EventEnvelope `json:"events"`
	// Opaque cursor of the first event in this page (null if empty).
	StartCursor *string `json:"startCursor,omitempty"`
	// Opaque cursor of the last event in this page (null if empty).
	EndCursor *string `json:"endCursor,omitempty"`
	// Whether there are older events before this page.
	HasOlder bool `json:"hasOlder"`
	// Whether there are newer events after this page.
	HasNewer bool `json:"hasNewer"`
}

// Per-room-group role permission inspector. Returns the explicit grants and
// denials configured on a room group for a given role (no inheritance — to
// see the effective permissions resolve per-room or per-user via the resolver
// instead).
type RoomGroupRolePermissions struct {
	// The room group these permissions belong to.
	GroupID string `json:"groupId"`
	// The role these permissions apply to.
	RoleName string `json:"roleName"`
	// Permissions explicitly granted to this role on this room group.
	Permissions []string `json:"permissions"`
	// Permissions explicitly denied to this role on this room group.
	PermissionDenials []string `json:"permissionDenials"`
}

// Per-room-group user permission inspector. Mirrors RoomGroupRolePermissions
// for direct user-level grants/denials.
type RoomGroupUserPermissions struct {
	// The room group these permissions belong to.
	GroupID string `json:"groupId"`
	// The user these permissions apply to.
	UserID string `json:"userId"`
	// Permissions explicitly granted to this user on this room group.
	Permissions []string `json:"permissions"`
	// Permissions explicitly denied to this user on this room group.
	PermissionDenials []string `json:"permissionDenials"`
}

// Paginated list of room members with metadata.
type RoomMembersConnection struct {
	// The users who are members of this room.
	Users []*corev1.User `json:"users"`
	// Total count of members before pagination.
	TotalCount int32 `json:"totalCount"`
	// Whether there are more members beyond this page.
	HasMore bool `json:"hasMore"`
}

// A user's notification preference for a specific room.
// Used by the bulk roomNotificationPreferences query to return all preferences at once.
type RoomNotificationPreferenceItem struct {
	// The room this preference applies to.
	RoomID string `json:"roomId"`
	// The explicitly set level (DEFAULT if not explicitly configured).
	Level NotificationLevel `json:"level"`
	// The effective level after inheritance resolution (never DEFAULT).
	EffectiveLevel NotificationLevel `json:"effectiveLevel"`
}

// Input for sending a typing indicator.
type SendTypingIndicatorInput struct {
	// The ID of the room the user is typing in.
	RoomID string `json:"roomId"`
	// The event ID of the thread root message, if typing in a thread.
	ThreadRootEventID *string `json:"threadRootEventId,omitempty"`
}

// Information about this Chatto server.
// Some fields don't require authentication and are available on the login page.
type Server struct {
	// The application version.
	Version string `json:"version"`
	// List of enabled SSO provider names (e.g., 'google', 'github').
	EnabledAuthProviders []string `json:"enabledAuthProviders"`
	// Public-facing identity and branding for this server.
	Profile *ServerProfile `json:"profile"`
	// True if Web Push notifications are enabled on this server.
	PushNotificationsEnabled bool `json:"pushNotificationsEnabled"`
	// VAPID public key for Web Push subscriptions. Null if push is disabled.
	VapidPublicKey *string `json:"vapidPublicKey,omitempty"`
	// LiveKit WebSocket URL for voice calls. Null if voice calls are disabled.
	LivekitURL *string `json:"livekitUrl,omitempty"`
	// True if direct (email/password) registration is enabled on this server.
	DirectRegistrationEnabled bool `json:"directRegistrationEnabled"`
	// True if video processing is enabled, allowing video attachments to be uploaded.
	VideoProcessingEnabled bool `json:"videoProcessingEnabled"`
	// Maximum upload size for regular attachments (images, files) in bytes.
	MaxUploadSize int64 `json:"maxUploadSize"`
	// Maximum upload size for video attachments in bytes. Same as maxUploadSize when video processing is disabled.
	MaxVideoUploadSize int64 `json:"maxVideoUploadSize"`
	// Duration in seconds after posting during which a user can edit their own message. Moderators with `message.edit-any` are not bound by this window.
	MessageEditWindowSeconds int32 `json:"messageEditWindowSeconds"`
	// List of rooms on this server.
	//
	// When `type` is null or `CHANNEL`, the result includes regular channels. When
	// `type` is null or `DM`, the caller's direct-message conversations are merged
	// in through membership; the unified sidebar uses the null default to render
	// channels and DMs together. Pass `type: CHANNEL` for channels-only consumers
	// (e.g. the admin room-management UI); pass `type: DM` for DMs-only consumers.
	Rooms []*corev1.Room `json:"rooms"`
	// Ordered list of channel-room groups. Every server boots with at least the
	// seed "Lobby" group; the list is never empty for a configured server.
	RoomGroups []*RoomGroupModel `json:"roomGroups"`
	// Number of members on this server.
	MemberCount int32 `json:"memberCount"`
	// Number of rooms on this server.
	RoomCount int32 `json:"roomCount"`
	// Number of assets (attachments) uploaded to this server.
	AssetCount int32 `json:"assetCount"`
	// Whether the current user has any admin.* permission (for showing the Admin link).
	ViewerHasAnyAdminPermission bool `json:"viewerHasAnyAdminPermission"`
	// Whether the current user can manage this server (has server.manage permission).
	ViewerCanManageServer bool `json:"viewerCanManageServer"`
	// Whether the current user can create rooms (has room.create permission).
	ViewerCanCreateRoom bool `json:"viewerCanCreateRoom"`
	// Whether the current user can manage rooms (has room.manage permission).
	ViewerCanManageRooms bool `json:"viewerCanManageRooms"`
	// Whether the current user has any unread messages in rooms they've joined.
	ViewerHasUnreadRooms bool `json:"viewerHasUnreadRooms"`
	// The current user's server-level notification preference.
	ViewerNotificationPreference *ViewerNotificationPreference `json:"viewerNotificationPreference,omitempty"`
	// Get a single member of this server by user ID.
	// Returns null if the user is not a member.
	Member *corev1.User `json:"member,omitempty"`
	// List members of this server with optional search and pagination.
	// Search matches login and display name (case-insensitive partial match).
	Members *ServerMembersConnection `json:"members"`
	// List all roles on this server.
	Roles []*core.RoleWithPermissions `json:"roles"`
	// Get a single role by name. Returns null if not found.
	Role *core.RoleWithPermissions `json:"role,omitempty"`
	// List all available permission identifiers.
	AvailablePermissions []string `json:"availablePermissions"`
	// Get the current user's permissions on this server.
	ViewerPermissions []string `json:"viewerPermissions"`
	// Whether the current user can manage roles (has role.manage permission).
	ViewerCanManageRoles bool `json:"viewerCanManageRoles"`
	// Whether the current user can assign roles to users (has role.assign permission).
	ViewerCanAssignRoles bool `json:"viewerCanAssignRoles"`
	// UI hint reporting whether the viewer outranks the target user by role
	// hierarchy. **This is a rank check only**, not an authorization gate —
	// capabilities like "edit this user's profile" additionally require a
	// permission (e.g. `role.assign`). Use this for showing/hiding admin UI
	// affordances; never as the sole basis for permitting a mutation. See
	// `.claude/rules/authorization.md` (`permission AND OutranksUser`).
	ViewerCanManageUser bool `json:"viewerCanManageUser"`
	// Get users assigned to a specific role.
	RoleUsers []*corev1.User `json:"roleUsers"`
	// Get a user's effective allowed permissions at server scope. Combines
	// role-based grants with user-level overrides (`grantUserPermission` /
	// `denyUserPermission`) — the same answer the authorization resolver
	// produces. For per-decision provenance use the permission explainer.
	UserEffectivePermissions []string `json:"userEffectivePermissions"`
	// Get a user's effective denied permissions at server scope. Mirrors
	// `userEffectivePermissions` but lists permissions whose first decision
	// is a deny.
	UserEffectiveDenials []string `json:"userEffectiveDenials"`
}

// Paginated list of server members with metadata.
type ServerMembersConnection struct {
	// The users who are members of this server.
	Users []*corev1.User `json:"users"`
	// Total count of members matching the search (before pagination).
	TotalCount int32 `json:"totalCount"`
	// Whether there are more members beyond this page.
	HasMore bool `json:"hasMore"`
}

// How this server presents itself in logged-out and multi-server UI.
type ServerProfile struct {
	// Display name for this server. Defaults to 'Chatto'.
	Name string `json:"name"`
	// URL to the server logo, if set.
	LogoURL *string `json:"logoUrl,omitempty"`
	// URL to the server banner image, if set.
	BannerURL *string `json:"bannerUrl,omitempty"`
	// Welcome message to display on the login screen (Markdown). Null if not configured.
	WelcomeMessage *string `json:"welcomeMessage,omitempty"`
	// Message of the Day, displayed in the header bar. Null if not configured.
	Motd *string `json:"motd,omitempty"`
	// Short description of this server, used for OG link-preview metadata and the welcome card. Null if not configured.
	Description *string `json:"description,omitempty"`
}

// Aggregate counts for the deployment. Operator-facing only.
type ServerStats struct {
	// Number of registered users.
	UserCount int32 `json:"userCount"`
	// Number of channel rooms.
	ChannelRoomCount int32 `json:"channelRoomCount"`
	// Number of DM rooms.
	DmRoomCount int32 `json:"dmRoomCount"`
}

// Input for setting the notification level for a room.
type SetRoomNotificationLevelInput struct {
	// The ID of the room.
	RoomID string `json:"roomId"`
	// The notification level to set.
	Level NotificationLevel `json:"level"`
}

// Input for setting the server-level notification level.
type SetServerNotificationLevelInput struct {
	// The notification level to set.
	Level NotificationLevel `json:"level"`
}

// Input for starting a DM conversation.
type StartDMInput struct {
	// The IDs of the users to start a conversation with. The current user is automatically included.
	ParticipantIds []string `json:"participantIds"`
}

// Root subscription type.
type Subscription struct {
}

// Point-in-time operator diagnostics for this deployment.
type SystemInfo struct {
	// NATS connection status and server info.
	Connection *ConnectionInfo `json:"connection"`
	// JetStream account limits and usage (aggregate totals).
	Account *AccountInfo `json:"account"`
	// Current JetStream stream and consumer diagnostics.
	Nats *NatsStats `json:"nats"`
	// Deployment-level counts surfaced in the admin dashboard.
	Stats *ServerStats `json:"stats"`
}

// A role's permission state at a single tier (server or room).
// Returned as part of RBAC matrix results so callers can display explicit
// allow/deny state for a tier.
type TierPermissions struct {
	// Permissions explicitly granted by this role at this tier.
	Permissions []string `json:"permissions"`
	// Permissions explicitly denied by this role at this tier.
	PermissionDenials []string `json:"permissionDenials"`
}

// A role's permission state at one tier, including the inherited baseline
// from the tiers above (the resolved state if the override at this tier
// were cleared). Used by the matrix UI to show inherited values faded
// behind the explicit override.
type TierRole struct {
	// Internal role name (e.g. 'admin', 'moderator').
	RoleName string `json:"roleName"`
	// Human-readable display name.
	DisplayName string `json:"displayName"`
	// Role description.
	Description string `json:"description"`
	// Whether this is a system role and cannot be deleted.
	IsSystem bool `json:"isSystem"`
	// Hierarchy position: higher = higher rank. Owner=1000, admin=900, moderator=100, custom roles in 1..99, everyone=0.
	Position int32 `json:"position"`
	// Explicit allow/deny at the requested tier. Allow and deny lists may
	// both be empty for a role with no override at this tier.
	Override *TierPermissions `json:"override"`
	// Permissions allowed by inheritance from the tiers above this one. Empty
	// at server scope; at room scope it reflects the role's server-level state.
	InheritedAllows []string `json:"inheritedAllows"`
	// Permissions denied by inheritance from the tiers above this one.
	InheritedDenials []string `json:"inheritedDenials"`
}

// A full per-tier permission matrix: every role applicable at the
// requested scope, with override + inherited baseline for each, plus the
// list of permissions configurable at this scope.
type TierRoles struct {
	// Permissions configurable at this tier. The matrix renders one row per
	// entry in this list.
	ApplicablePermissions []string `json:"applicablePermissions"`
	// All roles ordered by position (lowest = highest rank first).
	Roles []*TierRole `json:"roles"`
}

// Input for unarchiving a room.
type UnarchiveRoomInput struct {
	// The ID of the room to unarchive.
	RoomID string `json:"roomId"`
}

// Input for removing a room ban.
type UnbanRoomMemberInput struct {
	// The ID of the channel room to unban the user from.
	RoomID string `json:"roomId"`
	// The ID of the user to unban.
	UserID string `json:"userId"`
	// Moderator-entered reason stored for audit.
	Reason string `json:"reason"`
}

// Input for unfollowing a thread.
type UnfollowThreadInput struct {
	// The ID of the room containing the thread.
	RoomID string `json:"roomId"`
	// The event ID of the thread root message.
	ThreadRootEventID string `json:"threadRootEventId"`
}

// Input for unsubscribing from push notifications.
type UnsubscribeFromPushInput struct {
	// The push service endpoint URL to unsubscribe.
	Endpoint string `json:"endpoint"`
}

// Input for AdminMutations.updateBlockedUsernames.
type UpdateBlockedUsernamesInput struct {
	// Blocked usernames (newline-separated). Set to empty string to clear.
	BlockedUsernames string `json:"blockedUsernames"`
}

// Input for updating a message.
type UpdateMessageInput struct {
	// The ID of the room containing the message.
	RoomID string `json:"roomId"`
	// The event ID of the message to update.
	EventID string `json:"eventId"`
	// The new message content.
	Body string `json:"body"`
	// For thread replies, whether the reply should have a visible channel echo after saving. Omit to preserve current echo state.
	AlsoSendToChannel *bool `json:"alsoSendToChannel,omitempty"`
}

// Input for updating the current user's presence status.
type UpdateMyPresenceInput struct {
	// The presence status to set.
	Status PresenceStatusInput `json:"status"`
}

// Input for updating a user's profile.
type UpdateProfileInput struct {
	// The ID of the user to update. Caller must be self or have admin permission.
	UserID string `json:"userId"`
	// New display name. Omit to leave unchanged.
	DisplayName *string `json:"displayName,omitempty"`
	// New login/username. Omit to leave unchanged. Subject to 30-day cooldown.
	Login *string `json:"login,omitempty"`
}

// Input for updating an existing role.
type UpdateRoleInput struct {
	// Role identifier of the role to update.
	Name string `json:"name"`
	// Human-readable display name.
	DisplayName string `json:"displayName"`
	// Role description.
	Description string `json:"description"`
	// Whether @role pings notify users assigned to this role. Omit to leave unchanged.
	Pingable *bool `json:"pingable,omitempty"`
}

// Input for updating an existing room group.
type UpdateRoomGroupInput struct {
	// The room group's ID.
	ID string `json:"id"`
	// Display name.
	Name string `json:"name"`
	// Optional description.
	Description *string `json:"description,omitempty"`
}

// Input for updating an existing room.
type UpdateRoomInput struct {
	// The ID of the room to update.
	RoomID string `json:"roomId"`
	// The new name for the room.
	Name string `json:"name"`
	// The new description for the room.
	Description *string `json:"description,omitempty"`
}

// Input for updating server configuration.
type UpdateServerConfigInput struct {
	// Welcome message shown on the login page. Set to empty string to clear.
	WelcomeMessage *string `json:"welcomeMessage,omitempty"`
	// Server name for page titles. Set to empty string to use default.
	ServerName *string `json:"serverName,omitempty"`
	// Message of the Day for the header. Set to empty string to clear.
	Motd *string `json:"motd,omitempty"`
	// Short server description for OG link-preview metadata. Set to empty string to clear.
	Description *string `json:"description,omitempty"`
}

// Input for updating a user's settings. All preference fields are optional.
// Only provided fields will be updated; omitted fields are left unchanged.
type UpdateSettingsInput struct {
	// The ID of the user whose settings to update. Caller must be self or have admin permission.
	UserID string `json:"userId"`
	// IANA timezone name. Set to null to clear (revert to browser default).
	Timezone *string `json:"timezone,omitempty"`
	// Time display format. Set to AUTO to use browser locale default.
	TimeFormat *TimeFormat `json:"timeFormat,omitempty"`
}

// Input for uploading a user avatar.
type UploadAvatarInput struct {
	// The ID of the user whose avatar to upload. Caller must be self or have admin permission.
	UserID string `json:"userId"`
	// The avatar image file to upload.
	File graphql.Upload `json:"file"`
}

// Input for uploading the server banner.
type UploadServerBannerInput struct {
	// The banner image file.
	File graphql.Upload `json:"file"`
}

// Input for uploading the server logo.
type UploadServerLogoInput struct {
	// The logo image file.
	File graphql.Upload `json:"file"`
}

// Full snapshot of a user's permission matrix: the permissions that can
// be configured anywhere, the scopes they can be configured at, and the
// state of every cell.
type UserPermissionMatrix struct {
	// The user this matrix describes.
	UserID string `json:"userId"`
	// Permissions to render as rows. Same identifiers used by the role
	// matrix, so the frontend can reuse its grouping / display-name
	// metadata.
	ApplicablePermissions []string `json:"applicablePermissions"`
	// Scopes to render as columns. Server scope first, then groups, then
	// rooms grouped under their parent group via `parentGroupId`.
	Scopes []*PermissionMatrixScope `json:"scopes"`
	// One cell per (permission, scope) intersection. Sparse: a cell is
	// included iff the permission applies at that scope's tier.
	Cells []*PermissionMatrixCell `json:"cells"`
}

// The viewer's notification preference for the server or a room.
// Contains both the explicitly set level and the effective level after inheritance.
type ViewerNotificationPreference struct {
	// The explicitly set level (DEFAULT if not explicitly configured).
	Level NotificationLevel `json:"level"`
	// The effective level after inheritance resolution (never DEFAULT).
	EffectiveLevel NotificationLevel `json:"effectiveLevel"`
}

type VoiceCallIntentInput struct {
	// The room whose voice call is being joined or left.
	RoomID string `json:"roomId"`
}

// Fit mode for image transformations.
type FitMode string

const (
	// Fit within bounds while preserving aspect ratio (letterbox if needed).
	FitModeContain FitMode = "CONTAIN"
	// Fill bounds while preserving aspect ratio (center-crop if needed).
	FitModeCover FitMode = "COVER"
	// Stretch to exact dimensions (may distort aspect ratio).
	FitModeExact FitMode = "EXACT"
)

var AllFitMode = []FitMode{
	FitModeContain,
	FitModeCover,
	FitModeExact,
}

func (e FitMode) IsValid() bool {
	switch e {
	case FitModeContain, FitModeCover, FitModeExact:
		return true
	}
	return false
}

func (e FitMode) String() string {
	return string(e)
}

func (e *FitMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FitMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FitMode", str)
	}
	return nil
}

func (e FitMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FitMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FitMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The kind of decision a role contributed at a given level.
type PermissionDecisionKind string

const (
	// The role explicitly grants the permission.
	PermissionDecisionKindAllow PermissionDecisionKind = "ALLOW"
	// The role explicitly denies the permission.
	PermissionDecisionKindDeny PermissionDecisionKind = "DENY"
	// Used only for overall State; the resolver found no allow or deny anywhere.
	PermissionDecisionKindNone PermissionDecisionKind = "NONE"
)

var AllPermissionDecisionKind = []PermissionDecisionKind{
	PermissionDecisionKindAllow,
	PermissionDecisionKindDeny,
	PermissionDecisionKindNone,
}

func (e PermissionDecisionKind) IsValid() bool {
	switch e {
	case PermissionDecisionKindAllow, PermissionDecisionKindDeny, PermissionDecisionKindNone:
		return true
	}
	return false
}

func (e PermissionDecisionKind) String() string {
	return string(e)
}

func (e *PermissionDecisionKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PermissionDecisionKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PermissionDecisionKind", str)
	}
	return nil
}

func (e PermissionDecisionKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PermissionDecisionKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PermissionDecisionKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The level at which a permission decision was reached during resolution.
type PermissionLevel string

const (
	// Decision came from a role acting at server scope (objectId='any').
	PermissionLevelServer PermissionLevel = "SERVER"
	// Decision came from a per-room-group override (objectId=groupId).
	PermissionLevelGroup PermissionLevel = "GROUP"
	// Decision came from a per-room override (objectId=roomId).
	PermissionLevelRoom PermissionLevel = "ROOM"
)

var AllPermissionLevel = []PermissionLevel{
	PermissionLevelServer,
	PermissionLevelGroup,
	PermissionLevelRoom,
}

func (e PermissionLevel) IsValid() bool {
	switch e {
	case PermissionLevelServer, PermissionLevelGroup, PermissionLevelRoom:
		return true
	}
	return false
}

func (e PermissionLevel) String() string {
	return string(e)
}

func (e *PermissionLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PermissionLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PermissionLevel", str)
	}
	return nil
}

func (e PermissionLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PermissionLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PermissionLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Trinary decision used in the user-permission matrix.
type PermissionMatrixDecision string

const (
	// The permission is explicitly granted.
	PermissionMatrixDecisionAllow PermissionMatrixDecision = "ALLOW"
	// The permission is explicitly denied.
	PermissionMatrixDecisionDeny PermissionMatrixDecision = "DENY"
	// No explicit grant or denial applies at this scope.
	PermissionMatrixDecisionNone PermissionMatrixDecision = "NONE"
)

var AllPermissionMatrixDecision = []PermissionMatrixDecision{
	PermissionMatrixDecisionAllow,
	PermissionMatrixDecisionDeny,
	PermissionMatrixDecisionNone,
}

func (e PermissionMatrixDecision) IsValid() bool {
	switch e {
	case PermissionMatrixDecisionAllow, PermissionMatrixDecisionDeny, PermissionMatrixDecisionNone:
		return true
	}
	return false
}

func (e PermissionMatrixDecision) String() string {
	return string(e)
}

func (e *PermissionMatrixDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PermissionMatrixDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PermissionMatrixDecision", str)
	}
	return nil
}

func (e PermissionMatrixDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PermissionMatrixDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PermissionMatrixDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Where a PermissionMatrixScope sits in the resolution hierarchy.
type PermissionMatrixScopeKind string

const (
	// Server tier — no room/group context.
	PermissionMatrixScopeKindServer PermissionMatrixScopeKind = "SERVER"
	// A room group's scope (channel-room permissions).
	PermissionMatrixScopeKindGroup PermissionMatrixScopeKind = "GROUP"
	// A specific room's scope.
	PermissionMatrixScopeKindRoom PermissionMatrixScopeKind = "ROOM"
)

var AllPermissionMatrixScopeKind = []PermissionMatrixScopeKind{
	PermissionMatrixScopeKindServer,
	PermissionMatrixScopeKindGroup,
	PermissionMatrixScopeKindRoom,
}

func (e PermissionMatrixScopeKind) IsValid() bool {
	switch e {
	case PermissionMatrixScopeKindServer, PermissionMatrixScopeKindGroup, PermissionMatrixScopeKindRoom:
		return true
	}
	return false
}

func (e PermissionMatrixScopeKind) String() string {
	return string(e)
}

func (e *PermissionMatrixScopeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PermissionMatrixScopeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PermissionMatrixScopeKind", str)
	}
	return nil
}

func (e PermissionMatrixScopeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PermissionMatrixScopeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PermissionMatrixScopeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// User presence status on the server.
type PresenceStatus string

const (
	// User is not connected to any client.
	PresenceStatusOffline PresenceStatus = "OFFLINE"
	// User is actively connected.
	PresenceStatusOnline PresenceStatus = "ONLINE"
	// User is connected but idle or inactive.
	PresenceStatusAway PresenceStatus = "AWAY"
	// User has enabled do-not-disturb mode.
	PresenceStatusDoNotDisturb PresenceStatus = "DO_NOT_DISTURB"
)

var AllPresenceStatus = []PresenceStatus{
	PresenceStatusOffline,
	PresenceStatusOnline,
	PresenceStatusAway,
	PresenceStatusDoNotDisturb,
}

func (e PresenceStatus) IsValid() bool {
	switch e {
	case PresenceStatusOffline, PresenceStatusOnline, PresenceStatusAway, PresenceStatusDoNotDisturb:
		return true
	}
	return false
}

func (e PresenceStatus) String() string {
	return string(e)
}

func (e *PresenceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PresenceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PresenceStatus", str)
	}
	return nil
}

func (e PresenceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PresenceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PresenceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Presence statuses clients may explicitly set. Going offline is represented by
// disconnecting and waiting for presence TTL expiry, not by sending OFFLINE.
type PresenceStatusInput string

const (
	// User is actively connected.
	PresenceStatusInputOnline PresenceStatusInput = "ONLINE"
	// User is connected but idle or inactive.
	PresenceStatusInputAway PresenceStatusInput = "AWAY"
	// User has enabled do-not-disturb mode.
	PresenceStatusInputDoNotDisturb PresenceStatusInput = "DO_NOT_DISTURB"
)

var AllPresenceStatusInput = []PresenceStatusInput{
	PresenceStatusInputOnline,
	PresenceStatusInputAway,
	PresenceStatusInputDoNotDisturb,
}

func (e PresenceStatusInput) IsValid() bool {
	switch e {
	case PresenceStatusInputOnline, PresenceStatusInputAway, PresenceStatusInputDoNotDisturb:
		return true
	}
	return false
}

func (e PresenceStatusInput) String() string {
	return string(e)
}

func (e *PresenceStatusInput) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PresenceStatusInput(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PresenceStatusInput", str)
	}
	return nil
}

func (e PresenceStatusInput) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PresenceStatusInput) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PresenceStatusInput) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The kind of room. Used to distinguish regular channels from direct-message
// conversations, both of which can appear in a server's room list.
type RoomType string

const (
	// A regular channel — has a name, optional layout placement, and is governed by the server's RBAC roles.
	RoomTypeChannel RoomType = "CHANNEL"
	// A direct-message conversation — derives its display name from its participants and uses membership plus message permissions.
	RoomTypeDm RoomType = "DM"
)

var AllRoomType = []RoomType{
	RoomTypeChannel,
	RoomTypeDm,
}

func (e RoomType) IsValid() bool {
	switch e {
	case RoomTypeChannel, RoomTypeDm:
		return true
	}
	return false
}

func (e RoomType) String() string {
	return string(e)
}

func (e *RoomType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoomType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoomType", str)
	}
	return nil
}

func (e RoomType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoomType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoomType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Status of video processing.
type VideoProcessingStatus string

const (
	// Upload received and queued for processing; no transcoded variants yet.
	VideoProcessingStatusPending VideoProcessingStatus = "PENDING"
	// Currently transcoding; the video is not yet playable.
	VideoProcessingStatusProcessing VideoProcessingStatus = "PROCESSING"
	// Transcoding finished; at least one variant is available for playback.
	VideoProcessingStatusCompleted VideoProcessingStatus = "COMPLETED"
	// Transcoding failed; `reasonCode` describes the failure and no variants are available.
	VideoProcessingStatusFailed VideoProcessingStatus = "FAILED"
)

var AllVideoProcessingStatus = []VideoProcessingStatus{
	VideoProcessingStatusPending,
	VideoProcessingStatusProcessing,
	VideoProcessingStatusCompleted,
	VideoProcessingStatusFailed,
}

func (e VideoProcessingStatus) IsValid() bool {
	switch e {
	case VideoProcessingStatusPending, VideoProcessingStatusProcessing, VideoProcessingStatusCompleted, VideoProcessingStatusFailed:
		return true
	}
	return false
}

func (e VideoProcessingStatus) String() string {
	return string(e)
}

func (e *VideoProcessingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VideoProcessingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VideoProcessingStatus", str)
	}
	return nil
}

func (e VideoProcessingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VideoProcessingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VideoProcessingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
