package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/nats-io/nats.go/jetstream"
	"hmans.de/chatto/internal/core"
	"hmans.de/chatto/internal/graph/auth"
	"hmans.de/chatto/internal/graph/model"
	configv1 "hmans.de/chatto/internal/pb/chatto/config/v1"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// UpdateServerConfig is the resolver for the updateServerConfig field.
func (r *adminMutationsResolver) UpdateServerConfig(ctx context.Context, obj *model.AdminMutations, input model.UpdateServerConfigInput) (*model.AdminServerConfig, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, core.ErrNotAuthenticated
	}

	// The parent `mutation.admin` resolver gates on `admin.access` — that's
	// the "can enter the admin namespace" check. Each mutation underneath
	// enforces its own capability; for server-config writes that's
	// `server.manage`, not `admin.access`. A moderator with admin-panel
	// view access must not be able to rename the server, change the MOTD,
	// or edit the blocked-usernames list.
	canManage, err := r.core.CanManageServer(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("failed to check server.manage permission: %w", err)
	}
	if !canManage {
		return nil, core.ErrPermissionDenied
	}

	configMgr := r.core.ConfigManager()

	// Use OCC-safe update function to prevent race conditions
	cfg, err := configMgr.UpdateServerConfigFunc(ctx, user.Id, func(current *configv1.ServerConfig) (*configv1.ServerConfig, error) {
		// Start with existing config or empty
		cfg := &configv1.ServerConfig{}
		if current != nil {
			cfg = current
		}

		// Apply input values, preserving existing for nil inputs
		if input.WelcomeMessage != nil {
			cfg.WelcomeMessage = *input.WelcomeMessage
		}
		if input.ServerName != nil {
			cfg.ServerName = *input.ServerName
		}
		if input.Motd != nil {
			cfg.Motd = *input.Motd
		}
		if input.BlockedUsernames != nil {
			cfg.BlockedUsernames = *input.BlockedUsernames
		}
		if input.Description != nil {
			cfg.Description = *input.Description
		}

		return cfg, nil
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update server config: %w", err)
	}

	// Get the effective values (with defaults) for broadcasting
	effectiveName := cfg.ServerName
	if effectiveName == "" {
		effectiveName = "Chatto"
	}

	// Publish live event to notify all connected clients
	if err := r.core.PublishServerConfigUpdated(ctx, user.Id, effectiveName, cfg.Motd, cfg.WelcomeMessage, cfg.BlockedUsernames); err != nil {
		// Log the error but don't fail the mutation - config was saved successfully
		r.logger.Warn("Failed to publish server config update event", "error", err)
	}

	blockedUsernames, err := configMgr.GetEffectiveBlockedUsernames(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get blocked usernames: %w", err)
	}

	// Return the updated config section
	return serverConfigToModel(cfg, blockedUsernames), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *adminMutationsResolver) UpdateUser(ctx context.Context, obj *model.AdminMutations, input model.AdminUpdateUserInput) (*corev1.User, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, core.ErrNotAuthenticated
	}

	if err := r.requireUserAdminTarget(ctx, user.Id, input.UserID); err != nil {
		return nil, err
	}

	if input.Login == nil && input.DisplayName == nil {
		return nil, fmt.Errorf("at least one of login or displayName must be provided")
	}

	var updated *corev1.User
	if input.DisplayName != nil {
		u, err := r.core.AdminUpdateUserDisplayName(ctx, input.UserID, *input.DisplayName)
		if err != nil {
			return nil, err
		}
		updated = u
	}
	if input.Login != nil {
		u, err := r.core.AdminUpdateUserLogin(ctx, input.UserID, *input.Login)
		if err != nil {
			return nil, err
		}
		updated = u
	}
	return updated, nil
}

// ClearUsernameCooldown is the resolver for the clearUsernameCooldown field.
func (r *adminMutationsResolver) ClearUsernameCooldown(ctx context.Context, obj *model.AdminMutations, input model.ClearUsernameCooldownInput) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, core.ErrNotAuthenticated
	}

	if err := r.requireUserAdminTarget(ctx, user.Id, input.UserID); err != nil {
		return false, err
	}

	if err := r.core.ClearLoginChangeCooldown(ctx, input.UserID); err != nil {
		return false, err
	}
	return true, nil
}

// ServerConfig is the resolver for the serverConfig field.
func (r *adminQueriesResolver) ServerConfig(ctx context.Context, obj *model.AdminQueries) (*model.AdminServerConfig, error) {
	configMgr := r.core.ConfigManager()

	cfg, err := configMgr.GetServerConfig(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get server config: %w", err)
	}
	blockedUsernames, err := configMgr.GetEffectiveBlockedUsernames(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get blocked usernames: %w", err)
	}

	return serverConfigToModel(cfg, blockedUsernames), nil
}

// EventLog is the resolver for the eventLog field. The parent
// `admin.*` resolver gates on admin.access; this resolver additionally
// requires admin.view-audit so the event-log inspection view is
// available to auditors specifically rather than every admin-panel
// viewer.
func (r *adminQueriesResolver) EventLog(ctx context.Context, obj *model.AdminQueries, limit *int32, before *string) (*model.EventLogConnection, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, core.ErrNotAuthenticated
	}
	canView, err := r.core.CanAdminAuditView(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("check admin.view-audit: %w", err)
	}
	if !canView {
		return nil, core.ErrPermissionDenied
	}

	stream, err := r.core.EventStreamForDebug(ctx)
	if err != nil {
		return nil, fmt.Errorf("get EVT stream: %w", err)
	}
	info, err := stream.Info(ctx)
	if err != nil {
		return nil, fmt.Errorf("stream info: %w", err)
	}

	pageSize := defaultEventLogPageSize
	if limit != nil {
		pageSize = int(*limit)
		if pageSize < 1 {
			pageSize = 1
		}
		if pageSize > maxEventLogPageSize {
			pageSize = maxEventLogPageSize
		}
	}

	// startSeq is the highest sequence to include on this page.
	startSeq := info.State.LastSeq
	if before != nil && *before != "" {
		parsed, parseErr := strconv.ParseUint(*before, 10, 64)
		if parseErr != nil {
			return nil, fmt.Errorf("invalid before cursor %q: %w", *before, parseErr)
		}
		if parsed == 0 {
			return &model.EventLogConnection{
				Entries:    []*model.EventLogEntry{},
				HasOlder:   false,
				EndCursor:  nil,
				TotalCount: int32(info.State.Msgs),
			}, nil
		}
		startSeq = parsed - 1
	}

	entries, err := r.fetchEventLogPage(ctx, stream, startSeq, info.State.FirstSeq, pageSize)
	if err != nil {
		return nil, err
	}

	conn := &model.EventLogConnection{
		Entries:    entries,
		TotalCount: int32(info.State.Msgs),
	}
	if len(entries) > 0 {
		oldestSeq := entries[len(entries)-1].Sequence
		conn.EndCursor = &oldestSeq
		oldest, _ := strconv.ParseUint(oldestSeq, 10, 64)
		conn.HasOlder = oldest > info.State.FirstSeq
	}
	return conn, nil
}

// EventLogEntry is the resolver for the eventLogEntry field. Returns
// nil if the sequence doesn't exist (or is outside the stream's range).
// Same admin.view-audit gate as EventLog.
func (r *adminQueriesResolver) EventLogEntry(ctx context.Context, obj *model.AdminQueries, sequence string) (*model.EventLogEntry, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, core.ErrNotAuthenticated
	}
	canView, err := r.core.CanAdminAuditView(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("check admin.view-audit: %w", err)
	}
	if !canView {
		return nil, core.ErrPermissionDenied
	}

	seq, err := strconv.ParseUint(sequence, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid sequence %q: %w", sequence, err)
	}
	stream, err := r.core.EventStreamForDebug(ctx)
	if err != nil {
		return nil, fmt.Errorf("get EVT stream: %w", err)
	}
	msg, err := stream.GetMsg(ctx, seq)
	if err != nil {
		if errors.Is(err, jetstream.ErrMsgNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("get msg %d: %w", seq, err)
	}
	return streamMsgToEventLogEntry(msg)
}

// Projections is the resolver for the projections field. It uses
// admin.view-system: projection lag and RAM estimates are operational health
// data, distinct from the audit-gated raw EVT event log.
func (r *adminQueriesResolver) Projections(ctx context.Context, obj *model.AdminQueries) ([]*model.ProjectionState, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, core.ErrNotAuthenticated
	}
	canView, err := r.core.CanAdminSystemView(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("check admin.view-system: %w", err)
	}
	if !canView {
		return nil, core.ErrPermissionDenied
	}

	states, err := r.core.ProjectionAdminStates(ctx)
	if err != nil {
		return nil, fmt.Errorf("projection states: %w", err)
	}
	out := make([]*model.ProjectionState, 0, len(states))
	for _, state := range states {
		out = append(out, projectionStateToModel(state))
	}
	return out, nil
}

// Admin is the resolver for the admin field.
func (r *mutationResolver) Admin(ctx context.Context) (*model.AdminMutations, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, nil // Not authenticated, return null
	}

	// Single gate on `admin.access`. Owner / admin pass via their
	// enumerated permission set; moderators pass via the default
	// moderator grant; everyone else gets a null result. Per-mutation
	// gates underneath enforce their own capability (e.g.
	// UpdateServerConfig requires `server.manage`).
	canView, err := r.core.CanAdminAccess(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("failed to check admin permission: %w", err)
	}
	if !canView {
		return nil, nil
	}
	return &model.AdminMutations{}, nil
}

// Admin is the resolver for the admin field.
func (r *queryResolver) Admin(ctx context.Context) (*model.AdminQueries, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, nil // Not authenticated, return null
	}

	canView, err := r.core.CanAdminAccess(ctx, user.Id)
	if err != nil {
		return nil, fmt.Errorf("failed to check admin permission: %w", err)
	}
	if !canView {
		return nil, nil
	}

	// Fetch system info
	connInfo := r.core.GetConnectionInfo()
	connection := &model.ConnectionInfo{
		Connected:  connInfo.Connected,
		ServerID:   connInfo.ServerID,
		ServerName: connInfo.ServerName,
		Version:    connInfo.Version,
		MaxPayload: int(connInfo.MaxPayload),
		Rtt:        connInfo.RTT,
	}

	accInfo, err := r.core.GetAccountInfo(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get account info: %w", err)
	}
	account := &model.AccountInfo{
		Memory:        int(accInfo.Memory),
		MemoryUsed:    int(accInfo.MemoryUsed),
		Storage:       int(accInfo.Storage),
		StorageUsed:   int(accInfo.StorageUsed),
		Streams:       int32(accInfo.Streams),
		StreamsUsed:   int32(accInfo.StreamsUsed),
		Consumers:     int32(accInfo.Consumers),
		ConsumersUsed: int32(accInfo.ConsumersUsed),
	}

	coreStats, err := r.core.GetStats(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get server stats: %w", err)
	}
	stats := &model.ServerStats{
		UserCount:        int32(coreStats.UserCount),
		ChannelRoomCount: int32(coreStats.ChannelRoomCount),
		DmRoomCount:      int32(coreStats.DMRoomCount),
	}

	natsStats, err := r.core.GetJetStreamStats(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get NATS stats: %w", err)
	}

	systemInfo := &model.SystemInfo{
		Connection: connection,
		Account:    account,
		Nats:       natsStatsToModel(natsStats),
		Stats:      stats,
	}

	// Fetch all permissions applicable at server scope
	// This includes permissions like room.create, message.post that can have server-wide defaults
	allPerms := core.PermissionsForScope(core.ScopeServer)
	serverPermissionsList := make([]string, len(allPerms))
	for i, p := range allPerms {
		serverPermissionsList[i] = string(p.Permission)
	}

	return &model.AdminQueries{
		SystemInfo:        systemInfo,
		ServerPermissions: serverPermissionsList,
	}, nil
}

// AdminMutations returns AdminMutationsResolver implementation.
func (r *Resolver) AdminMutations() AdminMutationsResolver { return &adminMutationsResolver{r} }

// AdminQueries returns AdminQueriesResolver implementation.
func (r *Resolver) AdminQueries() AdminQueriesResolver { return &adminQueriesResolver{r} }

type adminMutationsResolver struct{ *Resolver }
type adminQueriesResolver struct{ *Resolver }
