package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"strings"

	"hmans.de/chatto/internal/graph/model"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// ImageURL is the resolver for the imageUrl field on LinkPreview.
func (r *linkPreviewResolver) ImageURL(ctx context.Context, obj *corev1.LinkPreview, width *int32, height *int32, fit *model.FitMode) (*string, error) {
	imageAssetId := obj.GetImageAssetId()
	if imageAssetId == "" {
		return nil, nil
	}

	if width != nil && height != nil && fit != nil {
		fitLower := strings.ToLower(string(*fit))
		url := r.core.GetTransformedServerAssetURL(imageAssetId, int(*width), int(*height), fitLower)
		return &url, nil
	}

	// Default: 400x400 contain for backwards compatibility
	url := r.core.GetTransformedServerAssetURL(imageAssetId, 400, 400, "contain")
	return &url, nil
}

// LinkPreview is the resolver for the linkPreview field.
// Lazy-loads the link preview from the MessageBody in the KV bucket.
func (r *messagePostedEventResolver) LinkPreview(ctx context.Context, obj *model.MessagePostedEvent) (*corev1.LinkPreview, error) {
	payload := messagePostedPayload(obj)
	if payload == nil {
		return nil, nil
	}
	kind, err := r.core.FindRoomKind(ctx, payload.RoomId)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve room kind: %w", err)
	}
	messageBody, err := r.core.GetFullMessageBody(ctx, kind, bodyKeyForLookup(obj))
	if err != nil {
		return nil, fmt.Errorf("failed to load message body: %w", err)
	}
	if messageBody == nil {
		return nil, nil // Message was deleted
	}
	return messageBody.LinkPreview, nil
}

// LinkPreview is the resolver for the linkPreview field.
func (r *queryResolver) LinkPreview(ctx context.Context, url string) (*corev1.LinkPreview, error) {
	// Require authentication to prevent abuse
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	preview, err := r.core.GetLinkPreview(ctx, url)
	if err != nil {
		// Return nil instead of error for failed fetches - client can handle missing preview gracefully
		r.logger.Debug("Failed to get link preview", "url", url, "error", err)
		return nil, nil
	}

	return preview, nil
}

// LinkPreview returns LinkPreviewResolver implementation.
func (r *Resolver) LinkPreview() LinkPreviewResolver { return &linkPreviewResolver{r} }

type linkPreviewResolver struct{ *Resolver }
