package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
	"hmans.de/chatto/internal/assets"
	"hmans.de/chatto/internal/core"
	"hmans.de/chatto/internal/graph/model"
	configv1 "hmans.de/chatto/internal/pb/chatto/config/v1"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input model.CreateRoomInput) (*corev1.Room, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind := core.KindChannel

	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}

	// Authorization: check CanCreateRoom permission
	can, err := r.core.CanCreateRoom(ctx, user.Id, kind)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	return r.core.CreateRoom(ctx, user.Id, kind, input.Name, desc)
}

// UpdateRoom is the resolver for the updateRoom field.
func (r *mutationResolver) UpdateRoom(ctx context.Context, input model.UpdateRoomInput) (*corev1.Room, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return nil, err
	}

	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}

	can, err := r.core.CanManageAnyRoom(ctx, user.Id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	return r.core.UpdateRoom(ctx, user.Id, kind, input.RoomID, input.Name, desc)
}

// ArchiveRoom is the resolver for the archiveRoom field.
func (r *mutationResolver) ArchiveRoom(ctx context.Context, input model.ArchiveRoomInput) (*corev1.Room, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return nil, err
	}

	can, err := r.core.CanManageAnyRoom(ctx, user.Id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	return r.core.ArchiveRoom(ctx, user.Id, kind, input.RoomID)
}

// UnarchiveRoom is the resolver for the unarchiveRoom field.
func (r *mutationResolver) UnarchiveRoom(ctx context.Context, input model.UnarchiveRoomInput) (*corev1.Room, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return nil, err
	}

	can, err := r.core.CanManageAnyRoom(ctx, user.Id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	return r.core.UnarchiveRoom(ctx, user.Id, kind, input.RoomID)
}

// SetRoomAutoJoin is the resolver for the setRoomAutoJoin field.
func (r *mutationResolver) SetRoomAutoJoin(ctx context.Context, input model.SetRoomAutoJoinInput) (*corev1.Room, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return nil, err
	}

	can, err := r.core.CanManageAnyRoom(ctx, user.Id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	return r.core.SetRoomAutoJoin(ctx, user.Id, kind, input.RoomID, input.AutoJoin)
}

// UpdateRoomLayout is the resolver for the updateRoomLayout field.
// Updates the room layout for a space. Requires room.manage permission.
func (r *mutationResolver) UpdateRoomLayout(ctx context.Context, input model.UpdateRoomLayoutInput) (*model.RoomLayoutModel, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind := core.KindChannel

	// Authorization: require room.manage permission
	can, err := r.core.CanManageAnyRoom(ctx, user.Id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	// Validate input: no duplicate room IDs across sections or unsectioned list, section names non-empty
	seenRoomIDs := make(map[string]bool)
	for _, section := range input.Sections {
		if strings.TrimSpace(section.Name) == "" {
			return nil, fmt.Errorf("section name must not be empty")
		}
		for _, roomID := range section.RoomIds {
			if seenRoomIDs[roomID] {
				return nil, fmt.Errorf("duplicate room ID %q across sections", roomID)
			}
			seenRoomIDs[roomID] = true
		}
	}
	for _, roomID := range input.UnsectionedRoomIds {
		if seenRoomIDs[roomID] {
			return nil, fmt.Errorf("room ID %q appears in both sections and unsectioned list", roomID)
		}
		seenRoomIDs[roomID] = true
	}

	// Convert input to proto
	layout := &corev1.RoomLayout{
		Sections:        make([]*corev1.RoomLayoutSection, len(input.Sections)),
		UnsortedRoomIds: input.UnsectionedRoomIds,
	}
	for i, s := range input.Sections {
		layout.Sections[i] = &corev1.RoomLayoutSection{
			Id:      s.ID,
			Name:    s.Name,
			RoomIds: s.RoomIds,
		}
	}

	// Store
	result, err := r.core.UpdateRoomLayout(ctx, kind, layout)
	if err != nil {
		return nil, err
	}

	// Publish live event (best-effort)
	if pubErr := r.core.PublishRoomLayoutUpdated(ctx, user.Id, kind); pubErr != nil {
		r.logger.Warn("Failed to publish room layout updated event", "error", pubErr, "kind", kind)
	}

	// For the mutation response, fetch all rooms so the response can resolve section rooms.
	// The admin performing this action can manage rooms, so show all rooms in the space.
	allRooms, err := r.core.ListRooms(ctx, kind)
	if err != nil {
		return nil, err
	}
	allRoomMap := make(map[string]*corev1.Room, len(allRooms))
	for _, room := range allRooms {
		allRoomMap[room.Id] = room
	}

	return protoLayoutToModel(result, allRoomMap), nil
}

// PostMessage is the resolver for the postMessage field.
func (r *mutationResolver) PostMessage(ctx context.Context, input model.PostMessageInput) (*corev1.Event, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return nil, err
	}

	// Authorization: check room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	// Authorization: check posting permissions
	if kind == core.KindDM {
		// DM space: check dm.write permission (skip message.* checks)
		can, err := r.core.CanDMWrite(ctx, user.Id)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, core.ErrPermissionDenied
		}
	} else if input.InThread != nil && *input.InThread != "" {
		// Thread reply: check message.post-in-thread
		can, err := r.core.CanPostInThread(ctx, user.Id, kind, input.RoomID)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, core.ErrPermissionDenied
		}
	} else {
		// Root message: check message.post
		can, err := r.core.CanPostMessage(ctx, user.Id, kind, input.RoomID)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, core.ErrPermissionDenied
		}
	}

	// Authorization: check reply attribution permissions (inReplyTo)
	if kind != "dm" && input.InReplyTo != nil && *input.InReplyTo != "" {
		if input.InThread != nil && *input.InThread != "" {
			// Reply in thread: check message.reply-in-thread
			can, err := r.core.CanReplyInThread(ctx, user.Id, kind, input.RoomID)
			if err != nil {
				return nil, err
			}
			if !can {
				return nil, core.ErrPermissionDenied
			}
		} else {
			// Reply in room: check message.reply
			can, err := r.core.CanReply(ctx, user.Id, kind, input.RoomID)
			if err != nil {
				return nil, err
			}
			if !can {
				return nil, core.ErrPermissionDenied
			}
		}
	}

	// Extract body (optional, defaults to empty string)
	body := ""
	if input.Body != nil {
		body = *input.Body
	}

	// Process file uploads if any (file uploads stay direct via HTTP)
	var attachments []*corev1.Attachment
	animatedGIFs := map[string]bool{} // track animated GIFs for video processing
	if input.Attachments != nil {
		for _, upload := range input.Attachments {
			var reader io.Reader = upload.File

			// Detect animated GIFs: buffer the file to check frame count,
			// then route through the video pipeline for GIF-to-MP4 conversion.
			if r.videoConfig.Enabled && upload.ContentType == "image/gif" {
				data, err := io.ReadAll(upload.File)
				if err != nil {
					return nil, fmt.Errorf("failed to read attachment %s: %w", upload.Filename, err)
				}
				if assets.IsAnimatedGIF(data) {
					animatedGIFs[upload.Filename] = true
				}
				reader = bytes.NewReader(data)
			}

			attachment, err := r.core.UploadAttachment(
				ctx,
				core.SpaceIDForKind(kind),
				input.RoomID,
				upload.Filename,
				upload.ContentType,
				reader,
			)
			if err != nil {
				return nil, fmt.Errorf("failed to upload attachment %s: %w", upload.Filename, err)
			}
			if animatedGIFs[upload.Filename] {
				animatedGIFs[attachment.Id] = true
			}
			attachments = append(attachments, attachment)
		}
	}

	// Get threading fields if provided
	var inThread string
	if input.InThread != nil {
		inThread = *input.InThread
	}
	var inReplyTo string
	if input.InReplyTo != nil {
		inReplyTo = *input.InReplyTo
	}

	// Extract alsoSendToChannel from input (defaults to false)
	alsoSendToChannel := input.AlsoSendToChannel != nil && *input.AlsoSendToChannel

	// Authorization: if echoing to channel, check message.echo AND message.post permissions.
	// An echo creates a root-level message, so it requires the same permission as posting directly.
	if alsoSendToChannel {
		if inThread == "" {
			return nil, fmt.Errorf("alsoSendToChannel can only be used with thread replies (inThread must be set)")
		}
		can, err := r.core.CanEchoMessage(ctx, user.Id, kind, input.RoomID)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, core.ErrPermissionDenied
		}
		can, err = r.core.CanPostMessage(ctx, user.Id, kind, input.RoomID)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, core.ErrPermissionDenied
		}
	}

	// Convert link preview input to proto if provided
	var linkPreview *corev1.LinkPreview
	if lp := input.LinkPreview; lp != nil {
		linkPreview = &corev1.LinkPreview{
			Url: lp.URL,
		}
		if lp.Title != nil {
			linkPreview.Title = *lp.Title
		}
		if lp.Description != nil {
			linkPreview.Description = *lp.Description
		}
		if lp.SiteName != nil {
			linkPreview.SiteName = *lp.SiteName
		}
		linkPreview.ImageAssetId = lp.ImageAssetID
		if lp.EmbedType != nil {
			linkPreview.EmbedType = *lp.EmbedType
		}
		linkPreview.EmbedId = lp.EmbedID
	}

	// Set PENDING state for video/animated-GIF attachments BEFORE PostMessage, so that
	// when the subscription delivers the event the videoProcessing field is already populated.
	if r.videoConfig.Enabled {
		for _, att := range attachments {
			if strings.HasPrefix(att.ContentType, "video/") || animatedGIFs[att.Id] {
				if err := r.core.InitVideoProcessingState(ctx, att.Id); err != nil {
					r.logger.Warn("Failed to init video processing state", "attachment_id", att.Id, "error", err)
				}
			}
		}
	}

	event, err := r.core.PostMessage(ctx, kind, input.RoomID, user.Id, body, attachments, inThread, inReplyTo, linkPreview, alsoSendToChannel)
	if err != nil {
		return nil, err
	}

	// Publish processing requests (needs messageBodyId from PostMessage response)
	if r.videoConfig.Enabled {
		if msg := event.GetMessagePosted(); msg != nil {
			for _, att := range attachments {
				if strings.HasPrefix(att.ContentType, "video/") || animatedGIFs[att.Id] {
					if err := r.core.PublishVideoProcessingRequest(ctx, core.SpaceIDForKind(kind), input.RoomID, att.Id, att.ContentType, msg.MessageBodyId); err != nil {
						r.logger.Warn("Failed to request video processing", "attachment_id", att.Id, "error", err)
					}
				}
			}
		}
	}

	// Auto-mark room as read since user is viewing it (avoids separate
	// MarkRoomAsRead call). For root posts, we know the just-published event
	// is the new last root. For thread replies, we look up the room's current
	// last root so that posting in a thread also acknowledges any recent
	// channel activity (preserves prior behavior).
	var lastRootID string
	if inThread == "" {
		lastRootID = event.Id
	} else {
		id, _, exists, err := r.core.GetRoomLastEvent(ctx, kind, input.RoomID)
		if err != nil {
			r.logger.Warn("Failed to get room last event for auto-mark-read", "error", err)
		} else if exists {
			lastRootID = id
		}
	}
	if lastRootID != "" {
		if err := r.core.SetLastReadEventID(ctx, kind, user.Id, input.RoomID, lastRootID); err != nil {
			r.logger.Warn("Failed to auto-mark room as read", "error", err)
		} else {
			r.core.NotifyRoomMarkedAsRead(ctx, user.Id, kind, input.RoomID)
			if err := r.core.ClearMentionStatus(ctx, input.RoomID, user.Id); err != nil {
				r.logger.Warn("Failed to clear mention status", "error", err)
			}
		}
	}

	return event, nil
}

// UpdateServer is the resolver for the updateServer field.
func (r *mutationResolver) UpdateServer(ctx context.Context, input model.UpdateServerInput) (*model.Server, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	can, err := r.core.CanManageServer(ctx, user.Id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	// The server name, description, motd, and welcome message are all
	// canonical state on the runtime-editable InstanceConfig (KV) — that's
	// what the resolver reads on reload. The chrome header listens for
	// ServerUpdatedEvent (published below) to refresh name/logo/banner.
	if cm := r.core.ConfigManager(); cm != nil {
		updated, err := cm.UpdateInstanceConfigFunc(ctx, func(cfg *configv1.ServerConfig) (*configv1.ServerConfig, error) {
			if cfg == nil {
				cfg = &configv1.ServerConfig{}
			}
			cfg.ServerName = input.Name
			if input.Description != nil {
				cfg.Description = *input.Description
			}
			if input.Motd != nil {
				cfg.Motd = *input.Motd
			}
			if input.WelcomeMessage != nil {
				cfg.WelcomeMessage = *input.WelcomeMessage
			}
			return cfg, nil
		})
		if err != nil {
			return nil, fmt.Errorf("save instance config: %w", err)
		}
		// Live-update is best-effort; the config write already succeeded.
		_ = r.core.PublishServerConfigUpdated(
			ctx,
			user.Id,
			updated.ServerName,
			updated.Motd,
			updated.WelcomeMessage,
			updated.BlockedUsernames,
		)
		// Publish ServerUpdatedEvent so the chrome header picks up the new
		// name immediately (same path used by logo/banner upload).
		r.core.PublishServerBrandingUpdate(ctx, user.Id)
	}

	return r.serverModel(), nil
}

// UploadServerLogo is the resolver for the uploadServerLogo field.
func (r *mutationResolver) UploadServerLogo(ctx context.Context, input model.UploadServerLogoInput) (*model.Server, error) {
	user, err := r.requireInstanceManager(ctx)
	if err != nil {
		return nil, err
	}

	asset, err := r.core.UploadServerLogo(ctx, input.File.File)
	if err != nil {
		return nil, fmt.Errorf("failed to upload logo: %w", err)
	}

	if err := r.core.SetServerLogo(ctx, user.Id, asset); err != nil {
		r.core.CleanupAsset(ctx, asset)
		return nil, fmt.Errorf("failed to save logo: %w", err)
	}

	return r.serverModel(), nil
}

// DeleteServerLogo is the resolver for the deleteServerLogo field.
func (r *mutationResolver) DeleteServerLogo(ctx context.Context) (*model.Server, error) {
	user, err := r.requireInstanceManager(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.core.DeleteServerLogo(ctx, user.Id); err != nil {
		return nil, fmt.Errorf("failed to delete logo: %w", err)
	}

	return r.serverModel(), nil
}

// UploadServerBanner is the resolver for the uploadServerBanner field.
func (r *mutationResolver) UploadServerBanner(ctx context.Context, input model.UploadServerBannerInput) (*model.Server, error) {
	user, err := r.requireInstanceManager(ctx)
	if err != nil {
		return nil, err
	}

	asset, err := r.core.UploadServerBanner(ctx, input.File.File)
	if err != nil {
		return nil, fmt.Errorf("failed to upload banner: %w", err)
	}

	if err := r.core.SetServerBanner(ctx, user.Id, asset); err != nil {
		r.core.CleanupAsset(ctx, asset)
		return nil, fmt.Errorf("failed to save banner: %w", err)
	}

	return r.serverModel(), nil
}

// DeleteServerBanner is the resolver for the deleteServerBanner field.
func (r *mutationResolver) DeleteServerBanner(ctx context.Context) (*model.Server, error) {
	user, err := r.requireInstanceManager(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.core.DeleteServerBanner(ctx, user.Id); err != nil {
		return nil, fmt.Errorf("failed to delete banner: %w", err)
	}

	return r.serverModel(), nil
}

// JoinRoom is the resolver for the joinRoom field.
func (r *mutationResolver) JoinRoom(ctx context.Context, input model.JoinRoomInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: check CanJoinRoom (includes space membership check)
	can, err := r.core.CanJoinRoom(ctx, user.Id, kind)
	if err != nil {
		return false, err
	}
	if !can {
		return false, core.ErrPermissionDenied
	}

	_, err = r.core.JoinRoom(ctx, user.Id, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// LeaveRoom is the resolver for the leaveRoom field.
func (r *mutationResolver) LeaveRoom(ctx context.Context, input model.LeaveRoomInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Core handles DM conversation check (ErrCannotLeaveDMConversation)
	if err := r.core.LeaveRoom(ctx, user.Id, kind, user.Id, input.RoomID); err != nil {
		return false, err
	}

	return true, nil
}

// MarkRoomAsRead is the resolver for the markRoomAsRead field.
func (r *mutationResolver) MarkRoomAsRead(ctx context.Context, input model.MarkRoomAsReadInput) (*model.MarkRoomAsReadResult, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return nil, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	// Get the user's previous last-read event ID (before updating)
	previousEventID, err := r.core.GetLastReadEventID(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return nil, err
	}

	// Resolve the target event ID for the new marker. If the client passed
	// an explicit upToEventId (i.e. "I've read up to this event"), prefer
	// that — it avoids the race where messages land between subscription
	// delivery and mutation processing on the server. Otherwise fall back
	// to whatever the room's current latest root event is.
	var (
		lastEventID string
		lastTime    time.Time
		hasLast     bool
	)
	if input.UpToEventID != nil && *input.UpToEventID != "" {
		targetTime, terr := r.core.GetEventTimestamp(ctx, kind, input.RoomID, *input.UpToEventID)
		if terr != nil {
			return nil, terr
		}
		if !targetTime.IsZero() {
			lastEventID = *input.UpToEventID
			lastTime = targetTime
			hasLast = true
		}
	}
	if !hasLast {
		lastEventID, lastTime, hasLast, err = r.core.GetRoomLastEvent(ctx, kind, input.RoomID)
		if err != nil {
			return nil, err
		}
	}

	if hasLast {
		// Advance-only: don't regress the marker if the client passed a
		// stale upToEventId (e.g. another tab/device is further ahead).
		shouldWrite := true
		if previousEventID != "" && previousEventID != lastEventID {
			prevTime, perr := r.core.GetEventTimestamp(ctx, kind, input.RoomID, previousEventID)
			if perr == nil && !prevTime.IsZero() && !lastTime.After(prevTime) {
				shouldWrite = false
				lastEventID = previousEventID
				lastTime = prevTime
			}
		}
		if shouldWrite {
			if err := r.core.SetLastReadEventID(ctx, kind, user.Id, input.RoomID, lastEventID); err != nil {
				return nil, err
			}
		}
	}

	// Notify user that they marked a room as read (for space unread indicator updates)
	r.core.NotifyRoomMarkedAsRead(ctx, user.Id, kind, input.RoomID)

	// Also clear any unread mention indicator for this room
	if err := r.core.ClearMentionStatus(ctx, input.RoomID, user.Id); err != nil {
		// Log but don't fail - marking read is still successful
		r.logger.Warn("Failed to clear mention status", "space_id", kind, "room_id", input.RoomID, "error", err)
	}

	result := &model.MarkRoomAsReadResult{}

	// Resolve timestamps for the read boundaries
	if hasLast && !lastTime.IsZero() {
		result.LastReadAt = timestamppb.New(lastTime)
	}
	if previousEventID != "" {
		if t, err := r.core.GetEventTimestamp(ctx, kind, input.RoomID, previousEventID); err == nil && !t.IsZero() {
			result.PreviousLastReadAt = timestamppb.New(t)
		}
	}

	return result, nil
}

// MarkThreadAsRead is the resolver for the markThreadAsRead field.
func (r *mutationResolver) MarkThreadAsRead(ctx context.Context, input model.MarkThreadAsReadInput) (*model.MarkThreadAsReadResult, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return nil, err
	}

	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	// Anchor the read cursor at a specific event's timestamp if the client
	// provided one. This avoids the race where new replies arrive between
	// the subscription delivery and the mutation hitting the server. Falls
	// back to wall-clock "now" when no explicit anchor is supplied.
	markerTime := time.Now()
	if input.UpToEventID != nil && *input.UpToEventID != "" {
		event, eerr := r.core.GetRoomEventByEventID(ctx, kind, input.RoomID, *input.UpToEventID)
		if eerr != nil {
			return nil, eerr
		}
		if event != nil && event.CreatedAt != nil {
			markerTime = event.CreatedAt.AsTime()
		}
	}

	previousReadAt, err := r.core.SetThreadLastOpenedAt(ctx, kind, user.Id, input.RoomID, input.ThreadRootEventID, markerTime)
	if err != nil {
		return nil, err
	}

	res := &model.MarkThreadAsReadResult{}
	if !previousReadAt.IsZero() {
		res.PreviousReadAt = timestamppb.New(previousReadAt)
	}
	return res, nil
}

// FollowThread is the resolver for the followThread field.
func (r *mutationResolver) FollowThread(ctx context.Context, input model.FollowThreadInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	if err := r.core.FollowThread(ctx, kind, user.Id, input.RoomID, input.ThreadRootEventID); err != nil {
		return false, err
	}
	return true, nil
}

// UnfollowThread is the resolver for the unfollowThread field.
func (r *mutationResolver) UnfollowThread(ctx context.Context, input model.UnfollowThreadInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	if err := r.core.UnfollowThread(ctx, kind, user.Id, input.RoomID, input.ThreadRootEventID); err != nil {
		return false, err
	}
	return true, nil
}

// AddReaction is the resolver for the addReaction field.
func (r *mutationResolver) AddReaction(ctx context.Context, input model.AddReactionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: check room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	// Authorization: check message.react permission at room level
	can, err := r.core.CanReactToMessage(ctx, user.Id, kind, input.RoomID)
	if err != nil {
		return false, err
	}
	if !can {
		return false, core.ErrPermissionDenied
	}

	return r.core.AddReaction(ctx, kind, input.RoomID, input.MessageEventID, input.Emoji, user.Id)
}

// RemoveReaction is the resolver for the removeReaction field.
func (r *mutationResolver) RemoveReaction(ctx context.Context, input model.RemoveReactionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: check room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	// Authorization: check message.react permission at room level
	can, err := r.core.CanReactToMessage(ctx, user.Id, kind, input.RoomID)
	if err != nil {
		return false, err
	}
	if !can {
		return false, core.ErrPermissionDenied
	}

	return r.core.RemoveReaction(ctx, kind, input.RoomID, input.MessageEventID, input.Emoji, user.Id)
}

// SendTypingIndicator is the resolver for the sendTypingIndicator field.
func (r *mutationResolver) SendTypingIndicator(ctx context.Context, input model.SendTypingIndicatorInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: check room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	// Publish the typing indicator (live-only event, no permission check beyond membership)
	if err := r.core.PublishTypingIndicator(ctx, user.Id, kind, input.RoomID, input.ThreadRootEventID); err != nil {
		return false, err
	}

	return true, nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, input model.DeleteMessageInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: check room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	// Resolve event ID to internal body key
	messageBodyKey, err := r.resolveMessageBodyKey(ctx, kind, input.RoomID, input.EventID)
	if err != nil {
		return false, err
	}

	// Authorization: check ownership and permissions
	authorID, err := r.core.GetMessageAuthorID(ctx, kind, messageBodyKey)
	if err != nil {
		return false, err
	}
	if authorID == "" {
		// Message already deleted, nothing to do
		return true, nil
	}

	if user.Id == authorID {
		// Author deleting own message: check message.delete.own permission
		can, err := r.core.CanDeleteOwnMessage(ctx, user.Id, kind, input.RoomID)
		if err != nil {
			return false, err
		}
		if !can {
			return false, core.ErrPermissionDenied
		}
	} else {
		// Non-author deleting: check message.delete-any permission AND
		// strict-outrank on the author. The rank check prevents a
		// moderator from deleting messages of higher-ranked users
		// (admins, owners) — see requireOutranksAuthor.
		can, err := r.core.CanDeleteAnyMessage(ctx, user.Id, kind, input.RoomID)
		if err != nil {
			return false, err
		}
		if !can {
			return false, core.ErrPermissionDenied
		}
		if err := r.requireOutranksAuthor(ctx, user.Id, authorID); err != nil {
			return false, err
		}
	}

	if err := r.core.DeleteMessage(ctx, user.Id, kind, input.RoomID, messageBodyKey); err != nil {
		return false, err
	}

	return true, nil
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, input model.EditMessageInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: check room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	// Resolve event ID to internal body key
	messageBodyKey, err := r.resolveMessageBodyKey(ctx, kind, input.RoomID, input.EventID)
	if err != nil {
		return false, err
	}

	// Get the message to determine authorship
	messageBody, err := r.core.GetFullMessageBody(ctx, kind, messageBodyKey)
	if err != nil {
		return false, err
	}
	if messageBody == nil {
		return false, core.ErrMessageNotFound
	}

	// Authorization: two-tier permission check based on authorship
	isAuthor := messageBody.AuthorId == user.Id
	if isAuthor {
		can, err := r.core.CanEditOwnMessage(ctx, user.Id, kind, input.RoomID)
		if err != nil {
			return false, err
		}
		if !can {
			return false, core.ErrPermissionDenied
		}
		// Edit window is enforced in Core.EditMessage for author edits
	} else {
		// Non-author editing: check message.edit-any permission AND
		// strict-outrank on the author. The rank check prevents a
		// moderator from editing messages of higher-ranked users
		// (admins, owners) — see requireOutranksAuthor.
		can, err := r.core.CanEditAnyMessage(ctx, user.Id, kind, input.RoomID)
		if err != nil {
			return false, err
		}
		if !can {
			return false, core.ErrPermissionDenied
		}
		if err := r.requireOutranksAuthor(ctx, user.Id, messageBody.AuthorId); err != nil {
			return false, err
		}
	}

	if err := r.core.EditMessage(ctx, user.Id, kind, input.RoomID, messageBodyKey, input.Body); err != nil {
		return false, err
	}

	return true, nil
}

// DeleteAttachment is the resolver for the deleteAttachment field.
func (r *mutationResolver) DeleteAttachment(ctx context.Context, input model.DeleteAttachmentInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: check room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	// Resolve event ID to internal body key
	messageBodyKey, err := r.resolveMessageBodyKey(ctx, kind, input.RoomID, input.EventID)
	if err != nil {
		return false, err
	}

	// Core handles ownership check - only author can delete their attachments
	if err := r.core.DeleteAttachmentFromMessage(ctx, user.Id, kind, input.RoomID, messageBodyKey, input.AttachmentID); err != nil {
		return false, err
	}

	return true, nil
}

// DeleteLinkPreview is the resolver for the deleteLinkPreview field.
func (r *mutationResolver) DeleteLinkPreview(ctx context.Context, input model.DeleteLinkPreviewInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	kind, err := r.resolveRoomKind(ctx, input.RoomID)
	if err != nil {
		return false, err
	}

	// Authorization: check room membership
	isMember, err := r.core.RoomMembershipExists(ctx, kind, user.Id, input.RoomID)
	if err != nil {
		return false, err
	}
	if !isMember {
		return false, core.ErrNotRoomMember
	}

	// Resolve event ID to internal body key
	messageBodyKey, err := r.resolveMessageBodyKey(ctx, kind, input.RoomID, input.EventID)
	if err != nil {
		return false, err
	}

	// Core handles ownership check - only author can delete their link previews
	if err := r.core.DeleteLinkPreviewFromMessage(ctx, user.Id, kind, input.RoomID, messageBodyKey, input.URL); err != nil {
		return false, err
	}

	return true, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*corev1.User, error) {
	if _, err := r.requireSelfOrUserAdminTarget(ctx, input.UserID); err != nil {
		return nil, err
	}

	if input.DisplayName == nil && input.Login == nil {
		return nil, fmt.Errorf("at least one of displayName or login must be provided")
	}

	var updatedUser *corev1.User
	var err error

	if input.DisplayName != nil {
		updatedUser, err = r.core.UpdateUserDisplayName(ctx, input.UserID, *input.DisplayName)
		if err != nil {
			return nil, err
		}
	}

	if input.Login != nil {
		updatedUser, err = r.core.UpdateUserLogin(ctx, input.UserID, *input.Login)
		if err != nil {
			return nil, err
		}
	}

	return updatedUser, nil
}

// UploadAvatar is the resolver for the uploadAvatar field.
func (r *mutationResolver) UploadAvatar(ctx context.Context, input model.UploadAvatarInput) (*corev1.User, error) {
	if _, err := r.requireSelfOrUserAdminTarget(ctx, input.UserID); err != nil {
		return nil, err
	}

	asset, err := r.core.UploadUserAvatar(ctx, input.UserID, input.File.File)
	if err != nil {
		return nil, fmt.Errorf("failed to upload avatar: %w", err)
	}

	if err := r.core.SetUserAvatar(ctx, input.UserID, asset); err != nil {
		r.core.CleanupAsset(ctx, asset)
		return nil, fmt.Errorf("failed to save avatar: %w", err)
	}

	return r.core.GetUser(ctx, input.UserID)
}

// DeleteAvatar is the resolver for the deleteAvatar field.
func (r *mutationResolver) DeleteAvatar(ctx context.Context, userID string) (*corev1.User, error) {
	if _, err := r.requireSelfOrUserAdminTarget(ctx, userID); err != nil {
		return nil, err
	}

	if err := r.core.DeleteUserAvatar(ctx, userID); err != nil {
		return nil, fmt.Errorf("failed to delete avatar: %w", err)
	}

	return r.core.GetUser(ctx, userID)
}

// RequestAccountDeletion is the resolver for the requestAccountDeletion field.
func (r *mutationResolver) RequestAccountDeletion(ctx context.Context) (string, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return "", err
	}

	// Self only - no additional authorization needed
	return r.core.CreateAccountDeletionToken(ctx, user.Id)
}

// DeleteMyAccount is the resolver for the deleteMyAccount field.
func (r *mutationResolver) DeleteMyAccount(ctx context.Context, input model.DeleteMyAccountInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Validate the confirmation token (XSS protection)
	if err := r.core.ValidateAccountDeletionToken(ctx, input.ConfirmationToken, user.Id); err != nil {
		return false, err
	}

	// Self-deletion
	if err := r.core.DeleteUser(ctx, user.Id, user.Id); err != nil {
		return false, err
	}

	return true, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
