package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"hmans.de/chatto/internal/core"
	"hmans.de/chatto/internal/graph/auth"
	"hmans.de/chatto/internal/graph/model"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, roomID string) (*corev1.Room, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	spaceID, err := r.resolveRoomSpaceID(ctx, roomID)
	if err != nil {
		return nil, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, spaceID, user.Id, roomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	return r.core.GetRoom(ctx, spaceID, roomID)
}

// RoomEvents is the resolver for the roomEvents field.
func (r *queryResolver) RoomEvents(ctx context.Context, roomID string, limit *int32, before *string, after *string) (*model.RoomEventsConnection, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	spaceID, err := r.resolveRoomSpaceID(ctx, roomID)
	if err != nil {
		return nil, err
	}

	// Default limit to 50 if not provided
	var fetchLimit uint32 = 50
	if limit != nil {
		fetchLimit = uint32(*limit)
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, spaceID, user.Id, roomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	var result *core.RoomEventsResult

	if after != nil && *after != "" {
		afterSeq, err := parseRoomEventCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid after cursor: %w", err)
		}
		result, err = r.core.GetRoomEventsAfter(ctx, spaceID, roomID, afterSeq, int(fetchLimit))
		if err != nil {
			return nil, err
		}
	} else {
		var beforeSeq *uint64
		if before != nil && *before != "" {
			seq, err := parseRoomEventCursor(*before)
			if err != nil {
				return nil, fmt.Errorf("invalid before cursor: %w", err)
			}
			beforeSeq = &seq
		}
		result, err = r.core.GetRoomEvents(ctx, spaceID, roomID, int(fetchLimit), beforeSeq)
		if err != nil {
			return nil, err
		}
	}

	return buildRoomEventsConnection(result), nil
}

// RoomEventByEventID is the resolver for the roomEventByEventId field.
// Uses O(1) subject lookup in JetStream — lightweight and fast.
func (r *queryResolver) RoomEventByEventID(ctx context.Context, roomID string, eventID string) (*corev1.Event, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	spaceID, err := r.resolveRoomSpaceID(ctx, roomID)
	if err != nil {
		return nil, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, spaceID, user.Id, roomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	return r.core.GetRoomEventByEventID(ctx, spaceID, roomID, eventID)
}

// ThreadEvents is the resolver for the threadEvents field.
// Fetches the root message and all replies for a specific thread.
func (r *queryResolver) ThreadEvents(ctx context.Context, roomID string, threadRootEventID string) ([]*corev1.Event, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	spaceID, err := r.resolveRoomSpaceID(ctx, roomID)
	if err != nil {
		return nil, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, spaceID, user.Id, roomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	return r.core.GetThreadEvents(ctx, spaceID, roomID, threadRootEventID)
}

// RoomEventsAround is the resolver for the roomEventsAround field.
// Fetches room events centered around a specific event for "jump to message".
func (r *queryResolver) RoomEventsAround(ctx context.Context, roomID string, eventID string, limit *int32) (*model.RoomEventsAroundResult, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	spaceID, err := r.resolveRoomSpaceID(ctx, roomID)
	if err != nil {
		return nil, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, spaceID, user.Id, roomID)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	var fetchLimit int = 50
	if limit != nil {
		fetchLimit = int(*limit)
	}

	result, err := r.core.GetRoomEventsAround(ctx, spaceID, roomID, eventID, fetchLimit)
	if err != nil {
		return nil, err
	}

	events := make([]*corev1.Event, len(result.Events))
	for i, e := range result.Events {
		events[i] = e.Event
	}
	out := &model.RoomEventsAroundResult{
		Events:      events,
		TargetIndex: int32(result.TargetIndex),
		HasOlder:    result.HasOlder,
		HasNewer:    result.HasNewer,
	}
	if len(result.Events) > 0 {
		if start := formatRoomEventCursor(result.Events[0].Sequence); start != "" {
			out.StartCursor = &start
		}
		if end := formatRoomEventCursor(result.Events[len(result.Events)-1].Sequence); end != "" {
			out.EndCursor = &end
		}
	}
	return out, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*corev1.User, error) {
	// Extract authenticated user from context
	user := auth.ForContext(ctx)
	// Returns nil if not authenticated (allowed by schema)
	return user, nil
}

// User is the resolver for the user field.
// Note: User profiles are intentionally public within the instance.
// This is required for displaying message authors, member lists, etc.
// Authentication is not required as user data is non-sensitive.
func (r *queryResolver) User(ctx context.Context, id string) (*corev1.User, error) {
	// No authorization - public user profiles
	return r.core.GetUser(ctx, id)
}

// UserByLogin is the resolver for the userByLogin field.
// Returns the user with the given login name, or null if not found.
// Note: User profiles are intentionally public within the instance.
func (r *queryResolver) UserByLogin(ctx context.Context, login string) (*corev1.User, error) {
	// No authorization - public user profiles
	user, err := r.core.GetUserByLogin(ctx, login)
	if err != nil {
		// Return nil instead of error for "not found" cases
		return nil, nil
	}
	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*corev1.User, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Authorization: instance admin only (checks both RBAC and config-based admin)
	isAdmin, err := r.isInstanceAdmin(ctx, user.Id)
	if err != nil {
		return nil, err
	}
	if !isAdmin {
		return nil, core.ErrPermissionDenied
	}

	return r.core.ListUsers(ctx)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
