package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"hmans.de/chatto/internal/core"
	"hmans.de/chatto/internal/graph/auth"
	"hmans.de/chatto/internal/graph/model"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// Type is the resolver for the type field.
//
// Derived from `IsDMSpace(obj.SpaceId)` — the kind discriminator is the
// room's space membership (DM rooms live in the DM system space), which
// matches the kind segment the storage layer uses in `SERVER_CONFIG` keys
// (`room.channel.{id}` vs `room.dm.{id}`). The Room proto doesn't carry a
// kind field of its own; `SpaceId` is the canonical source.
func (r *roomResolver) Type(ctx context.Context, obj *corev1.Room) (model.RoomType, error) {
	if core.IsDMSpace(obj.SpaceId) {
		return model.RoomTypeDm, nil
	}
	return model.RoomTypeChannel, nil
}

// Members is the resolver for the members field.
func (r *roomResolver) Members(ctx context.Context, obj *corev1.Room) ([]*corev1.User, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, obj.SpaceId, user.Id, obj.Id)
	if err != nil {
		return nil, err
	}
	if !isMember {
		return nil, core.ErrNotRoomMember
	}

	memberships, err := r.core.GetRoomMembersList(ctx, obj.SpaceId, obj.Id)
	if err != nil {
		return nil, err
	}
	users := make([]*corev1.User, 0, len(memberships))
	for _, m := range memberships {
		u, err := r.core.GetUser(ctx, m.UserId)
		if err != nil {
			return nil, err
		}
		if u != nil {
			users = append(users, u)
		}
	}
	return users, nil
}

// HasUnread is the resolver for the hasUnread field.
func (r *roomResolver) HasUnread(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}

	// Authorization: require room membership
	isMember, err := r.core.RoomMembershipExists(ctx, obj.SpaceId, user.Id, obj.Id)
	if err != nil {
		return false, nil // Silently return false if we can't check
	}
	if !isMember {
		return false, nil
	}

	return r.core.HasUnread(ctx, obj.SpaceId, user.Id, obj.Id)
}

// HasMention is the resolver for the hasMention field.
func (r *roomResolver) HasMention(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}

	// Call core directly for mention status
	return r.core.HasMention(ctx, obj.SpaceId, obj.Id, user.Id)
}

// ViewerCanPostMessage is the resolver for the viewerCanPostMessage field.
func (r *roomResolver) ViewerCanPostMessage(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanPostMessage(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanPostInThread is the resolver for the viewerCanPostInThread field.
func (r *roomResolver) ViewerCanPostInThread(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanPostInThread(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanReply is the resolver for the viewerCanReply field.
func (r *roomResolver) ViewerCanReply(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanReply(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanReplyInThread is the resolver for the viewerCanReplyInThread field.
func (r *roomResolver) ViewerCanReplyInThread(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanReplyInThread(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanReact is the resolver for the viewerCanReact field.
func (r *roomResolver) ViewerCanReact(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanReactToMessage(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanEditOwnMessage is the resolver for the viewerCanEditOwnMessage field.
func (r *roomResolver) ViewerCanEditOwnMessage(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanEditOwnMessage(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanEditAnyMessage is the resolver for the viewerCanEditAnyMessage field.
func (r *roomResolver) ViewerCanEditAnyMessage(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanEditAnyMessage(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanDeleteOwnMessage is the resolver for the viewerCanDeleteOwnMessage field.
func (r *roomResolver) ViewerCanDeleteOwnMessage(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanDeleteOwnMessage(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanDeleteAnyMessage is the resolver for the viewerCanDeleteAnyMessage field.
func (r *roomResolver) ViewerCanDeleteAnyMessage(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanDeleteAnyMessage(ctx, user.Id, obj.SpaceId, obj.Id)
}

// ViewerCanJoinRoom is the resolver for the viewerCanJoinRoom field.
func (r *roomResolver) ViewerCanJoinRoom(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanJoinRoom(ctx, user.Id, obj.SpaceId)
}

// ViewerCanEchoMessage is the resolver for the viewerCanEchoMessage field.
func (r *roomResolver) ViewerCanEchoMessage(ctx context.Context, obj *corev1.Room) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanEchoMessage(ctx, user.Id, obj.SpaceId, obj.Id)
}

// Room returns RoomResolver implementation.
func (r *Resolver) Room() RoomResolver { return &roomResolver{r} }

type roomResolver struct{ *Resolver }
