package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"hmans.de/chatto/internal/core"
	"hmans.de/chatto/internal/graph/auth"
	"hmans.de/chatto/internal/graph/model"
	corev1 "hmans.de/chatto/internal/pb/chatto/core/v1"
)

// GrantRoomPermission is the resolver for the grantRoomPermission field.
func (r *mutationResolver) GrantRoomPermission(ctx context.Context, input model.GrantRoomPermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	if err := r.requireRoomManageAuth(ctx, user.Id); err != nil {
		return false, err
	}

	if err := r.core.GrantRoomPermission(ctx, input.RoomID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// DenyRoomPermission is the resolver for the denyRoomPermission field.
func (r *mutationResolver) DenyRoomPermission(ctx context.Context, input model.DenyRoomPermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	if err := r.requireRoomManageAuth(ctx, user.Id); err != nil {
		return false, err
	}

	if err := r.core.DenyRoomPermission(ctx, input.RoomID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// ClearRoomPermission is the resolver for the clearRoomPermission field.
func (r *mutationResolver) ClearRoomPermission(ctx context.Context, input model.ClearRoomPermissionInput) (bool, error) {
	user, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	if err := r.requireRoomManageAuth(ctx, user.Id); err != nil {
		return false, err
	}

	if err := r.core.ClearRoomPermissionState(ctx, input.RoomID, input.Role, core.Permission(input.Permission)); err != nil {
		return false, err
	}
	return true, nil
}

// RoomPermissionOverrides is the resolver for the roomPermissionOverrides field.
func (r *roomResolver) RoomPermissionOverrides(ctx context.Context, obj *corev1.Room) ([]*model.RoleRoomPermissions, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}

	can, err := r.core.CanManageRoles(ctx, user.Id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, core.ErrPermissionDenied
	}

	roles, err := r.core.ListServerRoles(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.RoleRoomPermissions, 0, len(roles))
	for _, role := range roles {
		if role.Name == core.RoleEveryone {
			continue
		}
		grants, denials, err := r.core.GetRoomRolePermissions(ctx, obj.Id, role.Name)
		if err != nil {
			return nil, err
		}
		grantStrs := make([]string, len(grants))
		for i, g := range grants {
			grantStrs[i] = string(g)
		}
		denialStrs := make([]string, len(denials))
		for i, d := range denials {
			denialStrs[i] = string(d)
		}
		result = append(result, &model.RoleRoomPermissions{
			RoleName:          role.Name,
			DisplayName:       role.DisplayName,
			IsSystem:          role.IsSystem,
			Position:          role.Position,
			Permissions:       grantStrs,
			PermissionDenials: denialStrs,
		})
	}

	return result, nil
}

// AvailableRoomPermissions is the resolver for the availableRoomPermissions field.
func (r *roomResolver) AvailableRoomPermissions(ctx context.Context, obj *corev1.Room) ([]string, error) {
	perms := core.PermissionsForScope(core.ScopeRoom)
	result := make([]string, len(perms))
	for i, p := range perms {
		result[i] = string(p.Permission)
	}
	return result, nil
}

// Roles is the resolver for the roles field. Returns the server's role
// catalog — name, display name, position, and permission grants/denials
// per role. Available to any authenticated user.
//
// What's NOT exposed here is the per-user roster ("who has the admin
// role") — see Server.roleUsers and Server.userEffectivePermissions for
// that, both of which are gated. Knowing that "the admin role grants
// user.delete" is operational config; knowing "alice is an admin" is
// the sensitive part.
func (r *serverResolver) Roles(ctx context.Context, obj *model.Server) ([]*core.RoleWithPermissions, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	roles, err := r.core.ListServerRoles(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*core.RoleWithPermissions, len(roles))
	for i := range roles {
		out[i] = &roles[i]
	}
	return out, nil
}

// Role is the resolver for the role field. Available to any
// authenticated user — see Server.roles for the rationale.
func (r *serverResolver) Role(ctx context.Context, obj *model.Server, name string) (*core.RoleWithPermissions, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}

	role, err := r.core.GetServerRole(ctx, name)
	if err != nil {
		return nil, err
	}
	return role, nil
}

// AvailablePermissions is the resolver for the availablePermissions field.
func (r *serverResolver) AvailablePermissions(ctx context.Context, obj *model.Server) ([]string, error) {
	perms := core.PermissionsForScope(core.ScopeServer)
	result := make([]string, len(perms))
	for i, p := range perms {
		result[i] = string(p.Permission)
	}
	return result, nil
}

// ViewerPermissions is the resolver for the viewerPermissions field.
func (r *serverResolver) ViewerPermissions(ctx context.Context, obj *model.Server) ([]string, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return []string{}, nil
	}
	kind := core.KindChannel

	perms, err := r.core.GetUserEffectiveSpacePermissions(ctx, kind, user.Id)
	if err != nil {
		return nil, err
	}

	result := make([]string, len(perms))
	for i, p := range perms {
		result[i] = string(p)
	}
	return result, nil
}

// ViewerCanManageRoles is the resolver for the viewerCanManageRoles field.
func (r *serverResolver) ViewerCanManageRoles(ctx context.Context, obj *model.Server) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanManageRoles(ctx, user.Id)
}

// ViewerCanAssignRoles is the resolver for the viewerCanAssignRoles field.
func (r *serverResolver) ViewerCanAssignRoles(ctx context.Context, obj *model.Server) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	return r.core.CanAssignRoles(ctx, user.Id)
}

// ViewerCanManageUser is the resolver for the viewerCanManageUser field.
//
// IMPORTANT: this is a UI hint, not an authorization gate. It answers
// "does the viewer outrank the target by role hierarchy?" — nothing
// more. Callers (frontend) must understand that hiding a control
// based on this field is fine; granting a capability based on it is
// not. See the schema doc and authorization.md.
func (r *serverResolver) ViewerCanManageUser(ctx context.Context, obj *model.Server, userID string) (bool, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return false, nil
	}
	if user.Id == userID {
		return false, nil
	}
	return r.core.OutranksUser(ctx, user.Id, userID)
}

// RoleUsers is the resolver for the roleUsers field.
//
// Role rosters expose operationally-sensitive information (who's a server
// admin, etc.) and are gated on `role.assign` — the same permission required
// to manage role assignments. Returns nil for unauthorized callers.
func (r *serverResolver) RoleUsers(ctx context.Context, obj *model.Server, roleName string) ([]*corev1.User, error) {
	if err := r.Resolver.requireRoleRosterAccess(ctx); err != nil {
		return nil, err
	}

	userIDs, err := r.core.GetRoleUsers(ctx, roleName)
	if err != nil {
		return nil, fmt.Errorf("failed to get role users: %w", err)
	}

	users := make([]*corev1.User, 0, len(userIDs))
	for _, uID := range userIDs {
		u, err := r.core.GetUser(ctx, uID)
		if err != nil {
			continue
		}
		users = append(users, u)
	}

	return users, nil
}

// UserEffectivePermissions is the resolver for the userEffectivePermissions
// field. Reveals which permissions any given user effectively holds —
// combining role-based grants with user-level overrides. Useful for the
// admin inspector UI, but operationally sensitive (lets a caller enumerate
// other users' privileges). Gated on `role.assign`.
func (r *serverResolver) UserEffectivePermissions(ctx context.Context, obj *model.Server, userID string) ([]string, error) {
	if err := r.Resolver.requireRoleRosterAccess(ctx); err != nil {
		return nil, err
	}
	var allowed []string
	for _, permDef := range core.PermissionsForScope(core.ScopeServer) {
		decision, err := r.core.ResolveUserPermission(ctx, userID, core.KindChannel, "", core.Permission(permDef.Permission))
		if err != nil {
			return nil, err
		}
		if decision == core.DecisionAllow {
			allowed = append(allowed, string(permDef.Permission))
		}
	}
	return allowed, nil
}

// UserEffectiveDenials is the resolver for the userEffectiveDenials field.
// Same gate as UserEffectivePermissions — see that resolver's comment.
func (r *serverResolver) UserEffectiveDenials(ctx context.Context, obj *model.Server, userID string) ([]string, error) {
	if err := r.Resolver.requireRoleRosterAccess(ctx); err != nil {
		return nil, err
	}
	var denied []string
	for _, permDef := range core.PermissionsForScope(core.ScopeServer) {
		decision, err := r.core.ResolveUserPermission(ctx, userID, core.KindChannel, "", core.Permission(permDef.Permission))
		if err != nil {
			return nil, err
		}
		if decision == core.DecisionDeny {
			denied = append(denied, string(permDef.Permission))
		}
	}
	return denied, nil
}
