// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/admin/v1/members.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { User } from "../../api/v1/users_pb.js";
import { PageInfo, PageRequest } from "../../api/v1/pagination_pb.js";

/**
 * User row returned by server-admin member management reads.
 *
 * The embedded user record carries public identity fields; remaining fields are
 * admin/member metadata with visibility controlled by the service.
 *
 * @generated from message chatto.admin.v1.AdminMember
 */
export class AdminMember extends Message<AdminMember> {
  /**
   * Explicit server role assignments. The implicit everyone role is omitted.
   *
   * @generated from field: repeated string roles = 5;
   */
  roles: string[] = [];

  /**
   * Account creation time, when known.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * Whether the caller may see that the user has a verified email and one exists.
   *
   * @generated from field: bool has_verified_email = 8;
   */
  hasVerifiedEmail = false;

  /**
   * Verified email addresses visible to the caller.
   *
   * @generated from field: repeated string verified_emails = 9;
   */
  verifiedEmails: string[] = [];

  /**
   * Whether the caller may delete this account.
   *
   * @generated from field: bool viewer_can_delete_account = 10;
   */
  viewerCanDeleteAccount = false;

  /**
   * Last self-service username change, when visible and known.
   *
   * @generated from field: google.protobuf.Timestamp last_login_change = 11;
   */
  lastLoginChange?: Timestamp;

  /**
   * Public identity fields for this user.
   *
   * @generated from field: chatto.api.v1.User user = 12;
   */
  user?: User;

  constructor(data?: PartialMessage<AdminMember>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminMember";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 5, name: "roles", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 8, name: "has_verified_email", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "verified_emails", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "viewer_can_delete_account", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "last_login_change", kind: "message", T: Timestamp },
    { no: 12, name: "user", kind: "message", T: User },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminMember {
    return new AdminMember().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminMember {
    return new AdminMember().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminMember {
    return new AdminMember().fromJsonString(jsonString, options);
  }

  static equals(a: AdminMember | PlainMessage<AdminMember> | undefined, b: AdminMember | PlainMessage<AdminMember> | undefined): boolean {
    return proto3.util.equals(AdminMember, a, b);
  }
}

/**
 * Role reference used by member list filters and badges.
 *
 * @generated from message chatto.admin.v1.AdminRoleReference
 */
export class AdminRoleReference extends Message<AdminRoleReference> {
  /**
   * Stable role name.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Display name shown in admin UI.
   *
   * @generated from field: string display_name = 2;
   */
  displayName = "";

  constructor(data?: PartialMessage<AdminRoleReference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminRoleReference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminRoleReference {
    return new AdminRoleReference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminRoleReference {
    return new AdminRoleReference().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminRoleReference {
    return new AdminRoleReference().fromJsonString(jsonString, options);
  }

  static equals(a: AdminRoleReference | PlainMessage<AdminRoleReference> | undefined, b: AdminRoleReference | PlainMessage<AdminRoleReference> | undefined): boolean {
    return proto3.util.equals(AdminRoleReference, a, b);
  }
}

/**
 * Server role details used by the member detail role-assignment UI.
 *
 * @generated from message chatto.admin.v1.AdminMemberRole
 */
export class AdminMemberRole extends Message<AdminMemberRole> {
  /**
   * Stable role name.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Display name shown in admin UI.
   *
   * @generated from field: string display_name = 2;
   */
  displayName = "";

  /**
   * Display/order position.
   *
   * @generated from field: int32 position = 3;
   */
  position = 0;

  /**
   * Server permissions granted by this role.
   *
   * @generated from field: repeated string permissions = 4;
   */
  permissions: string[] = [];

  /**
   * Server permissions denied by this role.
   *
   * @generated from field: repeated string permission_denials = 5;
   */
  permissionDenials: string[] = [];

  constructor(data?: PartialMessage<AdminMemberRole>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminMemberRole";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "position", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "permissions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "permission_denials", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminMemberRole {
    return new AdminMemberRole().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminMemberRole {
    return new AdminMemberRole().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminMemberRole {
    return new AdminMemberRole().fromJsonString(jsonString, options);
  }

  static equals(a: AdminMemberRole | PlainMessage<AdminMemberRole> | undefined, b: AdminMemberRole | PlainMessage<AdminMemberRole> | undefined): boolean {
    return proto3.util.equals(AdminMemberRole, a, b);
  }
}

/**
 * Request server-admin member rows.
 *
 * @generated from message chatto.admin.v1.ListMembersRequest
 */
export class ListMembersRequest extends Message<ListMembersRequest> {
  /**
   * Case-insensitive login/display-name search term. Empty disables search.
   *
   * @generated from field: string search = 1;
   */
  search = "";

  /**
   * Page request. Defaults to 20 results when absent or limit is zero.
   *
   * @generated from field: chatto.api.v1.PageRequest page = 4;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListMembersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListMembersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "search", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMembersRequest {
    return new ListMembersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListMembersRequest | PlainMessage<ListMembersRequest> | undefined, b: ListMembersRequest | PlainMessage<ListMembersRequest> | undefined): boolean {
    return proto3.util.equals(ListMembersRequest, a, b);
  }
}

/**
 * Server-admin member rows plus role summaries.
 *
 * @generated from message chatto.admin.v1.ListMembersResponse
 */
export class ListMembersResponse extends Message<ListMembersResponse> {
  /**
   * Matching users.
   *
   * @generated from field: repeated chatto.admin.v1.AdminMember users = 1;
   */
  users: AdminMember[] = [];

  /**
   * Server roles for display-name lookup.
   *
   * @generated from field: repeated chatto.admin.v1.AdminRoleReference roles = 2;
   */
  roles: AdminRoleReference[] = [];

  /**
   * Page metadata.
   *
   * @generated from field: chatto.api.v1.PageInfo page = 5;
   */
  page?: PageInfo;

  constructor(data?: PartialMessage<ListMembersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListMembersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: AdminMember, repeated: true },
    { no: 2, name: "roles", kind: "message", T: AdminRoleReference, repeated: true },
    { no: 5, name: "page", kind: "message", T: PageInfo },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMembersResponse {
    return new ListMembersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListMembersResponse | PlainMessage<ListMembersResponse> | undefined, b: ListMembersResponse | PlainMessage<ListMembersResponse> | undefined): boolean {
    return proto3.util.equals(ListMembersResponse, a, b);
  }
}

/**
 * Request one server-admin member detail record.
 *
 * @generated from message chatto.admin.v1.GetMemberRequest
 */
export class GetMemberRequest extends Message<GetMemberRequest> {
  /**
   * Target user ID.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<GetMemberRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetMemberRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMemberRequest {
    return new GetMemberRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMemberRequest {
    return new GetMemberRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMemberRequest {
    return new GetMemberRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMemberRequest | PlainMessage<GetMemberRequest> | undefined, b: GetMemberRequest | PlainMessage<GetMemberRequest> | undefined): boolean {
    return proto3.util.equals(GetMemberRequest, a, b);
  }
}

/**
 * Server-admin member detail payload.
 *
 * @generated from message chatto.admin.v1.GetMemberResponse
 */
export class GetMemberResponse extends Message<GetMemberResponse> {
  /**
   * Member record.
   *
   * @generated from field: chatto.admin.v1.AdminMember member = 1;
   */
  member?: AdminMember;

  /**
   * Server roles for assignment UI.
   *
   * @generated from field: repeated chatto.admin.v1.AdminMemberRole roles = 2;
   */
  roles: AdminMemberRole[] = [];

  /**
   * Server permissions available for per-user overrides.
   *
   * @generated from field: repeated string available_permissions = 3;
   */
  availablePermissions: string[] = [];

  /**
   * Whether the caller may assign/revoke roles.
   *
   * @generated from field: bool viewer_can_assign_roles = 4;
   */
  viewerCanAssignRoles = false;

  /**
   * Whether the caller may edit role definitions.
   *
   * @generated from field: bool viewer_can_manage_roles = 5;
   */
  viewerCanManageRoles = false;

  /**
   * Whether the caller may edit direct user permissions.
   *
   * @generated from field: bool viewer_can_manage_user_permissions = 6;
   */
  viewerCanManageUserPermissions = false;

  constructor(data?: PartialMessage<GetMemberResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetMemberResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "member", kind: "message", T: AdminMember },
    { no: 2, name: "roles", kind: "message", T: AdminMemberRole, repeated: true },
    { no: 3, name: "available_permissions", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "viewer_can_assign_roles", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "viewer_can_manage_roles", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "viewer_can_manage_user_permissions", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMemberResponse {
    return new GetMemberResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMemberResponse {
    return new GetMemberResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMemberResponse {
    return new GetMemberResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetMemberResponse | PlainMessage<GetMemberResponse> | undefined, b: GetMemberResponse | PlainMessage<GetMemberResponse> | undefined): boolean {
    return proto3.util.equals(GetMemberResponse, a, b);
  }
}

/**
 * Request to assign a server role to a user.
 *
 * @generated from message chatto.admin.v1.AssignRoleRequest
 */
export class AssignRoleRequest extends Message<AssignRoleRequest> {
  /**
   * Target user ID.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * Role name to assign.
   *
   * @generated from field: string role_name = 2;
   */
  roleName = "";

  constructor(data?: PartialMessage<AssignRoleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AssignRoleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssignRoleRequest {
    return new AssignRoleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssignRoleRequest {
    return new AssignRoleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssignRoleRequest {
    return new AssignRoleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AssignRoleRequest | PlainMessage<AssignRoleRequest> | undefined, b: AssignRoleRequest | PlainMessage<AssignRoleRequest> | undefined): boolean {
    return proto3.util.equals(AssignRoleRequest, a, b);
  }
}

/**
 * Result of assigning a server role.
 *
 * @generated from message chatto.admin.v1.AssignRoleResponse
 */
export class AssignRoleResponse extends Message<AssignRoleResponse> {
  /**
   * True when the request completed.
   *
   * @generated from field: bool assigned = 1;
   */
  assigned = false;

  constructor(data?: PartialMessage<AssignRoleResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AssignRoleResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "assigned", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AssignRoleResponse {
    return new AssignRoleResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AssignRoleResponse {
    return new AssignRoleResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AssignRoleResponse {
    return new AssignRoleResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AssignRoleResponse | PlainMessage<AssignRoleResponse> | undefined, b: AssignRoleResponse | PlainMessage<AssignRoleResponse> | undefined): boolean {
    return proto3.util.equals(AssignRoleResponse, a, b);
  }
}

/**
 * Request to revoke a server role from a user.
 *
 * @generated from message chatto.admin.v1.RevokeRoleRequest
 */
export class RevokeRoleRequest extends Message<RevokeRoleRequest> {
  /**
   * Target user ID.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * Role name to revoke.
   *
   * @generated from field: string role_name = 2;
   */
  roleName = "";

  constructor(data?: PartialMessage<RevokeRoleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.RevokeRoleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeRoleRequest {
    return new RevokeRoleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeRoleRequest {
    return new RevokeRoleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeRoleRequest {
    return new RevokeRoleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeRoleRequest | PlainMessage<RevokeRoleRequest> | undefined, b: RevokeRoleRequest | PlainMessage<RevokeRoleRequest> | undefined): boolean {
    return proto3.util.equals(RevokeRoleRequest, a, b);
  }
}

/**
 * Result of revoking a server role.
 *
 * @generated from message chatto.admin.v1.RevokeRoleResponse
 */
export class RevokeRoleResponse extends Message<RevokeRoleResponse> {
  /**
   * True when the request completed.
   *
   * @generated from field: bool revoked = 1;
   */
  revoked = false;

  constructor(data?: PartialMessage<RevokeRoleResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.RevokeRoleResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "revoked", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeRoleResponse {
    return new RevokeRoleResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeRoleResponse {
    return new RevokeRoleResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeRoleResponse {
    return new RevokeRoleResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeRoleResponse | PlainMessage<RevokeRoleResponse> | undefined, b: RevokeRoleResponse | PlainMessage<RevokeRoleResponse> | undefined): boolean {
    return proto3.util.equals(RevokeRoleResponse, a, b);
  }
}

/**
 * Request to update a user's identity as a server-admin action.
 *
 * @generated from message chatto.admin.v1.UpdateUserRequest
 */
export class UpdateUserRequest extends Message<UpdateUserRequest> {
  /**
   * Target user ID.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * New display name, when changing it.
   *
   * @generated from field: optional string display_name = 2;
   */
  displayName?: string;

  /**
   * New login identifier, when changing it.
   *
   * @generated from field: optional string login = 3;
   */
  login?: string;

  constructor(data?: PartialMessage<UpdateUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "login", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateUserRequest | PlainMessage<UpdateUserRequest> | undefined, b: UpdateUserRequest | PlainMessage<UpdateUserRequest> | undefined): boolean {
    return proto3.util.equals(UpdateUserRequest, a, b);
  }
}

/**
 * Result of an admin user update.
 *
 * @generated from message chatto.admin.v1.UpdateUserResponse
 */
export class UpdateUserResponse extends Message<UpdateUserResponse> {
  /**
   * Updated user profile.
   *
   * @generated from field: chatto.api.v1.User user = 1;
   */
  user?: User;

  constructor(data?: PartialMessage<UpdateUserResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateUserResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUserResponse {
    return new UpdateUserResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUserResponse {
    return new UpdateUserResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUserResponse {
    return new UpdateUserResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateUserResponse | PlainMessage<UpdateUserResponse> | undefined, b: UpdateUserResponse | PlainMessage<UpdateUserResponse> | undefined): boolean {
    return proto3.util.equals(UpdateUserResponse, a, b);
  }
}

/**
 * Request to clear a user's self-service username-change cooldown.
 *
 * @generated from message chatto.admin.v1.ClearUsernameCooldownRequest
 */
export class ClearUsernameCooldownRequest extends Message<ClearUsernameCooldownRequest> {
  /**
   * Target user ID.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<ClearUsernameCooldownRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ClearUsernameCooldownRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClearUsernameCooldownRequest {
    return new ClearUsernameCooldownRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClearUsernameCooldownRequest {
    return new ClearUsernameCooldownRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClearUsernameCooldownRequest {
    return new ClearUsernameCooldownRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClearUsernameCooldownRequest | PlainMessage<ClearUsernameCooldownRequest> | undefined, b: ClearUsernameCooldownRequest | PlainMessage<ClearUsernameCooldownRequest> | undefined): boolean {
    return proto3.util.equals(ClearUsernameCooldownRequest, a, b);
  }
}

/**
 * Result of clearing a user's username-change cooldown.
 *
 * @generated from message chatto.admin.v1.ClearUsernameCooldownResponse
 */
export class ClearUsernameCooldownResponse extends Message<ClearUsernameCooldownResponse> {
  /**
   * True when the request completed.
   *
   * @generated from field: bool cleared = 1;
   */
  cleared = false;

  constructor(data?: PartialMessage<ClearUsernameCooldownResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ClearUsernameCooldownResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cleared", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClearUsernameCooldownResponse {
    return new ClearUsernameCooldownResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClearUsernameCooldownResponse {
    return new ClearUsernameCooldownResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClearUsernameCooldownResponse {
    return new ClearUsernameCooldownResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClearUsernameCooldownResponse | PlainMessage<ClearUsernameCooldownResponse> | undefined, b: ClearUsernameCooldownResponse | PlainMessage<ClearUsernameCooldownResponse> | undefined): boolean {
    return proto3.util.equals(ClearUsernameCooldownResponse, a, b);
  }
}

