// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/server.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Describes one login provider exposed by the server discovery endpoint.
 *
 * Clients can render these providers before a user has authenticated.
 *
 * @generated from message chatto.api.v1.AuthProvider
 */
export class AuthProvider extends Message<AuthProvider> {
  /**
   * Stable provider identifier used by clients when starting login.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Provider category, such as "password" or "oidc". Clients should treat
   * unknown provider types as unsupported.
   *
   * @generated from field: string type = 2;
   */
  type = "";

  /**
   * Human-readable provider label for login UI.
   *
   * @generated from field: string label = 3;
   */
  label = "";

  /**
   * URL that starts login for this provider.
   *
   * @generated from field: string login_url = 4;
   */
  loginUrl = "";

  constructor(data?: PartialMessage<AuthProvider>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.AuthProvider";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "login_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuthProvider {
    return new AuthProvider().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuthProvider {
    return new AuthProvider().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuthProvider {
    return new AuthProvider().fromJsonString(jsonString, options);
  }

  static equals(a: AuthProvider | PlainMessage<AuthProvider> | undefined, b: AuthProvider | PlainMessage<AuthProvider> | undefined): boolean {
    return proto3.util.equals(AuthProvider, a, b);
  }
}

/**
 * Public server profile, identity, and branding fields.
 *
 * @generated from message chatto.api.v1.ServerPublicProfile
 */
export class ServerPublicProfile extends Message<ServerPublicProfile> {
  /**
   * Display name of the Chatto server.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Server software version.
   *
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * Optional server logo URL.
   *
   * @generated from field: optional string logo_url = 3;
   */
  logoUrl?: string;

  /**
   * Optional server banner URL.
   *
   * @generated from field: optional string banner_url = 4;
   */
  bannerUrl?: string;

  /**
   * Optional welcome message.
   *
   * @generated from field: optional string welcome_message = 5;
   */
  welcomeMessage?: string;

  /**
   * Optional server description.
   *
   * @generated from field: optional string description = 6;
   */
  description?: string;

  constructor(data?: PartialMessage<ServerPublicProfile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ServerPublicProfile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "logo_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "banner_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "welcome_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerPublicProfile {
    return new ServerPublicProfile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerPublicProfile {
    return new ServerPublicProfile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerPublicProfile {
    return new ServerPublicProfile().fromJsonString(jsonString, options);
  }

  static equals(a: ServerPublicProfile | PlainMessage<ServerPublicProfile> | undefined, b: ServerPublicProfile | PlainMessage<ServerPublicProfile> | undefined): boolean {
    return proto3.util.equals(ServerPublicProfile, a, b);
  }
}

/**
 * Login and registration options exposed before authentication.
 *
 * @generated from message chatto.api.v1.ServerLogin
 */
export class ServerLogin extends Message<ServerLogin> {
  /**
   * Whether users can create accounts through the public UI.
   *
   * @generated from field: bool direct_registration_enabled = 1;
   */
  directRegistrationEnabled = false;

  /**
   * Configured login providers.
   *
   * @generated from field: repeated chatto.api.v1.AuthProvider providers = 2;
   */
  providers: AuthProvider[] = [];

  /**
   * URL for the legacy authorization flow, when enabled.
   *
   * @generated from field: string authorize_url = 3;
   */
  authorizeUrl = "";

  constructor(data?: PartialMessage<ServerLogin>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ServerLogin";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "direct_registration_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "providers", kind: "message", T: AuthProvider, repeated: true },
    { no: 3, name: "authorize_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerLogin {
    return new ServerLogin().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerLogin {
    return new ServerLogin().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerLogin {
    return new ServerLogin().fromJsonString(jsonString, options);
  }

  static equals(a: ServerLogin | PlainMessage<ServerLogin> | undefined, b: ServerLogin | PlainMessage<ServerLogin> | undefined): boolean {
    return proto3.util.equals(ServerLogin, a, b);
  }
}
