// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/encryption_keys.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserKeyEncryptionKey is the built-in KMS storage record for opaque kek.*
// refs in ENCRYPTION_KEYS. It is a local implementation detail; external KMS
// backends may not store key-encryption-key material in Chatto at all.
type UserKeyEncryptionKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserKeyEncryptionKey) Reset() {
	*x = UserKeyEncryptionKey{}
	mi := &file_chatto_core_v1_encryption_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKeyEncryptionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKeyEncryptionKey) ProtoMessage() {}

func (x *UserKeyEncryptionKey) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_encryption_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKeyEncryptionKey.ProtoReflect.Descriptor instead.
func (*UserKeyEncryptionKey) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_encryption_keys_proto_rawDescGZIP(), []int{0}
}

func (x *UserKeyEncryptionKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *UserKeyEncryptionKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// UserDataEncryptionKey is the wrapped data-encryption-key record stored in
// RUNTIME_STATE under UserDEKGeneratedEvent.content_key_ref. It is deliberately
// outside EVT so crypto-shredding can destroy key material without mutating
// event history, but it remains part of normal data backups because the record
// is unusable without the KMS KEK referenced by wrapping_key_ref.
type UserDataEncryptionKey struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EncryptedContentKey []byte                 `protobuf:"bytes,1,opt,name=encrypted_content_key,json=encryptedContentKey,proto3" json:"encrypted_content_key,omitempty"`
	ContentKeyNonce     []byte                 `protobuf:"bytes,2,opt,name=content_key_nonce,json=contentKeyNonce,proto3" json:"content_key_nonce,omitempty"`
	WrappingAlgorithm   string                 `protobuf:"bytes,3,opt,name=wrapping_algorithm,json=wrappingAlgorithm,proto3" json:"wrapping_algorithm,omitempty"`
	WrappingMetadata    []byte                 `protobuf:"bytes,4,opt,name=wrapping_metadata,json=wrappingMetadata,proto3" json:"wrapping_metadata,omitempty"`
	WrappingKeyRef      string                 `protobuf:"bytes,5,opt,name=wrapping_key_ref,json=wrappingKeyRef,proto3" json:"wrapping_key_ref,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserDataEncryptionKey) Reset() {
	*x = UserDataEncryptionKey{}
	mi := &file_chatto_core_v1_encryption_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataEncryptionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataEncryptionKey) ProtoMessage() {}

func (x *UserDataEncryptionKey) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_encryption_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataEncryptionKey.ProtoReflect.Descriptor instead.
func (*UserDataEncryptionKey) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_encryption_keys_proto_rawDescGZIP(), []int{1}
}

func (x *UserDataEncryptionKey) GetEncryptedContentKey() []byte {
	if x != nil {
		return x.EncryptedContentKey
	}
	return nil
}

func (x *UserDataEncryptionKey) GetContentKeyNonce() []byte {
	if x != nil {
		return x.ContentKeyNonce
	}
	return nil
}

func (x *UserDataEncryptionKey) GetWrappingAlgorithm() string {
	if x != nil {
		return x.WrappingAlgorithm
	}
	return ""
}

func (x *UserDataEncryptionKey) GetWrappingMetadata() []byte {
	if x != nil {
		return x.WrappingMetadata
	}
	return nil
}

func (x *UserDataEncryptionKey) GetWrappingKeyRef() string {
	if x != nil {
		return x.WrappingKeyRef
	}
	return ""
}

var File_chatto_core_v1_encryption_keys_proto protoreflect.FileDescriptor

const file_chatto_core_v1_encryption_keys_proto_rawDesc = "" +
	"\n" +
	"$chatto/core/v1/encryption_keys.proto\x12\x0echatto.core.v1\"F\n" +
	"\x14UserKeyEncryptionKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\"\xfd\x01\n" +
	"\x15UserDataEncryptionKey\x122\n" +
	"\x15encrypted_content_key\x18\x01 \x01(\fR\x13encryptedContentKey\x12*\n" +
	"\x11content_key_nonce\x18\x02 \x01(\fR\x0fcontentKeyNonce\x12-\n" +
	"\x12wrapping_algorithm\x18\x03 \x01(\tR\x11wrappingAlgorithm\x12+\n" +
	"\x11wrapping_metadata\x18\x04 \x01(\fR\x10wrappingMetadata\x12(\n" +
	"\x10wrapping_key_ref\x18\x05 \x01(\tR\x0ewrappingKeyRefB\xb6\x01\n" +
	"\x12com.chatto.core.v1B\x13EncryptionKeysProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_encryption_keys_proto_rawDescOnce sync.Once
	file_chatto_core_v1_encryption_keys_proto_rawDescData []byte
)

func file_chatto_core_v1_encryption_keys_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_encryption_keys_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_encryption_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_encryption_keys_proto_rawDesc), len(file_chatto_core_v1_encryption_keys_proto_rawDesc)))
	})
	return file_chatto_core_v1_encryption_keys_proto_rawDescData
}

var file_chatto_core_v1_encryption_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_core_v1_encryption_keys_proto_goTypes = []any{
	(*UserKeyEncryptionKey)(nil),  // 0: chatto.core.v1.UserKeyEncryptionKey
	(*UserDataEncryptionKey)(nil), // 1: chatto.core.v1.UserDataEncryptionKey
}
var file_chatto_core_v1_encryption_keys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_encryption_keys_proto_init() }
func file_chatto_core_v1_encryption_keys_proto_init() {
	if File_chatto_core_v1_encryption_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_encryption_keys_proto_rawDesc), len(file_chatto_core_v1_encryption_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_encryption_keys_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_encryption_keys_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_encryption_keys_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_encryption_keys_proto = out.File
	file_chatto_core_v1_encryption_keys_proto_goTypes = nil
	file_chatto_core_v1_encryption_keys_proto_depIdxs = nil
}
