// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/server_event.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SpaceEvent is the wrapper for all space-scoped events.
//
// Events are either:
// - Stored in JetStream streams — persisted events
// - Published directly to NATS Core for real-time updates — live events
//
// Persisted event message definitions are in this file. Changing their field numbers
// or structure affects stored data and requires careful migration.
//
// Live-only (transient) event message definitions are in live_event.proto. Those can
// be changed freely since they are never persisted.
//
// Server-scoped events use a separate ServerEvent wrapper (in live_event.proto).
//
// Authorization is determined by NATS subject, not the wrapper type:
// - Space events: space.{spaceId}.> (JetStream) or live.space.{spaceId}.> (NATS Core)
type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Universal event identifier (NanoID) for forward-compatibility with non-NATS systems
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When this event was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ID of the user who triggered this event
	ActorId string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// The concrete event payload
	//
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_RoomCreated
	//	*ServerEvent_RoomUpdated
	//	*ServerEvent_RoomDeleted
	//	*ServerEvent_RoomArchived
	//	*ServerEvent_RoomUnarchived
	//	*ServerEvent_UserJoinedRoom
	//	*ServerEvent_UserLeftRoom
	//	*ServerEvent_SpaceMemberDeleted
	//	*ServerEvent_MessagePosted
	//	*ServerEvent_MessageUpdated
	//	*ServerEvent_MessageDeleted
	//	*ServerEvent_ReactionAdded
	//	*ServerEvent_ReactionRemoved
	//	*ServerEvent_UserTyping
	//	*ServerEvent_VideoProcessingCompleted
	//	*ServerEvent_PresenceChanged
	//	*ServerEvent_CallParticipantJoined
	//	*ServerEvent_CallParticipantLeft
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{0}
}

func (x *ServerEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServerEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetRoomCreated() *RoomCreatedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_RoomCreated); ok {
			return x.RoomCreated
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomUpdated() *RoomUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_RoomUpdated); ok {
			return x.RoomUpdated
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomDeleted() *RoomDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_RoomDeleted); ok {
			return x.RoomDeleted
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomArchived() *RoomArchivedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_RoomArchived); ok {
			return x.RoomArchived
		}
	}
	return nil
}

func (x *ServerEvent) GetRoomUnarchived() *RoomUnarchivedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_RoomUnarchived); ok {
			return x.RoomUnarchived
		}
	}
	return nil
}

func (x *ServerEvent) GetUserJoinedRoom() *UserJoinedRoomEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_UserJoinedRoom); ok {
			return x.UserJoinedRoom
		}
	}
	return nil
}

func (x *ServerEvent) GetUserLeftRoom() *UserLeftRoomEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_UserLeftRoom); ok {
			return x.UserLeftRoom
		}
	}
	return nil
}

func (x *ServerEvent) GetSpaceMemberDeleted() *SpaceMemberDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_SpaceMemberDeleted); ok {
			return x.SpaceMemberDeleted
		}
	}
	return nil
}

func (x *ServerEvent) GetMessagePosted() *MessagePostedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_MessagePosted); ok {
			return x.MessagePosted
		}
	}
	return nil
}

func (x *ServerEvent) GetMessageUpdated() *MessageUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_MessageUpdated); ok {
			return x.MessageUpdated
		}
	}
	return nil
}

func (x *ServerEvent) GetMessageDeleted() *MessageDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_MessageDeleted); ok {
			return x.MessageDeleted
		}
	}
	return nil
}

func (x *ServerEvent) GetReactionAdded() *ReactionAddedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ReactionAdded); ok {
			return x.ReactionAdded
		}
	}
	return nil
}

func (x *ServerEvent) GetReactionRemoved() *ReactionRemovedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ReactionRemoved); ok {
			return x.ReactionRemoved
		}
	}
	return nil
}

func (x *ServerEvent) GetUserTyping() *UserTypingEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_UserTyping); ok {
			return x.UserTyping
		}
	}
	return nil
}

func (x *ServerEvent) GetVideoProcessingCompleted() *VideoProcessingCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_VideoProcessingCompleted); ok {
			return x.VideoProcessingCompleted
		}
	}
	return nil
}

func (x *ServerEvent) GetPresenceChanged() *PresenceChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_PresenceChanged); ok {
			return x.PresenceChanged
		}
	}
	return nil
}

func (x *ServerEvent) GetCallParticipantJoined() *CallParticipantJoinedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_CallParticipantJoined); ok {
			return x.CallParticipantJoined
		}
	}
	return nil
}

func (x *ServerEvent) GetCallParticipantLeft() *CallParticipantLeftEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_CallParticipantLeft); ok {
			return x.CallParticipantLeft
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_RoomCreated struct {
	// ----- Room lifecycle (300-309) -----
	RoomCreated *RoomCreatedEvent `protobuf:"bytes,300,opt,name=room_created,json=roomCreated,proto3,oneof"`
}

type ServerEvent_RoomUpdated struct {
	RoomUpdated *RoomUpdatedEvent `protobuf:"bytes,301,opt,name=room_updated,json=roomUpdated,proto3,oneof"`
}

type ServerEvent_RoomDeleted struct {
	RoomDeleted *RoomDeletedEvent `protobuf:"bytes,302,opt,name=room_deleted,json=roomDeleted,proto3,oneof"`
}

type ServerEvent_RoomArchived struct {
	RoomArchived *RoomArchivedEvent `protobuf:"bytes,303,opt,name=room_archived,json=roomArchived,proto3,oneof"`
}

type ServerEvent_RoomUnarchived struct {
	RoomUnarchived *RoomUnarchivedEvent `protobuf:"bytes,304,opt,name=room_unarchived,json=roomUnarchived,proto3,oneof"`
}

type ServerEvent_UserJoinedRoom struct {
	// ----- Room membership (310-329) -----
	UserJoinedRoom *UserJoinedRoomEvent `protobuf:"bytes,310,opt,name=user_joined_room,json=userJoinedRoom,proto3,oneof"`
}

type ServerEvent_UserLeftRoom struct {
	UserLeftRoom *UserLeftRoomEvent `protobuf:"bytes,311,opt,name=user_left_room,json=userLeftRoom,proto3,oneof"`
}

type ServerEvent_SpaceMemberDeleted struct {
	SpaceMemberDeleted *SpaceMemberDeletedEvent `protobuf:"bytes,320,opt,name=space_member_deleted,json=spaceMemberDeleted,proto3,oneof"`
}

type ServerEvent_MessagePosted struct {
	// ----- Messages (400-409) -----
	MessagePosted *MessagePostedEvent `protobuf:"bytes,400,opt,name=message_posted,json=messagePosted,proto3,oneof"` // Field 403 was ThreadReplyEchoEvent, now folded into MessagePostedEvent
}

type ServerEvent_MessageUpdated struct {
	// ----- Message mutations (401-402) -----
	MessageUpdated *MessageUpdatedEvent `protobuf:"bytes,401,opt,name=message_updated,json=messageUpdated,proto3,oneof"`
}

type ServerEvent_MessageDeleted struct {
	MessageDeleted *MessageDeletedEvent `protobuf:"bytes,402,opt,name=message_deleted,json=messageDeleted,proto3,oneof"`
}

type ServerEvent_ReactionAdded struct {
	// ----- Reactions (500-509) — KV is source of truth -----
	ReactionAdded *ReactionAddedEvent `protobuf:"bytes,500,opt,name=reaction_added,json=reactionAdded,proto3,oneof"`
}

type ServerEvent_ReactionRemoved struct {
	ReactionRemoved *ReactionRemovedEvent `protobuf:"bytes,501,opt,name=reaction_removed,json=reactionRemoved,proto3,oneof"`
}

type ServerEvent_UserTyping struct {
	// ----- Typing indicators (510-519) -----
	UserTyping *UserTypingEvent `protobuf:"bytes,510,opt,name=user_typing,json=userTyping,proto3,oneof"`
}

type ServerEvent_VideoProcessingCompleted struct {
	// ----- Video processing (520-529) -----
	VideoProcessingCompleted *VideoProcessingCompletedEvent `protobuf:"bytes,520,opt,name=video_processing_completed,json=videoProcessingCompleted,proto3,oneof"`
}

type ServerEvent_PresenceChanged struct {
	// ----- Presence (600-609) -----
	PresenceChanged *PresenceChangedEvent `protobuf:"bytes,600,opt,name=presence_changed,json=presenceChanged,proto3,oneof"`
}

type ServerEvent_CallParticipantJoined struct {
	// ----- Voice calls (710-719) -----
	CallParticipantJoined *CallParticipantJoinedEvent `protobuf:"bytes,710,opt,name=call_participant_joined,json=callParticipantJoined,proto3,oneof"`
}

type ServerEvent_CallParticipantLeft struct {
	CallParticipantLeft *CallParticipantLeftEvent `protobuf:"bytes,711,opt,name=call_participant_left,json=callParticipantLeft,proto3,oneof"`
}

func (*ServerEvent_RoomCreated) isServerEvent_Event() {}

func (*ServerEvent_RoomUpdated) isServerEvent_Event() {}

func (*ServerEvent_RoomDeleted) isServerEvent_Event() {}

func (*ServerEvent_RoomArchived) isServerEvent_Event() {}

func (*ServerEvent_RoomUnarchived) isServerEvent_Event() {}

func (*ServerEvent_UserJoinedRoom) isServerEvent_Event() {}

func (*ServerEvent_UserLeftRoom) isServerEvent_Event() {}

func (*ServerEvent_SpaceMemberDeleted) isServerEvent_Event() {}

func (*ServerEvent_MessagePosted) isServerEvent_Event() {}

func (*ServerEvent_MessageUpdated) isServerEvent_Event() {}

func (*ServerEvent_MessageDeleted) isServerEvent_Event() {}

func (*ServerEvent_ReactionAdded) isServerEvent_Event() {}

func (*ServerEvent_ReactionRemoved) isServerEvent_Event() {}

func (*ServerEvent_UserTyping) isServerEvent_Event() {}

func (*ServerEvent_VideoProcessingCompleted) isServerEvent_Event() {}

func (*ServerEvent_PresenceChanged) isServerEvent_Event() {}

func (*ServerEvent_CallParticipantJoined) isServerEvent_Event() {}

func (*ServerEvent_CallParticipantLeft) isServerEvent_Event() {}

type RoomCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreatedEvent) Reset() {
	*x = RoomCreatedEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreatedEvent) ProtoMessage() {}

func (x *RoomCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreatedEvent.ProtoReflect.Descriptor instead.
func (*RoomCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{1}
}

func (x *RoomCreatedEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *RoomCreatedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomCreatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RoomUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomUpdatedEvent) Reset() {
	*x = RoomUpdatedEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUpdatedEvent) ProtoMessage() {}

func (x *RoomUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUpdatedEvent.ProtoReflect.Descriptor instead.
func (*RoomUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{2}
}

func (x *RoomUpdatedEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *RoomUpdatedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomUpdatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomUpdatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RoomDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDeletedEvent) Reset() {
	*x = RoomDeletedEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDeletedEvent) ProtoMessage() {}

func (x *RoomDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDeletedEvent.ProtoReflect.Descriptor instead.
func (*RoomDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{3}
}

func (x *RoomDeletedEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *RoomDeletedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// RoomArchivedEvent is published when a room is archived.
// Archived rooms are hidden from sidebars and Browse Rooms.
type RoomArchivedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomArchivedEvent) Reset() {
	*x = RoomArchivedEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomArchivedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomArchivedEvent) ProtoMessage() {}

func (x *RoomArchivedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomArchivedEvent.ProtoReflect.Descriptor instead.
func (*RoomArchivedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{4}
}

func (x *RoomArchivedEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *RoomArchivedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// RoomUnarchivedEvent is published when a room is unarchived.
// The room becomes visible again in sidebars and Browse Rooms.
type RoomUnarchivedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomUnarchivedEvent) Reset() {
	*x = RoomUnarchivedEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomUnarchivedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUnarchivedEvent) ProtoMessage() {}

func (x *RoomUnarchivedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUnarchivedEvent.ProtoReflect.Descriptor instead.
func (*RoomUnarchivedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{5}
}

func (x *RoomUnarchivedEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *RoomUnarchivedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type UserJoinedRoomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserJoinedRoomEvent) Reset() {
	*x = UserJoinedRoomEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJoinedRoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinedRoomEvent) ProtoMessage() {}

func (x *UserJoinedRoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinedRoomEvent.ProtoReflect.Descriptor instead.
func (*UserJoinedRoomEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{6}
}

func (x *UserJoinedRoomEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *UserJoinedRoomEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type UserLeftRoomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLeftRoomEvent) Reset() {
	*x = UserLeftRoomEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLeftRoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeftRoomEvent) ProtoMessage() {}

func (x *UserLeftRoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeftRoomEvent.ProtoReflect.Descriptor instead.
func (*UserLeftRoomEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{7}
}

func (x *UserLeftRoomEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *UserLeftRoomEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// SpaceMemberDeletedEvent is published when a user's account is deleted.
// This notifies all space members that the user is gone, so they can:
// - Update their member lists
// - Refresh messages to show "Deleted User" and unavailable content
type SpaceMemberDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceMemberDeletedEvent) Reset() {
	*x = SpaceMemberDeletedEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceMemberDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceMemberDeletedEvent) ProtoMessage() {}

func (x *SpaceMemberDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceMemberDeletedEvent.ProtoReflect.Descriptor instead.
func (*SpaceMemberDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{8}
}

func (x *SpaceMemberDeletedEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SpaceMemberDeletedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MessagePostedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space ID - required to locate the message body in the correct
	// SPACE_{spaceId}_BODIES KV bucket for lazy-loading
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Room ID - identifies which room this message belongs to
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Compound key for body storage in KV: {userId}.{eventId}
	// The userId prefix enables efficient per-user filtering for GDPR deletion.
	MessageBodyId string `protobuf:"bytes,3,opt,name=message_body_id,json=messageBodyId,proto3" json:"message_body_id,omitempty"`
	// Threading: event ID of the message this is replying to (empty = top-level message)
	InReplyTo string `protobuf:"bytes,4,opt,name=in_reply_to,json=inReplyTo,proto3" json:"in_reply_to,omitempty"`
	// Threading: event ID of the thread root message (empty = top-level message)
	// For direct replies to a root, in_thread == in_reply_to.
	// For nested replies, in_thread references the original root.
	InThread string `protobuf:"bytes,5,opt,name=in_thread,json=inThread,proto3" json:"in_thread,omitempty"`
	// User IDs of users mentioned via @username in the message body.
	// Only includes valid, resolved user IDs (invalid mentions are silently ignored).
	MentionedUserIds []string `protobuf:"bytes,6,rep,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"`
	// Event ID of the original thread reply this echoes (empty = not an echo)
	EchoOfEventId string `protobuf:"bytes,7,opt,name=echo_of_event_id,json=echoOfEventId,proto3" json:"echo_of_event_id,omitempty"`
	// Thread root event ID — the thread this echo originates from (empty = not an echo)
	EchoFromThreadRootEventId string `protobuf:"bytes,8,opt,name=echo_from_thread_root_event_id,json=echoFromThreadRootEventId,proto3" json:"echo_from_thread_root_event_id,omitempty"`
	// Parent event's ID (populated at read time for resolver access)
	// Used for reactions lookup since reactions are keyed by event ID
	EventId       string `protobuf:"bytes,1001,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePostedEvent) Reset() {
	*x = MessagePostedEvent{}
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePostedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePostedEvent) ProtoMessage() {}

func (x *MessagePostedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePostedEvent.ProtoReflect.Descriptor instead.
func (*MessagePostedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_event_proto_rawDescGZIP(), []int{9}
}

func (x *MessagePostedEvent) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *MessagePostedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessagePostedEvent) GetMessageBodyId() string {
	if x != nil {
		return x.MessageBodyId
	}
	return ""
}

func (x *MessagePostedEvent) GetInReplyTo() string {
	if x != nil {
		return x.InReplyTo
	}
	return ""
}

func (x *MessagePostedEvent) GetInThread() string {
	if x != nil {
		return x.InThread
	}
	return ""
}

func (x *MessagePostedEvent) GetMentionedUserIds() []string {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

func (x *MessagePostedEvent) GetEchoOfEventId() string {
	if x != nil {
		return x.EchoOfEventId
	}
	return ""
}

func (x *MessagePostedEvent) GetEchoFromThreadRootEventId() string {
	if x != nil {
		return x.EchoFromThreadRootEventId
	}
	return ""
}

func (x *MessagePostedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_chatto_core_v1_server_event_proto protoreflect.FileDescriptor

const file_chatto_core_v1_server_event_proto_rawDesc = "" +
	"\n" +
	"!chatto/core/v1/server_event.proto\x12\x0echatto.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fchatto/core/v1/live_event.proto\"\xaf\x10\n" +
	"\vServerEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12F\n" +
	"\froom_created\x18\xac\x02 \x01(\v2 .chatto.core.v1.RoomCreatedEventH\x00R\vroomCreated\x12F\n" +
	"\froom_updated\x18\xad\x02 \x01(\v2 .chatto.core.v1.RoomUpdatedEventH\x00R\vroomUpdated\x12F\n" +
	"\froom_deleted\x18\xae\x02 \x01(\v2 .chatto.core.v1.RoomDeletedEventH\x00R\vroomDeleted\x12I\n" +
	"\rroom_archived\x18\xaf\x02 \x01(\v2!.chatto.core.v1.RoomArchivedEventH\x00R\froomArchived\x12O\n" +
	"\x0froom_unarchived\x18\xb0\x02 \x01(\v2#.chatto.core.v1.RoomUnarchivedEventH\x00R\x0eroomUnarchived\x12P\n" +
	"\x10user_joined_room\x18\xb6\x02 \x01(\v2#.chatto.core.v1.UserJoinedRoomEventH\x00R\x0euserJoinedRoom\x12J\n" +
	"\x0euser_left_room\x18\xb7\x02 \x01(\v2!.chatto.core.v1.UserLeftRoomEventH\x00R\fuserLeftRoom\x12\\\n" +
	"\x14space_member_deleted\x18\xc0\x02 \x01(\v2'.chatto.core.v1.SpaceMemberDeletedEventH\x00R\x12spaceMemberDeleted\x12L\n" +
	"\x0emessage_posted\x18\x90\x03 \x01(\v2\".chatto.core.v1.MessagePostedEventH\x00R\rmessagePosted\x12O\n" +
	"\x0fmessage_updated\x18\x91\x03 \x01(\v2#.chatto.core.v1.MessageUpdatedEventH\x00R\x0emessageUpdated\x12O\n" +
	"\x0fmessage_deleted\x18\x92\x03 \x01(\v2#.chatto.core.v1.MessageDeletedEventH\x00R\x0emessageDeleted\x12L\n" +
	"\x0ereaction_added\x18\xf4\x03 \x01(\v2\".chatto.core.v1.ReactionAddedEventH\x00R\rreactionAdded\x12R\n" +
	"\x10reaction_removed\x18\xf5\x03 \x01(\v2$.chatto.core.v1.ReactionRemovedEventH\x00R\x0freactionRemoved\x12C\n" +
	"\vuser_typing\x18\xfe\x03 \x01(\v2\x1f.chatto.core.v1.UserTypingEventH\x00R\n" +
	"userTyping\x12n\n" +
	"\x1avideo_processing_completed\x18\x88\x04 \x01(\v2-.chatto.core.v1.VideoProcessingCompletedEventH\x00R\x18videoProcessingCompleted\x12R\n" +
	"\x10presence_changed\x18\xd8\x04 \x01(\v2$.chatto.core.v1.PresenceChangedEventH\x00R\x0fpresenceChanged\x12e\n" +
	"\x17call_participant_joined\x18\xc6\x05 \x01(\v2*.chatto.core.v1.CallParticipantJoinedEventH\x00R\x15callParticipantJoined\x12_\n" +
	"\x15call_participant_left\x18\xc7\x05 \x01(\v2(.chatto.core.v1.CallParticipantLeftEventH\x00R\x13callParticipantLeftB\a\n" +
	"\x05eventJ\x06\b\xa9F\x10\xaaFJ\x04\bd\x10eJ\x04\bn\x10oJ\x04\bo\x10pJ\x04\bp\x10qJ\x04\bq\x10rJ\x04\br\x10sJ\x04\bx\x10yJ\x04\by\x10zJ\x06\b\xc8\x01\x10\xc9\x01J\x06\b\xc9\x01\x10\xca\x01J\x06\b\xca\x01\x10\xcb\x01J\x06\b\xbc\x05\x10\xbd\x05J\x06\b\xbd\x05\x10\xbe\x05J\x06\b\xa0\x06\x10\xa1\x06J\x06\b\xa1\x06\x10\xa2\x06J\x06\b\x84\a\x10\x85\aJ\x06\b\x85\a\x10\x86\aR\x0econfig_updatedR\fuser_createdR\fuser_deletedR\x14user_profile_updatedR\x1fserver_user_preferences_updatedR\x1anotification_level_changedR\x11user_joined_spaceR\x0fuser_left_spaceR\rspace_createdR\rspace_updatedR\rspace_deletedR\x14mention_notificationR\x1fnew_direct_message_notificationR\x14notification_createdR\x16notification_dismissedR\x14new_message_in_spaceR\x13room_marked_as_read\"|\n" +
	"\x10RoomCreatedEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"|\n" +
	"\x10RoomUpdatedEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"F\n" +
	"\x10RoomDeletedEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"G\n" +
	"\x11RoomArchivedEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"I\n" +
	"\x13RoomUnarchivedEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"I\n" +
	"\x13UserJoinedRoomEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"G\n" +
	"\x11UserLeftRoomEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"M\n" +
	"\x17SpaceMemberDeletedEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xeb\x02\n" +
	"\x12MessagePostedEvent\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12&\n" +
	"\x0fmessage_body_id\x18\x03 \x01(\tR\rmessageBodyId\x12\x1e\n" +
	"\vin_reply_to\x18\x04 \x01(\tR\tinReplyTo\x12\x1b\n" +
	"\tin_thread\x18\x05 \x01(\tR\binThread\x12,\n" +
	"\x12mentioned_user_ids\x18\x06 \x03(\tR\x10mentionedUserIds\x12'\n" +
	"\x10echo_of_event_id\x18\a \x01(\tR\rechoOfEventId\x12A\n" +
	"\x1eecho_from_thread_root_event_id\x18\b \x01(\tR\x19echoFromThreadRootEventId\x12\x1a\n" +
	"\bevent_id\x18\xe9\a \x01(\tR\aeventIdJ\x06\b\xe8\a\x10\xe9\aB\xb3\x01\n" +
	"\x12com.chatto.core.v1B\x10ServerEventProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_server_event_proto_rawDescOnce sync.Once
	file_chatto_core_v1_server_event_proto_rawDescData []byte
)

func file_chatto_core_v1_server_event_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_server_event_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_server_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_server_event_proto_rawDesc), len(file_chatto_core_v1_server_event_proto_rawDesc)))
	})
	return file_chatto_core_v1_server_event_proto_rawDescData
}

var file_chatto_core_v1_server_event_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chatto_core_v1_server_event_proto_goTypes = []any{
	(*ServerEvent)(nil),                   // 0: chatto.core.v1.ServerEvent
	(*RoomCreatedEvent)(nil),              // 1: chatto.core.v1.RoomCreatedEvent
	(*RoomUpdatedEvent)(nil),              // 2: chatto.core.v1.RoomUpdatedEvent
	(*RoomDeletedEvent)(nil),              // 3: chatto.core.v1.RoomDeletedEvent
	(*RoomArchivedEvent)(nil),             // 4: chatto.core.v1.RoomArchivedEvent
	(*RoomUnarchivedEvent)(nil),           // 5: chatto.core.v1.RoomUnarchivedEvent
	(*UserJoinedRoomEvent)(nil),           // 6: chatto.core.v1.UserJoinedRoomEvent
	(*UserLeftRoomEvent)(nil),             // 7: chatto.core.v1.UserLeftRoomEvent
	(*SpaceMemberDeletedEvent)(nil),       // 8: chatto.core.v1.SpaceMemberDeletedEvent
	(*MessagePostedEvent)(nil),            // 9: chatto.core.v1.MessagePostedEvent
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
	(*MessageUpdatedEvent)(nil),           // 11: chatto.core.v1.MessageUpdatedEvent
	(*MessageDeletedEvent)(nil),           // 12: chatto.core.v1.MessageDeletedEvent
	(*ReactionAddedEvent)(nil),            // 13: chatto.core.v1.ReactionAddedEvent
	(*ReactionRemovedEvent)(nil),          // 14: chatto.core.v1.ReactionRemovedEvent
	(*UserTypingEvent)(nil),               // 15: chatto.core.v1.UserTypingEvent
	(*VideoProcessingCompletedEvent)(nil), // 16: chatto.core.v1.VideoProcessingCompletedEvent
	(*PresenceChangedEvent)(nil),          // 17: chatto.core.v1.PresenceChangedEvent
	(*CallParticipantJoinedEvent)(nil),    // 18: chatto.core.v1.CallParticipantJoinedEvent
	(*CallParticipantLeftEvent)(nil),      // 19: chatto.core.v1.CallParticipantLeftEvent
}
var file_chatto_core_v1_server_event_proto_depIdxs = []int32{
	10, // 0: chatto.core.v1.ServerEvent.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: chatto.core.v1.ServerEvent.room_created:type_name -> chatto.core.v1.RoomCreatedEvent
	2,  // 2: chatto.core.v1.ServerEvent.room_updated:type_name -> chatto.core.v1.RoomUpdatedEvent
	3,  // 3: chatto.core.v1.ServerEvent.room_deleted:type_name -> chatto.core.v1.RoomDeletedEvent
	4,  // 4: chatto.core.v1.ServerEvent.room_archived:type_name -> chatto.core.v1.RoomArchivedEvent
	5,  // 5: chatto.core.v1.ServerEvent.room_unarchived:type_name -> chatto.core.v1.RoomUnarchivedEvent
	6,  // 6: chatto.core.v1.ServerEvent.user_joined_room:type_name -> chatto.core.v1.UserJoinedRoomEvent
	7,  // 7: chatto.core.v1.ServerEvent.user_left_room:type_name -> chatto.core.v1.UserLeftRoomEvent
	8,  // 8: chatto.core.v1.ServerEvent.space_member_deleted:type_name -> chatto.core.v1.SpaceMemberDeletedEvent
	9,  // 9: chatto.core.v1.ServerEvent.message_posted:type_name -> chatto.core.v1.MessagePostedEvent
	11, // 10: chatto.core.v1.ServerEvent.message_updated:type_name -> chatto.core.v1.MessageUpdatedEvent
	12, // 11: chatto.core.v1.ServerEvent.message_deleted:type_name -> chatto.core.v1.MessageDeletedEvent
	13, // 12: chatto.core.v1.ServerEvent.reaction_added:type_name -> chatto.core.v1.ReactionAddedEvent
	14, // 13: chatto.core.v1.ServerEvent.reaction_removed:type_name -> chatto.core.v1.ReactionRemovedEvent
	15, // 14: chatto.core.v1.ServerEvent.user_typing:type_name -> chatto.core.v1.UserTypingEvent
	16, // 15: chatto.core.v1.ServerEvent.video_processing_completed:type_name -> chatto.core.v1.VideoProcessingCompletedEvent
	17, // 16: chatto.core.v1.ServerEvent.presence_changed:type_name -> chatto.core.v1.PresenceChangedEvent
	18, // 17: chatto.core.v1.ServerEvent.call_participant_joined:type_name -> chatto.core.v1.CallParticipantJoinedEvent
	19, // 18: chatto.core.v1.ServerEvent.call_participant_left:type_name -> chatto.core.v1.CallParticipantLeftEvent
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_server_event_proto_init() }
func file_chatto_core_v1_server_event_proto_init() {
	if File_chatto_core_v1_server_event_proto != nil {
		return
	}
	file_chatto_core_v1_live_event_proto_init()
	file_chatto_core_v1_server_event_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerEvent_RoomCreated)(nil),
		(*ServerEvent_RoomUpdated)(nil),
		(*ServerEvent_RoomDeleted)(nil),
		(*ServerEvent_RoomArchived)(nil),
		(*ServerEvent_RoomUnarchived)(nil),
		(*ServerEvent_UserJoinedRoom)(nil),
		(*ServerEvent_UserLeftRoom)(nil),
		(*ServerEvent_SpaceMemberDeleted)(nil),
		(*ServerEvent_MessagePosted)(nil),
		(*ServerEvent_MessageUpdated)(nil),
		(*ServerEvent_MessageDeleted)(nil),
		(*ServerEvent_ReactionAdded)(nil),
		(*ServerEvent_ReactionRemoved)(nil),
		(*ServerEvent_UserTyping)(nil),
		(*ServerEvent_VideoProcessingCompleted)(nil),
		(*ServerEvent_PresenceChanged)(nil),
		(*ServerEvent_CallParticipantJoined)(nil),
		(*ServerEvent_CallParticipantLeft)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_server_event_proto_rawDesc), len(file_chatto_core_v1_server_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_server_event_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_server_event_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_server_event_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_server_event_proto = out.File
	file_chatto_core_v1_server_event_proto_goTypes = nil
	file_chatto_core_v1_server_event_proto_depIdxs = nil
}
