// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/reactions.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddReactionRequest, AddReactionResponse, RemoveReactionRequest, RemoveReactionResponse } from "./reactions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Manages message reactions for the current user.
 *
 * @generated from service chatto.api.v1.ReactionService
 */
export const ReactionService = {
  typeName: "chatto.api.v1.ReactionService",
  methods: {
    /**
     * Adds a reaction to a message. The user must be a room member and have
     * message.react in the target room.
     *
     * @generated from rpc chatto.api.v1.ReactionService.AddReaction
     */
    addReaction: {
      name: "AddReaction",
      I: AddReactionRequest,
      O: AddReactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes a reaction from a message. The user must be a room member and have
     * message.react in the target room.
     *
     * @generated from rpc chatto.api.v1.ReactionService.RemoveReaction
     */
    removeReaction: {
      name: "RemoveReaction",
      I: RemoveReactionRequest,
      O: RemoveReactionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

