// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/read_state.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MarkRoomAsReadRequest, MarkRoomAsReadResponse, MarkThreadAsReadRequest, MarkThreadAsReadResponse } from "./read_state_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chatto.api.v1.ReadStateService
 */
export const ReadStateService = {
  typeName: "chatto.api.v1.ReadStateService",
  methods: {
    /**
     * @generated from rpc chatto.api.v1.ReadStateService.MarkRoomAsRead
     */
    markRoomAsRead: {
      name: "MarkRoomAsRead",
      I: MarkRoomAsReadRequest,
      O: MarkRoomAsReadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chatto.api.v1.ReadStateService.MarkThreadAsRead
     */
    markThreadAsRead: {
      name: "MarkThreadAsRead",
      I: MarkThreadAsReadRequest,
      O: MarkThreadAsReadResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

