// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/threads.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message chatto.api.v1.FollowThreadRequest
 */
export class FollowThreadRequest extends Message<FollowThreadRequest> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  constructor(data?: PartialMessage<FollowThreadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.FollowThreadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FollowThreadRequest {
    return new FollowThreadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FollowThreadRequest {
    return new FollowThreadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FollowThreadRequest {
    return new FollowThreadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FollowThreadRequest | PlainMessage<FollowThreadRequest> | undefined, b: FollowThreadRequest | PlainMessage<FollowThreadRequest> | undefined): boolean {
    return proto3.util.equals(FollowThreadRequest, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.FollowThreadResponse
 */
export class FollowThreadResponse extends Message<FollowThreadResponse> {
  /**
   * @generated from field: bool following = 1;
   */
  following = false;

  constructor(data?: PartialMessage<FollowThreadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.FollowThreadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "following", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FollowThreadResponse {
    return new FollowThreadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FollowThreadResponse {
    return new FollowThreadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FollowThreadResponse {
    return new FollowThreadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: FollowThreadResponse | PlainMessage<FollowThreadResponse> | undefined, b: FollowThreadResponse | PlainMessage<FollowThreadResponse> | undefined): boolean {
    return proto3.util.equals(FollowThreadResponse, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.UnfollowThreadRequest
 */
export class UnfollowThreadRequest extends Message<UnfollowThreadRequest> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  constructor(data?: PartialMessage<UnfollowThreadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UnfollowThreadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnfollowThreadRequest {
    return new UnfollowThreadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnfollowThreadRequest {
    return new UnfollowThreadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnfollowThreadRequest {
    return new UnfollowThreadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UnfollowThreadRequest | PlainMessage<UnfollowThreadRequest> | undefined, b: UnfollowThreadRequest | PlainMessage<UnfollowThreadRequest> | undefined): boolean {
    return proto3.util.equals(UnfollowThreadRequest, a, b);
  }
}

/**
 * @generated from message chatto.api.v1.UnfollowThreadResponse
 */
export class UnfollowThreadResponse extends Message<UnfollowThreadResponse> {
  /**
   * @generated from field: bool following = 1;
   */
  following = false;

  constructor(data?: PartialMessage<UnfollowThreadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UnfollowThreadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "following", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnfollowThreadResponse {
    return new UnfollowThreadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnfollowThreadResponse {
    return new UnfollowThreadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnfollowThreadResponse {
    return new UnfollowThreadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UnfollowThreadResponse | PlainMessage<UnfollowThreadResponse> | undefined, b: UnfollowThreadResponse | PlainMessage<UnfollowThreadResponse> | undefined): boolean {
    return proto3.util.equals(UnfollowThreadResponse, a, b);
  }
}

