// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/permissions.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PermissionServiceName is the fully-qualified name of the PermissionService service.
	PermissionServiceName = "chatto.api.v1.PermissionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PermissionServiceGetRolePermissionTierMatrixProcedure is the fully-qualified name of the
	// PermissionService's GetRolePermissionTierMatrix RPC.
	PermissionServiceGetRolePermissionTierMatrixProcedure = "/chatto.api.v1.PermissionService/GetRolePermissionTierMatrix"
	// PermissionServiceGetRolePermissionMatrixProcedure is the fully-qualified name of the
	// PermissionService's GetRolePermissionMatrix RPC.
	PermissionServiceGetRolePermissionMatrixProcedure = "/chatto.api.v1.PermissionService/GetRolePermissionMatrix"
	// PermissionServiceGetUserPermissionMatrixProcedure is the fully-qualified name of the
	// PermissionService's GetUserPermissionMatrix RPC.
	PermissionServiceGetUserPermissionMatrixProcedure = "/chatto.api.v1.PermissionService/GetUserPermissionMatrix"
	// PermissionServiceExplainPermissionsProcedure is the fully-qualified name of the
	// PermissionService's ExplainPermissions RPC.
	PermissionServiceExplainPermissionsProcedure = "/chatto.api.v1.PermissionService/ExplainPermissions"
	// PermissionServiceSetRolePermissionProcedure is the fully-qualified name of the
	// PermissionService's SetRolePermission RPC.
	PermissionServiceSetRolePermissionProcedure = "/chatto.api.v1.PermissionService/SetRolePermission"
	// PermissionServiceSetUserPermissionProcedure is the fully-qualified name of the
	// PermissionService's SetUserPermission RPC.
	PermissionServiceSetUserPermissionProcedure = "/chatto.api.v1.PermissionService/SetUserPermission"
)

// PermissionServiceClient is a client for the chatto.api.v1.PermissionService service.
type PermissionServiceClient interface {
	// Gets the role-permission matrix for a single tier.
	GetRolePermissionTierMatrix(context.Context, *connect.Request[v1.GetRolePermissionTierMatrixRequest]) (*connect.Response[v1.GetRolePermissionTierMatrixResponse], error)
	// Gets one role's full permission matrix. Requires role.manage. Returns
	// NOT_FOUND when the role does not exist.
	GetRolePermissionMatrix(context.Context, *connect.Request[v1.GetRolePermissionMatrixRequest]) (*connect.Response[v1.GetRolePermissionMatrixResponse], error)
	// Gets one user's full permission matrix. Requires user.manage-permissions.
	GetUserPermissionMatrix(context.Context, *connect.Request[v1.GetUserPermissionMatrixRequest]) (*connect.Response[v1.GetUserPermissionMatrixResponse], error)
	// Explains permission resolution for another user. Requires role.manage.
	ExplainPermissions(context.Context, *connect.Request[v1.ExplainPermissionsRequest]) (*connect.Response[v1.ExplainPermissionsResponse], error)
	// Sets one role permission decision. Requires role.manage or scoped room.manage for room scope.
	SetRolePermission(context.Context, *connect.Request[v1.SetRolePermissionRequest]) (*connect.Response[v1.SetRolePermissionResponse], error)
	// Sets one user permission decision. Requires user.manage-permissions.
	SetUserPermission(context.Context, *connect.Request[v1.SetUserPermissionRequest]) (*connect.Response[v1.SetUserPermissionResponse], error)
}

// NewPermissionServiceClient constructs a client for the chatto.api.v1.PermissionService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPermissionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PermissionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	permissionServiceMethods := v1.File_chatto_api_v1_permissions_proto.Services().ByName("PermissionService").Methods()
	return &permissionServiceClient{
		getRolePermissionTierMatrix: connect.NewClient[v1.GetRolePermissionTierMatrixRequest, v1.GetRolePermissionTierMatrixResponse](
			httpClient,
			baseURL+PermissionServiceGetRolePermissionTierMatrixProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("GetRolePermissionTierMatrix")),
			connect.WithClientOptions(opts...),
		),
		getRolePermissionMatrix: connect.NewClient[v1.GetRolePermissionMatrixRequest, v1.GetRolePermissionMatrixResponse](
			httpClient,
			baseURL+PermissionServiceGetRolePermissionMatrixProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("GetRolePermissionMatrix")),
			connect.WithClientOptions(opts...),
		),
		getUserPermissionMatrix: connect.NewClient[v1.GetUserPermissionMatrixRequest, v1.GetUserPermissionMatrixResponse](
			httpClient,
			baseURL+PermissionServiceGetUserPermissionMatrixProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("GetUserPermissionMatrix")),
			connect.WithClientOptions(opts...),
		),
		explainPermissions: connect.NewClient[v1.ExplainPermissionsRequest, v1.ExplainPermissionsResponse](
			httpClient,
			baseURL+PermissionServiceExplainPermissionsProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("ExplainPermissions")),
			connect.WithClientOptions(opts...),
		),
		setRolePermission: connect.NewClient[v1.SetRolePermissionRequest, v1.SetRolePermissionResponse](
			httpClient,
			baseURL+PermissionServiceSetRolePermissionProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("SetRolePermission")),
			connect.WithClientOptions(opts...),
		),
		setUserPermission: connect.NewClient[v1.SetUserPermissionRequest, v1.SetUserPermissionResponse](
			httpClient,
			baseURL+PermissionServiceSetUserPermissionProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("SetUserPermission")),
			connect.WithClientOptions(opts...),
		),
	}
}

// permissionServiceClient implements PermissionServiceClient.
type permissionServiceClient struct {
	getRolePermissionTierMatrix *connect.Client[v1.GetRolePermissionTierMatrixRequest, v1.GetRolePermissionTierMatrixResponse]
	getRolePermissionMatrix     *connect.Client[v1.GetRolePermissionMatrixRequest, v1.GetRolePermissionMatrixResponse]
	getUserPermissionMatrix     *connect.Client[v1.GetUserPermissionMatrixRequest, v1.GetUserPermissionMatrixResponse]
	explainPermissions          *connect.Client[v1.ExplainPermissionsRequest, v1.ExplainPermissionsResponse]
	setRolePermission           *connect.Client[v1.SetRolePermissionRequest, v1.SetRolePermissionResponse]
	setUserPermission           *connect.Client[v1.SetUserPermissionRequest, v1.SetUserPermissionResponse]
}

// GetRolePermissionTierMatrix calls chatto.api.v1.PermissionService.GetRolePermissionTierMatrix.
func (c *permissionServiceClient) GetRolePermissionTierMatrix(ctx context.Context, req *connect.Request[v1.GetRolePermissionTierMatrixRequest]) (*connect.Response[v1.GetRolePermissionTierMatrixResponse], error) {
	return c.getRolePermissionTierMatrix.CallUnary(ctx, req)
}

// GetRolePermissionMatrix calls chatto.api.v1.PermissionService.GetRolePermissionMatrix.
func (c *permissionServiceClient) GetRolePermissionMatrix(ctx context.Context, req *connect.Request[v1.GetRolePermissionMatrixRequest]) (*connect.Response[v1.GetRolePermissionMatrixResponse], error) {
	return c.getRolePermissionMatrix.CallUnary(ctx, req)
}

// GetUserPermissionMatrix calls chatto.api.v1.PermissionService.GetUserPermissionMatrix.
func (c *permissionServiceClient) GetUserPermissionMatrix(ctx context.Context, req *connect.Request[v1.GetUserPermissionMatrixRequest]) (*connect.Response[v1.GetUserPermissionMatrixResponse], error) {
	return c.getUserPermissionMatrix.CallUnary(ctx, req)
}

// ExplainPermissions calls chatto.api.v1.PermissionService.ExplainPermissions.
func (c *permissionServiceClient) ExplainPermissions(ctx context.Context, req *connect.Request[v1.ExplainPermissionsRequest]) (*connect.Response[v1.ExplainPermissionsResponse], error) {
	return c.explainPermissions.CallUnary(ctx, req)
}

// SetRolePermission calls chatto.api.v1.PermissionService.SetRolePermission.
func (c *permissionServiceClient) SetRolePermission(ctx context.Context, req *connect.Request[v1.SetRolePermissionRequest]) (*connect.Response[v1.SetRolePermissionResponse], error) {
	return c.setRolePermission.CallUnary(ctx, req)
}

// SetUserPermission calls chatto.api.v1.PermissionService.SetUserPermission.
func (c *permissionServiceClient) SetUserPermission(ctx context.Context, req *connect.Request[v1.SetUserPermissionRequest]) (*connect.Response[v1.SetUserPermissionResponse], error) {
	return c.setUserPermission.CallUnary(ctx, req)
}

// PermissionServiceHandler is an implementation of the chatto.api.v1.PermissionService service.
type PermissionServiceHandler interface {
	// Gets the role-permission matrix for a single tier.
	GetRolePermissionTierMatrix(context.Context, *connect.Request[v1.GetRolePermissionTierMatrixRequest]) (*connect.Response[v1.GetRolePermissionTierMatrixResponse], error)
	// Gets one role's full permission matrix. Requires role.manage. Returns
	// NOT_FOUND when the role does not exist.
	GetRolePermissionMatrix(context.Context, *connect.Request[v1.GetRolePermissionMatrixRequest]) (*connect.Response[v1.GetRolePermissionMatrixResponse], error)
	// Gets one user's full permission matrix. Requires user.manage-permissions.
	GetUserPermissionMatrix(context.Context, *connect.Request[v1.GetUserPermissionMatrixRequest]) (*connect.Response[v1.GetUserPermissionMatrixResponse], error)
	// Explains permission resolution for another user. Requires role.manage.
	ExplainPermissions(context.Context, *connect.Request[v1.ExplainPermissionsRequest]) (*connect.Response[v1.ExplainPermissionsResponse], error)
	// Sets one role permission decision. Requires role.manage or scoped room.manage for room scope.
	SetRolePermission(context.Context, *connect.Request[v1.SetRolePermissionRequest]) (*connect.Response[v1.SetRolePermissionResponse], error)
	// Sets one user permission decision. Requires user.manage-permissions.
	SetUserPermission(context.Context, *connect.Request[v1.SetUserPermissionRequest]) (*connect.Response[v1.SetUserPermissionResponse], error)
}

// NewPermissionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPermissionServiceHandler(svc PermissionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	permissionServiceMethods := v1.File_chatto_api_v1_permissions_proto.Services().ByName("PermissionService").Methods()
	permissionServiceGetRolePermissionTierMatrixHandler := connect.NewUnaryHandler(
		PermissionServiceGetRolePermissionTierMatrixProcedure,
		svc.GetRolePermissionTierMatrix,
		connect.WithSchema(permissionServiceMethods.ByName("GetRolePermissionTierMatrix")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceGetRolePermissionMatrixHandler := connect.NewUnaryHandler(
		PermissionServiceGetRolePermissionMatrixProcedure,
		svc.GetRolePermissionMatrix,
		connect.WithSchema(permissionServiceMethods.ByName("GetRolePermissionMatrix")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceGetUserPermissionMatrixHandler := connect.NewUnaryHandler(
		PermissionServiceGetUserPermissionMatrixProcedure,
		svc.GetUserPermissionMatrix,
		connect.WithSchema(permissionServiceMethods.ByName("GetUserPermissionMatrix")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceExplainPermissionsHandler := connect.NewUnaryHandler(
		PermissionServiceExplainPermissionsProcedure,
		svc.ExplainPermissions,
		connect.WithSchema(permissionServiceMethods.ByName("ExplainPermissions")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceSetRolePermissionHandler := connect.NewUnaryHandler(
		PermissionServiceSetRolePermissionProcedure,
		svc.SetRolePermission,
		connect.WithSchema(permissionServiceMethods.ByName("SetRolePermission")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceSetUserPermissionHandler := connect.NewUnaryHandler(
		PermissionServiceSetUserPermissionProcedure,
		svc.SetUserPermission,
		connect.WithSchema(permissionServiceMethods.ByName("SetUserPermission")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.PermissionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PermissionServiceGetRolePermissionTierMatrixProcedure:
			permissionServiceGetRolePermissionTierMatrixHandler.ServeHTTP(w, r)
		case PermissionServiceGetRolePermissionMatrixProcedure:
			permissionServiceGetRolePermissionMatrixHandler.ServeHTTP(w, r)
		case PermissionServiceGetUserPermissionMatrixProcedure:
			permissionServiceGetUserPermissionMatrixHandler.ServeHTTP(w, r)
		case PermissionServiceExplainPermissionsProcedure:
			permissionServiceExplainPermissionsHandler.ServeHTTP(w, r)
		case PermissionServiceSetRolePermissionProcedure:
			permissionServiceSetRolePermissionHandler.ServeHTTP(w, r)
		case PermissionServiceSetUserPermissionProcedure:
			permissionServiceSetUserPermissionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPermissionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPermissionServiceHandler struct{}

func (UnimplementedPermissionServiceHandler) GetRolePermissionTierMatrix(context.Context, *connect.Request[v1.GetRolePermissionTierMatrixRequest]) (*connect.Response[v1.GetRolePermissionTierMatrixResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PermissionService.GetRolePermissionTierMatrix is not implemented"))
}

func (UnimplementedPermissionServiceHandler) GetRolePermissionMatrix(context.Context, *connect.Request[v1.GetRolePermissionMatrixRequest]) (*connect.Response[v1.GetRolePermissionMatrixResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PermissionService.GetRolePermissionMatrix is not implemented"))
}

func (UnimplementedPermissionServiceHandler) GetUserPermissionMatrix(context.Context, *connect.Request[v1.GetUserPermissionMatrixRequest]) (*connect.Response[v1.GetUserPermissionMatrixResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PermissionService.GetUserPermissionMatrix is not implemented"))
}

func (UnimplementedPermissionServiceHandler) ExplainPermissions(context.Context, *connect.Request[v1.ExplainPermissionsRequest]) (*connect.Response[v1.ExplainPermissionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PermissionService.ExplainPermissions is not implemented"))
}

func (UnimplementedPermissionServiceHandler) SetRolePermission(context.Context, *connect.Request[v1.SetRolePermissionRequest]) (*connect.Response[v1.SetRolePermissionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PermissionService.SetRolePermission is not implemented"))
}

func (UnimplementedPermissionServiceHandler) SetUserPermission(context.Context, *connect.Request[v1.SetUserPermissionRequest]) (*connect.Response[v1.SetUserPermissionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PermissionService.SetUserPermission is not implemented"))
}
