// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/user_status.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserStatusServiceName is the fully-qualified name of the UserStatusService service.
	UserStatusServiceName = "chatto.api.v1.UserStatusService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserStatusServiceSetCustomStatusProcedure is the fully-qualified name of the UserStatusService's
	// SetCustomStatus RPC.
	UserStatusServiceSetCustomStatusProcedure = "/chatto.api.v1.UserStatusService/SetCustomStatus"
	// UserStatusServiceClearCustomStatusProcedure is the fully-qualified name of the
	// UserStatusService's ClearCustomStatus RPC.
	UserStatusServiceClearCustomStatusProcedure = "/chatto.api.v1.UserStatusService/ClearCustomStatus"
)

// UserStatusServiceClient is a client for the chatto.api.v1.UserStatusService service.
type UserStatusServiceClient interface {
	SetCustomStatus(context.Context, *connect.Request[v1.SetCustomStatusRequest]) (*connect.Response[v1.SetCustomStatusResponse], error)
	ClearCustomStatus(context.Context, *connect.Request[v1.ClearCustomStatusRequest]) (*connect.Response[v1.ClearCustomStatusResponse], error)
}

// NewUserStatusServiceClient constructs a client for the chatto.api.v1.UserStatusService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserStatusServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserStatusServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userStatusServiceMethods := v1.File_chatto_api_v1_user_status_proto.Services().ByName("UserStatusService").Methods()
	return &userStatusServiceClient{
		setCustomStatus: connect.NewClient[v1.SetCustomStatusRequest, v1.SetCustomStatusResponse](
			httpClient,
			baseURL+UserStatusServiceSetCustomStatusProcedure,
			connect.WithSchema(userStatusServiceMethods.ByName("SetCustomStatus")),
			connect.WithClientOptions(opts...),
		),
		clearCustomStatus: connect.NewClient[v1.ClearCustomStatusRequest, v1.ClearCustomStatusResponse](
			httpClient,
			baseURL+UserStatusServiceClearCustomStatusProcedure,
			connect.WithSchema(userStatusServiceMethods.ByName("ClearCustomStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userStatusServiceClient implements UserStatusServiceClient.
type userStatusServiceClient struct {
	setCustomStatus   *connect.Client[v1.SetCustomStatusRequest, v1.SetCustomStatusResponse]
	clearCustomStatus *connect.Client[v1.ClearCustomStatusRequest, v1.ClearCustomStatusResponse]
}

// SetCustomStatus calls chatto.api.v1.UserStatusService.SetCustomStatus.
func (c *userStatusServiceClient) SetCustomStatus(ctx context.Context, req *connect.Request[v1.SetCustomStatusRequest]) (*connect.Response[v1.SetCustomStatusResponse], error) {
	return c.setCustomStatus.CallUnary(ctx, req)
}

// ClearCustomStatus calls chatto.api.v1.UserStatusService.ClearCustomStatus.
func (c *userStatusServiceClient) ClearCustomStatus(ctx context.Context, req *connect.Request[v1.ClearCustomStatusRequest]) (*connect.Response[v1.ClearCustomStatusResponse], error) {
	return c.clearCustomStatus.CallUnary(ctx, req)
}

// UserStatusServiceHandler is an implementation of the chatto.api.v1.UserStatusService service.
type UserStatusServiceHandler interface {
	SetCustomStatus(context.Context, *connect.Request[v1.SetCustomStatusRequest]) (*connect.Response[v1.SetCustomStatusResponse], error)
	ClearCustomStatus(context.Context, *connect.Request[v1.ClearCustomStatusRequest]) (*connect.Response[v1.ClearCustomStatusResponse], error)
}

// NewUserStatusServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserStatusServiceHandler(svc UserStatusServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userStatusServiceMethods := v1.File_chatto_api_v1_user_status_proto.Services().ByName("UserStatusService").Methods()
	userStatusServiceSetCustomStatusHandler := connect.NewUnaryHandler(
		UserStatusServiceSetCustomStatusProcedure,
		svc.SetCustomStatus,
		connect.WithSchema(userStatusServiceMethods.ByName("SetCustomStatus")),
		connect.WithHandlerOptions(opts...),
	)
	userStatusServiceClearCustomStatusHandler := connect.NewUnaryHandler(
		UserStatusServiceClearCustomStatusProcedure,
		svc.ClearCustomStatus,
		connect.WithSchema(userStatusServiceMethods.ByName("ClearCustomStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.UserStatusService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserStatusServiceSetCustomStatusProcedure:
			userStatusServiceSetCustomStatusHandler.ServeHTTP(w, r)
		case UserStatusServiceClearCustomStatusProcedure:
			userStatusServiceClearCustomStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserStatusServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserStatusServiceHandler struct{}

func (UnimplementedUserStatusServiceHandler) SetCustomStatus(context.Context, *connect.Request[v1.SetCustomStatusRequest]) (*connect.Response[v1.SetCustomStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.UserStatusService.SetCustomStatus is not implemented"))
}

func (UnimplementedUserStatusServiceHandler) ClearCustomStatus(context.Context, *connect.Request[v1.ClearCustomStatusRequest]) (*connect.Response[v1.ClearCustomStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.UserStatusService.ClearCustomStatus is not implemented"))
}
