// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/attachments.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fit mode used when generating transformed attachment thumbnails.
type AttachmentFitMode int32

const (
	// The fit mode was not specified.
	AttachmentFitMode_ATTACHMENT_FIT_MODE_UNSPECIFIED AttachmentFitMode = 0
	// Preserve the whole source image within the requested bounds.
	AttachmentFitMode_ATTACHMENT_FIT_MODE_CONTAIN AttachmentFitMode = 1
	// Fill the requested bounds, cropping when needed.
	AttachmentFitMode_ATTACHMENT_FIT_MODE_COVER AttachmentFitMode = 2
)

// Enum value maps for AttachmentFitMode.
var (
	AttachmentFitMode_name = map[int32]string{
		0: "ATTACHMENT_FIT_MODE_UNSPECIFIED",
		1: "ATTACHMENT_FIT_MODE_CONTAIN",
		2: "ATTACHMENT_FIT_MODE_COVER",
	}
	AttachmentFitMode_value = map[string]int32{
		"ATTACHMENT_FIT_MODE_UNSPECIFIED": 0,
		"ATTACHMENT_FIT_MODE_CONTAIN":     1,
		"ATTACHMENT_FIT_MODE_COVER":       2,
	}
)

func (x AttachmentFitMode) Enum() *AttachmentFitMode {
	p := new(AttachmentFitMode)
	*p = x
	return p
}

func (x AttachmentFitMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentFitMode) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_attachments_proto_enumTypes[0].Descriptor()
}

func (AttachmentFitMode) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_attachments_proto_enumTypes[0]
}

func (x AttachmentFitMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentFitMode.Descriptor instead.
func (AttachmentFitMode) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_attachments_proto_rawDescGZIP(), []int{0}
}

// Thumbnail transform parameters for attachment URL reads.
type AttachmentThumbnailOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Thumbnail width in pixels.
	Width int32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	// Thumbnail height in pixels.
	Height int32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// Thumbnail fit mode.
	Fit           AttachmentFitMode `protobuf:"varint,3,opt,name=fit,proto3,enum=chatto.api.v1.AttachmentFitMode" json:"fit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentThumbnailOptions) Reset() {
	*x = AttachmentThumbnailOptions{}
	mi := &file_chatto_api_v1_attachments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentThumbnailOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentThumbnailOptions) ProtoMessage() {}

func (x *AttachmentThumbnailOptions) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_attachments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentThumbnailOptions.ProtoReflect.Descriptor instead.
func (*AttachmentThumbnailOptions) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_attachments_proto_rawDescGZIP(), []int{0}
}

func (x *AttachmentThumbnailOptions) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AttachmentThumbnailOptions) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AttachmentThumbnailOptions) GetFit() AttachmentFitMode {
	if x != nil {
		return x.Fit
	}
	return AttachmentFitMode_ATTACHMENT_FIT_MODE_UNSPECIFIED
}

// One current room attachment and its message anchor.
type RoomAttachmentListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attachment metadata and signed URLs.
	Attachment *RoomTimelineAttachment `protobuf:"bytes,1,opt,name=attachment,proto3" json:"attachment,omitempty"`
	// Message event containing the attachment.
	MessageEventId string `protobuf:"bytes,2,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	// Thread root event ID when the containing message is a thread reply.
	ThreadRootEventId string `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	// Message creation timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomAttachmentListItem) Reset() {
	*x = RoomAttachmentListItem{}
	mi := &file_chatto_api_v1_attachments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomAttachmentListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAttachmentListItem) ProtoMessage() {}

func (x *RoomAttachmentListItem) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_attachments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAttachmentListItem.ProtoReflect.Descriptor instead.
func (*RoomAttachmentListItem) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_attachments_proto_rawDescGZIP(), []int{1}
}

func (x *RoomAttachmentListItem) GetAttachment() *RoomTimelineAttachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *RoomAttachmentListItem) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

func (x *RoomAttachmentListItem) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *RoomAttachmentListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Fresh signed URLs for one message attachment.
type RefreshedAttachmentUrls struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attachment ID these URLs belong to.
	AttachmentId string `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	// Fresh signed URL for the original attachment.
	AssetUrl *RoomTimelineAssetUrl `protobuf:"bytes,2,opt,name=asset_url,json=assetUrl,proto3" json:"asset_url,omitempty"`
	// Fresh signed transformed thumbnail URL for the attachment.
	ThumbnailAssetUrl *RoomTimelineAssetUrl `protobuf:"bytes,3,opt,name=thumbnail_asset_url,json=thumbnailAssetUrl,proto3" json:"thumbnail_asset_url,omitempty"`
	// Fresh signed URL for the processed video thumbnail, when present.
	VideoThumbnailAssetUrl *RoomTimelineAssetUrl `protobuf:"bytes,4,opt,name=video_thumbnail_asset_url,json=videoThumbnailAssetUrl,proto3" json:"video_thumbnail_asset_url,omitempty"`
	// Fresh signed URLs for processed video variants, when present.
	Variants      []*RoomTimelineVideoVariant `protobuf:"bytes,5,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshedAttachmentUrls) Reset() {
	*x = RefreshedAttachmentUrls{}
	mi := &file_chatto_api_v1_attachments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshedAttachmentUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshedAttachmentUrls) ProtoMessage() {}

func (x *RefreshedAttachmentUrls) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_attachments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshedAttachmentUrls.ProtoReflect.Descriptor instead.
func (*RefreshedAttachmentUrls) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_attachments_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshedAttachmentUrls) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *RefreshedAttachmentUrls) GetAssetUrl() *RoomTimelineAssetUrl {
	if x != nil {
		return x.AssetUrl
	}
	return nil
}

func (x *RefreshedAttachmentUrls) GetThumbnailAssetUrl() *RoomTimelineAssetUrl {
	if x != nil {
		return x.ThumbnailAssetUrl
	}
	return nil
}

func (x *RefreshedAttachmentUrls) GetVideoThumbnailAssetUrl() *RoomTimelineAssetUrl {
	if x != nil {
		return x.VideoThumbnailAssetUrl
	}
	return nil
}

func (x *RefreshedAttachmentUrls) GetVariants() []*RoomTimelineVideoVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

var File_chatto_api_v1_attachments_proto protoreflect.FileDescriptor

const file_chatto_api_v1_attachments_proto_rawDesc = "" +
	"\n" +
	"\x1fchatto/api/v1/attachments.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a!chatto/api/v1/room_timeline.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\x1aAttachmentThumbnailOptions\x12 \n" +
	"\x05width\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x80 (\x01R\x05width\x12\"\n" +
	"\x06height\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x80 (\x01R\x06height\x12<\n" +
	"\x03fit\x18\x03 \x01(\x0e2 .chatto.api.v1.AttachmentFitModeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x03fit\"\xf5\x01\n" +
	"\x16RoomAttachmentListItem\x12E\n" +
	"\n" +
	"attachment\x18\x01 \x01(\v2%.chatto.api.v1.RoomTimelineAttachmentR\n" +
	"attachment\x12(\n" +
	"\x10message_event_id\x18\x02 \x01(\tR\x0emessageEventId\x12/\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tR\x11threadRootEventId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xfa\x02\n" +
	"\x17RefreshedAttachmentUrls\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12@\n" +
	"\tasset_url\x18\x02 \x01(\v2#.chatto.api.v1.RoomTimelineAssetUrlR\bassetUrl\x12S\n" +
	"\x13thumbnail_asset_url\x18\x03 \x01(\v2#.chatto.api.v1.RoomTimelineAssetUrlR\x11thumbnailAssetUrl\x12^\n" +
	"\x19video_thumbnail_asset_url\x18\x04 \x01(\v2#.chatto.api.v1.RoomTimelineAssetUrlR\x16videoThumbnailAssetUrl\x12C\n" +
	"\bvariants\x18\x05 \x03(\v2'.chatto.api.v1.RoomTimelineVideoVariantR\bvariants*x\n" +
	"\x11AttachmentFitMode\x12#\n" +
	"\x1fATTACHMENT_FIT_MODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bATTACHMENT_FIT_MODE_CONTAIN\x10\x01\x12\x1d\n" +
	"\x19ATTACHMENT_FIT_MODE_COVER\x10\x02B\xac\x01\n" +
	"\x11com.chatto.api.v1B\x10AttachmentsProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_attachments_proto_rawDescOnce sync.Once
	file_chatto_api_v1_attachments_proto_rawDescData []byte
)

func file_chatto_api_v1_attachments_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_attachments_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_attachments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_attachments_proto_rawDesc), len(file_chatto_api_v1_attachments_proto_rawDesc)))
	})
	return file_chatto_api_v1_attachments_proto_rawDescData
}

var file_chatto_api_v1_attachments_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_attachments_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chatto_api_v1_attachments_proto_goTypes = []any{
	(AttachmentFitMode)(0),             // 0: chatto.api.v1.AttachmentFitMode
	(*AttachmentThumbnailOptions)(nil), // 1: chatto.api.v1.AttachmentThumbnailOptions
	(*RoomAttachmentListItem)(nil),     // 2: chatto.api.v1.RoomAttachmentListItem
	(*RefreshedAttachmentUrls)(nil),    // 3: chatto.api.v1.RefreshedAttachmentUrls
	(*RoomTimelineAttachment)(nil),     // 4: chatto.api.v1.RoomTimelineAttachment
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
	(*RoomTimelineAssetUrl)(nil),       // 6: chatto.api.v1.RoomTimelineAssetUrl
	(*RoomTimelineVideoVariant)(nil),   // 7: chatto.api.v1.RoomTimelineVideoVariant
}
var file_chatto_api_v1_attachments_proto_depIdxs = []int32{
	0, // 0: chatto.api.v1.AttachmentThumbnailOptions.fit:type_name -> chatto.api.v1.AttachmentFitMode
	4, // 1: chatto.api.v1.RoomAttachmentListItem.attachment:type_name -> chatto.api.v1.RoomTimelineAttachment
	5, // 2: chatto.api.v1.RoomAttachmentListItem.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: chatto.api.v1.RefreshedAttachmentUrls.asset_url:type_name -> chatto.api.v1.RoomTimelineAssetUrl
	6, // 4: chatto.api.v1.RefreshedAttachmentUrls.thumbnail_asset_url:type_name -> chatto.api.v1.RoomTimelineAssetUrl
	6, // 5: chatto.api.v1.RefreshedAttachmentUrls.video_thumbnail_asset_url:type_name -> chatto.api.v1.RoomTimelineAssetUrl
	7, // 6: chatto.api.v1.RefreshedAttachmentUrls.variants:type_name -> chatto.api.v1.RoomTimelineVideoVariant
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_attachments_proto_init() }
func file_chatto_api_v1_attachments_proto_init() {
	if File_chatto_api_v1_attachments_proto != nil {
		return
	}
	file_chatto_api_v1_room_timeline_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_attachments_proto_rawDesc), len(file_chatto_api_v1_attachments_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_api_v1_attachments_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_attachments_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_attachments_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_attachments_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_attachments_proto = out.File
	file_chatto_api_v1_attachments_proto_goTypes = nil
	file_chatto_api_v1_attachments_proto_depIdxs = nil
}
