// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/notification_preferences.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification delivery level for a room.
type NotificationLevel int32

const (
	// The level was not specified.
	NotificationLevel_NOTIFICATION_LEVEL_UNSPECIFIED NotificationLevel = 0
	// Use the inherited default for the room.
	NotificationLevel_NOTIFICATION_LEVEL_DEFAULT NotificationLevel = 1
	// Do not notify for this room.
	NotificationLevel_NOTIFICATION_LEVEL_MUTED NotificationLevel = 2
	// Notify according to the normal room rules.
	NotificationLevel_NOTIFICATION_LEVEL_NORMAL NotificationLevel = 3
	// Notify for every message in the room.
	NotificationLevel_NOTIFICATION_LEVEL_ALL_MESSAGES NotificationLevel = 4
)

// Enum value maps for NotificationLevel.
var (
	NotificationLevel_name = map[int32]string{
		0: "NOTIFICATION_LEVEL_UNSPECIFIED",
		1: "NOTIFICATION_LEVEL_DEFAULT",
		2: "NOTIFICATION_LEVEL_MUTED",
		3: "NOTIFICATION_LEVEL_NORMAL",
		4: "NOTIFICATION_LEVEL_ALL_MESSAGES",
	}
	NotificationLevel_value = map[string]int32{
		"NOTIFICATION_LEVEL_UNSPECIFIED":  0,
		"NOTIFICATION_LEVEL_DEFAULT":      1,
		"NOTIFICATION_LEVEL_MUTED":        2,
		"NOTIFICATION_LEVEL_NORMAL":       3,
		"NOTIFICATION_LEVEL_ALL_MESSAGES": 4,
	}
)

func (x NotificationLevel) Enum() *NotificationLevel {
	p := new(NotificationLevel)
	*p = x
	return p
}

func (x NotificationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_notification_preferences_proto_enumTypes[0].Descriptor()
}

func (NotificationLevel) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_notification_preferences_proto_enumTypes[0]
}

func (x NotificationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationLevel.Descriptor instead.
func (NotificationLevel) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_notification_preferences_proto_rawDescGZIP(), []int{0}
}

// Current notification preference for a room.
//
// Clients can show both the stored room-level setting and the effective setting
// the server will apply after defaults are resolved.
type GetRoomNotificationPreferenceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit level stored for the current user and room.
	Level NotificationLevel `protobuf:"varint,1,opt,name=level,proto3,enum=chatto.api.v1.NotificationLevel" json:"level,omitempty"`
	// Level after applying defaults and inheritance.
	EffectiveLevel NotificationLevel `protobuf:"varint,2,opt,name=effective_level,json=effectiveLevel,proto3,enum=chatto.api.v1.NotificationLevel" json:"effective_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRoomNotificationPreferenceResponse) Reset() {
	*x = GetRoomNotificationPreferenceResponse{}
	mi := &file_chatto_api_v1_notification_preferences_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomNotificationPreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomNotificationPreferenceResponse) ProtoMessage() {}

func (x *GetRoomNotificationPreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_notification_preferences_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomNotificationPreferenceResponse.ProtoReflect.Descriptor instead.
func (*GetRoomNotificationPreferenceResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_notification_preferences_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomNotificationPreferenceResponse) GetLevel() NotificationLevel {
	if x != nil {
		return x.Level
	}
	return NotificationLevel_NOTIFICATION_LEVEL_UNSPECIFIED
}

func (x *GetRoomNotificationPreferenceResponse) GetEffectiveLevel() NotificationLevel {
	if x != nil {
		return x.EffectiveLevel
	}
	return NotificationLevel_NOTIFICATION_LEVEL_UNSPECIFIED
}

// Updated notification preference for a room.
//
// The response mirrors the read shape so clients can update local state without
// issuing a second read request.
type SetRoomNotificationLevelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit level stored for the current user and room.
	Level NotificationLevel `protobuf:"varint,1,opt,name=level,proto3,enum=chatto.api.v1.NotificationLevel" json:"level,omitempty"`
	// Level after applying defaults and inheritance.
	EffectiveLevel NotificationLevel `protobuf:"varint,2,opt,name=effective_level,json=effectiveLevel,proto3,enum=chatto.api.v1.NotificationLevel" json:"effective_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetRoomNotificationLevelResponse) Reset() {
	*x = SetRoomNotificationLevelResponse{}
	mi := &file_chatto_api_v1_notification_preferences_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoomNotificationLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomNotificationLevelResponse) ProtoMessage() {}

func (x *SetRoomNotificationLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_notification_preferences_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomNotificationLevelResponse.ProtoReflect.Descriptor instead.
func (*SetRoomNotificationLevelResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_notification_preferences_proto_rawDescGZIP(), []int{1}
}

func (x *SetRoomNotificationLevelResponse) GetLevel() NotificationLevel {
	if x != nil {
		return x.Level
	}
	return NotificationLevel_NOTIFICATION_LEVEL_UNSPECIFIED
}

func (x *SetRoomNotificationLevelResponse) GetEffectiveLevel() NotificationLevel {
	if x != nil {
		return x.EffectiveLevel
	}
	return NotificationLevel_NOTIFICATION_LEVEL_UNSPECIFIED
}

// Request for the current user's notification preference in one room.
type GetRoomNotificationPreferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room whose notification preference should be loaded for the current user.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomNotificationPreferenceRequest) Reset() {
	*x = GetRoomNotificationPreferenceRequest{}
	mi := &file_chatto_api_v1_notification_preferences_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomNotificationPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomNotificationPreferenceRequest) ProtoMessage() {}

func (x *GetRoomNotificationPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_notification_preferences_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomNotificationPreferenceRequest.ProtoReflect.Descriptor instead.
func (*GetRoomNotificationPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_notification_preferences_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomNotificationPreferenceRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Request to update the current user's notification level in one room.
type SetRoomNotificationLevelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room whose notification level should be changed for the current user.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. New explicit notification level. Use NOTIFICATION_LEVEL_DEFAULT
	// to return the room to inherited/default behavior.
	Level         NotificationLevel `protobuf:"varint,2,opt,name=level,proto3,enum=chatto.api.v1.NotificationLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoomNotificationLevelRequest) Reset() {
	*x = SetRoomNotificationLevelRequest{}
	mi := &file_chatto_api_v1_notification_preferences_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoomNotificationLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomNotificationLevelRequest) ProtoMessage() {}

func (x *SetRoomNotificationLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_notification_preferences_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomNotificationLevelRequest.ProtoReflect.Descriptor instead.
func (*SetRoomNotificationLevelRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_notification_preferences_proto_rawDescGZIP(), []int{3}
}

func (x *SetRoomNotificationLevelRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetRoomNotificationLevelRequest) GetLevel() NotificationLevel {
	if x != nil {
		return x.Level
	}
	return NotificationLevel_NOTIFICATION_LEVEL_UNSPECIFIED
}

var File_chatto_api_v1_notification_preferences_proto protoreflect.FileDescriptor

const file_chatto_api_v1_notification_preferences_proto_rawDesc = "" +
	"\n" +
	",chatto/api/v1/notification_preferences.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\"\xaa\x01\n" +
	"%GetRoomNotificationPreferenceResponse\x126\n" +
	"\x05level\x18\x01 \x01(\x0e2 .chatto.api.v1.NotificationLevelR\x05level\x12I\n" +
	"\x0feffective_level\x18\x02 \x01(\x0e2 .chatto.api.v1.NotificationLevelR\x0eeffectiveLevel\"\xa5\x01\n" +
	" SetRoomNotificationLevelResponse\x126\n" +
	"\x05level\x18\x01 \x01(\x0e2 .chatto.api.v1.NotificationLevelR\x05level\x12I\n" +
	"\x0feffective_level\x18\x02 \x01(\x0e2 .chatto.api.v1.NotificationLevelR\x0eeffectiveLevel\"H\n" +
	"$GetRoomNotificationPreferenceRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"\x87\x01\n" +
	"\x1fSetRoomNotificationLevelRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12B\n" +
	"\x05level\x18\x02 \x01(\x0e2 .chatto.api.v1.NotificationLevelB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05level*\xb9\x01\n" +
	"\x11NotificationLevel\x12\"\n" +
	"\x1eNOTIFICATION_LEVEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_LEVEL_DEFAULT\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_LEVEL_MUTED\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_LEVEL_NORMAL\x10\x03\x12#\n" +
	"\x1fNOTIFICATION_LEVEL_ALL_MESSAGES\x10\x042\xaa\x02\n" +
	"\x1eNotificationPreferencesService\x12\x8a\x01\n" +
	"\x1dGetRoomNotificationPreference\x123.chatto.api.v1.GetRoomNotificationPreferenceRequest\x1a4.chatto.api.v1.GetRoomNotificationPreferenceResponse\x12{\n" +
	"\x18SetRoomNotificationLevel\x12..chatto.api.v1.SetRoomNotificationLevelRequest\x1a/.chatto.api.v1.SetRoomNotificationLevelResponseB\xb8\x01\n" +
	"\x11com.chatto.api.v1B\x1cNotificationPreferencesProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_notification_preferences_proto_rawDescOnce sync.Once
	file_chatto_api_v1_notification_preferences_proto_rawDescData []byte
)

func file_chatto_api_v1_notification_preferences_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_notification_preferences_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_notification_preferences_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_notification_preferences_proto_rawDesc), len(file_chatto_api_v1_notification_preferences_proto_rawDesc)))
	})
	return file_chatto_api_v1_notification_preferences_proto_rawDescData
}

var file_chatto_api_v1_notification_preferences_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_notification_preferences_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chatto_api_v1_notification_preferences_proto_goTypes = []any{
	(NotificationLevel)(0),                        // 0: chatto.api.v1.NotificationLevel
	(*GetRoomNotificationPreferenceResponse)(nil), // 1: chatto.api.v1.GetRoomNotificationPreferenceResponse
	(*SetRoomNotificationLevelResponse)(nil),      // 2: chatto.api.v1.SetRoomNotificationLevelResponse
	(*GetRoomNotificationPreferenceRequest)(nil),  // 3: chatto.api.v1.GetRoomNotificationPreferenceRequest
	(*SetRoomNotificationLevelRequest)(nil),       // 4: chatto.api.v1.SetRoomNotificationLevelRequest
}
var file_chatto_api_v1_notification_preferences_proto_depIdxs = []int32{
	0, // 0: chatto.api.v1.GetRoomNotificationPreferenceResponse.level:type_name -> chatto.api.v1.NotificationLevel
	0, // 1: chatto.api.v1.GetRoomNotificationPreferenceResponse.effective_level:type_name -> chatto.api.v1.NotificationLevel
	0, // 2: chatto.api.v1.SetRoomNotificationLevelResponse.level:type_name -> chatto.api.v1.NotificationLevel
	0, // 3: chatto.api.v1.SetRoomNotificationLevelResponse.effective_level:type_name -> chatto.api.v1.NotificationLevel
	0, // 4: chatto.api.v1.SetRoomNotificationLevelRequest.level:type_name -> chatto.api.v1.NotificationLevel
	3, // 5: chatto.api.v1.NotificationPreferencesService.GetRoomNotificationPreference:input_type -> chatto.api.v1.GetRoomNotificationPreferenceRequest
	4, // 6: chatto.api.v1.NotificationPreferencesService.SetRoomNotificationLevel:input_type -> chatto.api.v1.SetRoomNotificationLevelRequest
	1, // 7: chatto.api.v1.NotificationPreferencesService.GetRoomNotificationPreference:output_type -> chatto.api.v1.GetRoomNotificationPreferenceResponse
	2, // 8: chatto.api.v1.NotificationPreferencesService.SetRoomNotificationLevel:output_type -> chatto.api.v1.SetRoomNotificationLevelResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_notification_preferences_proto_init() }
func file_chatto_api_v1_notification_preferences_proto_init() {
	if File_chatto_api_v1_notification_preferences_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_notification_preferences_proto_rawDesc), len(file_chatto_api_v1_notification_preferences_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_notification_preferences_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_notification_preferences_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_notification_preferences_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_notification_preferences_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_notification_preferences_proto = out.File
	file_chatto_api_v1_notification_preferences_proto_goTypes = nil
	file_chatto_api_v1_notification_preferences_proto_depIdxs = nil
}
