// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/rooms.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind of room represented by the public API.
type RoomKind int32

const (
	// The room kind was not specified.
	RoomKind_ROOM_KIND_UNSPECIFIED RoomKind = 0
	// A regular channel governed by server and room permissions.
	RoomKind_ROOM_KIND_CHANNEL RoomKind = 1
	// A direct-message conversation between members.
	RoomKind_ROOM_KIND_DM RoomKind = 2
)

// Enum value maps for RoomKind.
var (
	RoomKind_name = map[int32]string{
		0: "ROOM_KIND_UNSPECIFIED",
		1: "ROOM_KIND_CHANNEL",
		2: "ROOM_KIND_DM",
	}
	RoomKind_value = map[string]int32{
		"ROOM_KIND_UNSPECIFIED": 0,
		"ROOM_KIND_CHANNEL":     1,
		"ROOM_KIND_DM":          2,
	}
)

func (x RoomKind) Enum() *RoomKind {
	p := new(RoomKind)
	*p = x
	return p
}

func (x RoomKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_rooms_proto_enumTypes[0].Descriptor()
}

func (RoomKind) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_rooms_proto_enumTypes[0]
}

func (x RoomKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomKind.Descriptor instead.
func (RoomKind) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{0}
}

// Public room metadata returned by room commands.
type Room struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable room ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Room kind.
	Kind RoomKind `protobuf:"varint,2,opt,name=kind,proto3,enum=chatto.api.v1.RoomKind" json:"kind,omitempty"`
	// Room name. Direct-message rooms may have an empty name because clients
	// derive their display label from participants.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Optional room description.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// True when the room is archived and hidden from active room lists.
	Archived bool `protobuf:"varint,5,opt,name=archived,proto3" json:"archived,omitempty"`
	// Room group ID for channel rooms. Empty for direct-message rooms.
	GroupId string `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// True when a channel grants effective membership to eligible server members.
	Universal     bool `protobuf:"varint,7,opt,name=universal,proto3" json:"universal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetKind() RoomKind {
	if x != nil {
		return x.Kind
	}
	return RoomKind_ROOM_KIND_UNSPECIFIED
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Room) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Room) GetUniversal() bool {
	if x != nil {
		return x.Universal
	}
	return false
}

// Request to create a channel room.
type CreateRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Name of the new channel room.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional room description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Required. Room group that should contain the new channel.
	GroupId string `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Whether the new channel should grant effective membership to eligible
	// server members.
	Universal     bool `protobuf:"varint,4,opt,name=universal,proto3" json:"universal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoomRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateRoomRequest) GetUniversal() bool {
	if x != nil {
		return x.Universal
	}
	return false
}

// Result of creating a room.
type CreateRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to update a room's editable metadata.
type UpdateRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to update.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. New room name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional new room description.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Result of updating a room.
type UpdateRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to archive a room.
type ArchiveRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to archive.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRoomRequest) Reset() {
	*x = ArchiveRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRoomRequest) ProtoMessage() {}

func (x *ArchiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRoomRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Result of archiving a room.
type ArchiveRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Archived room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRoomResponse) Reset() {
	*x = ArchiveRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRoomResponse) ProtoMessage() {}

func (x *ArchiveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRoomResponse.ProtoReflect.Descriptor instead.
func (*ArchiveRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{6}
}

func (x *ArchiveRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to unarchive a room.
type UnarchiveRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to unarchive.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveRoomRequest) Reset() {
	*x = UnarchiveRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveRoomRequest) ProtoMessage() {}

func (x *UnarchiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveRoomRequest.ProtoReflect.Descriptor instead.
func (*UnarchiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{7}
}

func (x *UnarchiveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Result of unarchiving a room.
type UnarchiveRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unarchived room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveRoomResponse) Reset() {
	*x = UnarchiveRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveRoomResponse) ProtoMessage() {}

func (x *UnarchiveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveRoomResponse.ProtoReflect.Descriptor instead.
func (*UnarchiveRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{8}
}

func (x *UnarchiveRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to change a channel room's universal membership flag.
type SetRoomUniversalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Channel room to update.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// New universal membership state.
	Universal     bool `protobuf:"varint,2,opt,name=universal,proto3" json:"universal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoomUniversalRequest) Reset() {
	*x = SetRoomUniversalRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoomUniversalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomUniversalRequest) ProtoMessage() {}

func (x *SetRoomUniversalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomUniversalRequest.ProtoReflect.Descriptor instead.
func (*SetRoomUniversalRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{9}
}

func (x *SetRoomUniversalRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetRoomUniversalRequest) GetUniversal() bool {
	if x != nil {
		return x.Universal
	}
	return false
}

// Result of changing a channel room's universal membership flag.
type SetRoomUniversalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoomUniversalResponse) Reset() {
	*x = SetRoomUniversalResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoomUniversalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomUniversalResponse) ProtoMessage() {}

func (x *SetRoomUniversalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomUniversalResponse.ProtoReflect.Descriptor instead.
func (*SetRoomUniversalResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{10}
}

func (x *SetRoomUniversalResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to join a room as the current user.
type JoinRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to join.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{11}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Result of joining a room.
type JoinRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Joined room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{12}
}

func (x *JoinRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to leave a room as the current user.
type LeaveRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to leave.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{13}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Result of leaving a room.
type LeaveRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the current user is no longer an explicit member after the call.
	Left          bool `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{14}
}

func (x *LeaveRoomResponse) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

// Request to ban a member from a channel room.
type BanRoomMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Channel room to ban the user from.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. User to ban from the room.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Required moderator-entered reason stored for audit.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional future time when the ban expires.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanRoomMemberRequest) Reset() {
	*x = BanRoomMemberRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanRoomMemberRequest) ProtoMessage() {}

func (x *BanRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*BanRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{15}
}

func (x *BanRoomMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BanRoomMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanRoomMemberRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanRoomMemberRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Result of banning a room member.
type BanRoomMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the ban operation completed.
	Banned        bool `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanRoomMemberResponse) Reset() {
	*x = BanRoomMemberResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanRoomMemberResponse) ProtoMessage() {}

func (x *BanRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*BanRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{16}
}

func (x *BanRoomMemberResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

// Request to remove a channel room ban.
type UnbanRoomMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Channel room to unban the user from.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. User to unban.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Required moderator-entered reason stored for audit.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanRoomMemberRequest) Reset() {
	*x = UnbanRoomMemberRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanRoomMemberRequest) ProtoMessage() {}

func (x *UnbanRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*UnbanRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{17}
}

func (x *UnbanRoomMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UnbanRoomMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnbanRoomMemberRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Result of removing a room ban.
type UnbanRoomMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the unban operation completed.
	Unbanned      bool `protobuf:"varint,1,opt,name=unbanned,proto3" json:"unbanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanRoomMemberResponse) Reset() {
	*x = UnbanRoomMemberResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanRoomMemberResponse) ProtoMessage() {}

func (x *UnbanRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*UnbanRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{18}
}

func (x *UnbanRoomMemberResponse) GetUnbanned() bool {
	if x != nil {
		return x.Unbanned
	}
	return false
}

var File_chatto_api_v1_rooms_proto protoreflect.FileDescriptor

const file_chatto_api_v1_rooms_proto_rawDesc = "" +
	"\n" +
	"\x19chatto/api/v1/rooms.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x17.chatto.api.v1.RoomKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\barchived\x18\x05 \x01(\bR\barchived\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12\x1c\n" +
	"\tuniversal\x18\a \x01(\bR\tuniversal\"\xa0\x01\n" +
	"\x11CreateRoomRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x1eR\x04name\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\vdescription\x12\"\n" +
	"\bgroup_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\agroupId\x12\x1c\n" +
	"\tuniversal\x18\x04 \x01(\bR\tuniversal\"=\n" +
	"\x12CreateRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"\x80\x01\n" +
	"\x11UpdateRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x1eR\x04name\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\vdescription\"=\n" +
	"\x12UpdateRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"6\n" +
	"\x12ArchiveRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\">\n" +
	"\x13ArchiveRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"8\n" +
	"\x14UnarchiveRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"@\n" +
	"\x15UnarchiveRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"Y\n" +
	"\x17SetRoomUniversalRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12\x1c\n" +
	"\tuniversal\x18\x02 \x01(\bR\tuniversal\"C\n" +
	"\x18SetRoomUniversalResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"3\n" +
	"\x0fJoinRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\";\n" +
	"\x10JoinRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"4\n" +
	"\x10LeaveRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"'\n" +
	"\x11LeaveRoomResponse\x12\x12\n" +
	"\x04left\x18\x01 \x01(\bR\x04left\"\xb9\x01\n" +
	"\x14BanRoomMemberRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12\"\n" +
	"\x06reason\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xe8\aR\x06reason\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"/\n" +
	"\x15BanRoomMemberResponse\x12\x16\n" +
	"\x06banned\x18\x01 \x01(\bR\x06banned\"\x80\x01\n" +
	"\x16UnbanRoomMemberRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12\"\n" +
	"\x06reason\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xe8\aR\x06reason\"5\n" +
	"\x17UnbanRoomMemberResponse\x12\x1a\n" +
	"\bunbanned\x18\x01 \x01(\bR\bunbanned*N\n" +
	"\bRoomKind\x12\x19\n" +
	"\x15ROOM_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ROOM_KIND_CHANNEL\x10\x01\x12\x10\n" +
	"\fROOM_KIND_DM\x10\x022\xa5\x06\n" +
	"\vRoomService\x12Q\n" +
	"\n" +
	"CreateRoom\x12 .chatto.api.v1.CreateRoomRequest\x1a!.chatto.api.v1.CreateRoomResponse\x12Q\n" +
	"\n" +
	"UpdateRoom\x12 .chatto.api.v1.UpdateRoomRequest\x1a!.chatto.api.v1.UpdateRoomResponse\x12T\n" +
	"\vArchiveRoom\x12!.chatto.api.v1.ArchiveRoomRequest\x1a\".chatto.api.v1.ArchiveRoomResponse\x12Z\n" +
	"\rUnarchiveRoom\x12#.chatto.api.v1.UnarchiveRoomRequest\x1a$.chatto.api.v1.UnarchiveRoomResponse\x12c\n" +
	"\x10SetRoomUniversal\x12&.chatto.api.v1.SetRoomUniversalRequest\x1a'.chatto.api.v1.SetRoomUniversalResponse\x12K\n" +
	"\bJoinRoom\x12\x1e.chatto.api.v1.JoinRoomRequest\x1a\x1f.chatto.api.v1.JoinRoomResponse\x12N\n" +
	"\tLeaveRoom\x12\x1f.chatto.api.v1.LeaveRoomRequest\x1a .chatto.api.v1.LeaveRoomResponse\x12Z\n" +
	"\rBanRoomMember\x12#.chatto.api.v1.BanRoomMemberRequest\x1a$.chatto.api.v1.BanRoomMemberResponse\x12`\n" +
	"\x0fUnbanRoomMember\x12%.chatto.api.v1.UnbanRoomMemberRequest\x1a&.chatto.api.v1.UnbanRoomMemberResponseB\xa6\x01\n" +
	"\x11com.chatto.api.v1B\n" +
	"RoomsProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_rooms_proto_rawDescOnce sync.Once
	file_chatto_api_v1_rooms_proto_rawDescData []byte
)

func file_chatto_api_v1_rooms_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_rooms_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_rooms_proto_rawDesc), len(file_chatto_api_v1_rooms_proto_rawDesc)))
	})
	return file_chatto_api_v1_rooms_proto_rawDescData
}

var file_chatto_api_v1_rooms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_chatto_api_v1_rooms_proto_goTypes = []any{
	(RoomKind)(0),                    // 0: chatto.api.v1.RoomKind
	(*Room)(nil),                     // 1: chatto.api.v1.Room
	(*CreateRoomRequest)(nil),        // 2: chatto.api.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),       // 3: chatto.api.v1.CreateRoomResponse
	(*UpdateRoomRequest)(nil),        // 4: chatto.api.v1.UpdateRoomRequest
	(*UpdateRoomResponse)(nil),       // 5: chatto.api.v1.UpdateRoomResponse
	(*ArchiveRoomRequest)(nil),       // 6: chatto.api.v1.ArchiveRoomRequest
	(*ArchiveRoomResponse)(nil),      // 7: chatto.api.v1.ArchiveRoomResponse
	(*UnarchiveRoomRequest)(nil),     // 8: chatto.api.v1.UnarchiveRoomRequest
	(*UnarchiveRoomResponse)(nil),    // 9: chatto.api.v1.UnarchiveRoomResponse
	(*SetRoomUniversalRequest)(nil),  // 10: chatto.api.v1.SetRoomUniversalRequest
	(*SetRoomUniversalResponse)(nil), // 11: chatto.api.v1.SetRoomUniversalResponse
	(*JoinRoomRequest)(nil),          // 12: chatto.api.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),         // 13: chatto.api.v1.JoinRoomResponse
	(*LeaveRoomRequest)(nil),         // 14: chatto.api.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),        // 15: chatto.api.v1.LeaveRoomResponse
	(*BanRoomMemberRequest)(nil),     // 16: chatto.api.v1.BanRoomMemberRequest
	(*BanRoomMemberResponse)(nil),    // 17: chatto.api.v1.BanRoomMemberResponse
	(*UnbanRoomMemberRequest)(nil),   // 18: chatto.api.v1.UnbanRoomMemberRequest
	(*UnbanRoomMemberResponse)(nil),  // 19: chatto.api.v1.UnbanRoomMemberResponse
	(*timestamppb.Timestamp)(nil),    // 20: google.protobuf.Timestamp
}
var file_chatto_api_v1_rooms_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.Room.kind:type_name -> chatto.api.v1.RoomKind
	1,  // 1: chatto.api.v1.CreateRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 2: chatto.api.v1.UpdateRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 3: chatto.api.v1.ArchiveRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 4: chatto.api.v1.UnarchiveRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 5: chatto.api.v1.SetRoomUniversalResponse.room:type_name -> chatto.api.v1.Room
	1,  // 6: chatto.api.v1.JoinRoomResponse.room:type_name -> chatto.api.v1.Room
	20, // 7: chatto.api.v1.BanRoomMemberRequest.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 8: chatto.api.v1.RoomService.CreateRoom:input_type -> chatto.api.v1.CreateRoomRequest
	4,  // 9: chatto.api.v1.RoomService.UpdateRoom:input_type -> chatto.api.v1.UpdateRoomRequest
	6,  // 10: chatto.api.v1.RoomService.ArchiveRoom:input_type -> chatto.api.v1.ArchiveRoomRequest
	8,  // 11: chatto.api.v1.RoomService.UnarchiveRoom:input_type -> chatto.api.v1.UnarchiveRoomRequest
	10, // 12: chatto.api.v1.RoomService.SetRoomUniversal:input_type -> chatto.api.v1.SetRoomUniversalRequest
	12, // 13: chatto.api.v1.RoomService.JoinRoom:input_type -> chatto.api.v1.JoinRoomRequest
	14, // 14: chatto.api.v1.RoomService.LeaveRoom:input_type -> chatto.api.v1.LeaveRoomRequest
	16, // 15: chatto.api.v1.RoomService.BanRoomMember:input_type -> chatto.api.v1.BanRoomMemberRequest
	18, // 16: chatto.api.v1.RoomService.UnbanRoomMember:input_type -> chatto.api.v1.UnbanRoomMemberRequest
	3,  // 17: chatto.api.v1.RoomService.CreateRoom:output_type -> chatto.api.v1.CreateRoomResponse
	5,  // 18: chatto.api.v1.RoomService.UpdateRoom:output_type -> chatto.api.v1.UpdateRoomResponse
	7,  // 19: chatto.api.v1.RoomService.ArchiveRoom:output_type -> chatto.api.v1.ArchiveRoomResponse
	9,  // 20: chatto.api.v1.RoomService.UnarchiveRoom:output_type -> chatto.api.v1.UnarchiveRoomResponse
	11, // 21: chatto.api.v1.RoomService.SetRoomUniversal:output_type -> chatto.api.v1.SetRoomUniversalResponse
	13, // 22: chatto.api.v1.RoomService.JoinRoom:output_type -> chatto.api.v1.JoinRoomResponse
	15, // 23: chatto.api.v1.RoomService.LeaveRoom:output_type -> chatto.api.v1.LeaveRoomResponse
	17, // 24: chatto.api.v1.RoomService.BanRoomMember:output_type -> chatto.api.v1.BanRoomMemberResponse
	19, // 25: chatto.api.v1.RoomService.UnbanRoomMember:output_type -> chatto.api.v1.UnbanRoomMemberResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_rooms_proto_init() }
func file_chatto_api_v1_rooms_proto_init() {
	if File_chatto_api_v1_rooms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_rooms_proto_rawDesc), len(file_chatto_api_v1_rooms_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_rooms_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_rooms_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_rooms_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_rooms_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_rooms_proto = out.File
	file_chatto_api_v1_rooms_proto_goTypes = nil
	file_chatto_api_v1_rooms_proto_depIdxs = nil
}
