// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/users.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fit mode used when generating transformed user avatar URLs.
type UserAvatarFitMode int32

const (
	// The fit mode was not specified.
	UserAvatarFitMode_USER_AVATAR_FIT_MODE_UNSPECIFIED UserAvatarFitMode = 0
	// Preserve the whole source image within the requested bounds.
	UserAvatarFitMode_USER_AVATAR_FIT_MODE_CONTAIN UserAvatarFitMode = 1
	// Fill the requested bounds, cropping when needed.
	UserAvatarFitMode_USER_AVATAR_FIT_MODE_COVER UserAvatarFitMode = 2
)

// Enum value maps for UserAvatarFitMode.
var (
	UserAvatarFitMode_name = map[int32]string{
		0: "USER_AVATAR_FIT_MODE_UNSPECIFIED",
		1: "USER_AVATAR_FIT_MODE_CONTAIN",
		2: "USER_AVATAR_FIT_MODE_COVER",
	}
	UserAvatarFitMode_value = map[string]int32{
		"USER_AVATAR_FIT_MODE_UNSPECIFIED": 0,
		"USER_AVATAR_FIT_MODE_CONTAIN":     1,
		"USER_AVATAR_FIT_MODE_COVER":       2,
	}
)

func (x UserAvatarFitMode) Enum() *UserAvatarFitMode {
	p := new(UserAvatarFitMode)
	*p = x
	return p
}

func (x UserAvatarFitMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAvatarFitMode) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_users_proto_enumTypes[0].Descriptor()
}

func (UserAvatarFitMode) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_users_proto_enumTypes[0]
}

func (x UserAvatarFitMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAvatarFitMode.Descriptor instead.
func (UserAvatarFitMode) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{0}
}

// Avatar transform parameters for user profile reads.
type UserAvatarOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Avatar width in pixels.
	Width int32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	// Avatar height in pixels.
	Height int32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// Avatar crop/fit behavior.
	Fit           UserAvatarFitMode `protobuf:"varint,3,opt,name=fit,proto3,enum=chatto.api.v1.UserAvatarFitMode" json:"fit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAvatarOptions) Reset() {
	*x = UserAvatarOptions{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAvatarOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAvatarOptions) ProtoMessage() {}

func (x *UserAvatarOptions) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAvatarOptions.ProtoReflect.Descriptor instead.
func (*UserAvatarOptions) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *UserAvatarOptions) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserAvatarOptions) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserAvatarOptions) GetFit() UserAvatarFitMode {
	if x != nil {
		return x.Fit
	}
	return UserAvatarFitMode_USER_AVATAR_FIT_MODE_UNSPECIFIED
}

// Lightweight public user data for cache-backed render surfaces.
type UserSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable user ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Login name.
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	// Display name, when set.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// True when the user account has been deleted.
	Deleted bool `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// Avatar image URL, when available.
	AvatarUrl     *string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSummary) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserSummary) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserSummary) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *UserSummary) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// Lightweight public user data plus live profile state.
type UserPresenceSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public identity fields.
	User *UserSummary `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Current live presence status.
	PresenceStatus PresenceStatus `protobuf:"varint,2,opt,name=presence_status,json=presenceStatus,proto3,enum=chatto.api.v1.PresenceStatus" json:"presence_status,omitempty"`
	// Custom profile status, when set.
	CustomStatus  *CustomUserStatus `protobuf:"bytes,3,opt,name=custom_status,json=customStatus,proto3" json:"custom_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPresenceSummary) Reset() {
	*x = UserPresenceSummary{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPresenceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPresenceSummary) ProtoMessage() {}

func (x *UserPresenceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPresenceSummary.ProtoReflect.Descriptor instead.
func (*UserPresenceSummary) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *UserPresenceSummary) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserPresenceSummary) GetPresenceStatus() PresenceStatus {
	if x != nil {
		return x.PresenceStatus
	}
	return PresenceStatus_PRESENCE_STATUS_UNSPECIFIED
}

func (x *UserPresenceSummary) GetCustomStatus() *CustomUserStatus {
	if x != nil {
		return x.CustomStatus
	}
	return nil
}

// Request one user by stable user ID.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional avatar URL transform parameters. Omit for the original avatar URL.
	Avatar        *UserAvatarOptions `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRequest) GetAvatar() *UserAvatarOptions {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// Request one user by login identifier.
type GetUserByLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required login identifier.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Optional avatar URL transform parameters. Omit for the original avatar URL.
	Avatar        *UserAvatarOptions `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByLoginRequest) Reset() {
	*x = GetUserByLoginRequest{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByLoginRequest) ProtoMessage() {}

func (x *GetUserByLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByLoginRequest.ProtoReflect.Descriptor instead.
func (*GetUserByLoginRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserByLoginRequest) GetAvatar() *UserAvatarOptions {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// Request lightweight summaries for a set of stable user IDs.
type BatchGetUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required user IDs. Unknown IDs are omitted from the response.
	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	// Optional avatar URL transform parameters. Omit for the original avatar URL.
	Avatar        *UserAvatarOptions `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersRequest) Reset() {
	*x = BatchGetUsersRequest{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersRequest) ProtoMessage() {}

func (x *BatchGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *BatchGetUsersRequest) GetAvatar() *UserAvatarOptions {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// Public authenticated user profile response.
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested user.
	User          *UserPresenceSummary `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserResponse) GetUser() *UserPresenceSummary {
	if x != nil {
		return x.User
	}
	return nil
}

// Public authenticated user profile response for login lookup.
type GetUserByLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested user.
	User          *UserPresenceSummary `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByLoginResponse) Reset() {
	*x = GetUserByLoginResponse{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByLoginResponse) ProtoMessage() {}

func (x *GetUserByLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByLoginResponse.ProtoReflect.Descriptor instead.
func (*GetUserByLoginResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByLoginResponse) GetUser() *UserPresenceSummary {
	if x != nil {
		return x.User
	}
	return nil
}

// Lightweight batch user summary response.
type BatchGetUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found users. The server preserves first-seen request order and de-duplicates
	// repeated IDs.
	Users         []*UserSummary `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersResponse) Reset() {
	*x = BatchGetUsersResponse{}
	mi := &file_chatto_api_v1_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersResponse) ProtoMessage() {}

func (x *BatchGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_users_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetUsersResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_chatto_api_v1_users_proto protoreflect.FileDescriptor

const file_chatto_api_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x19chatto/api/v1/users.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cchatto/api/v1/presence.proto\x1a\x1fchatto/api/v1/user_status.proto\"\x97\x01\n" +
	"\x11UserAvatarOptions\x12 \n" +
	"\x05width\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x80 (\x01R\x05width\x12\"\n" +
	"\x06height\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x80 (\x01R\x06height\x12<\n" +
	"\x03fit\x18\x03 \x01(\x0e2 .chatto.api.v1.UserAvatarFitModeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x03fit\"\xa3\x01\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x00R\tavatarUrl\x88\x01\x01B\r\n" +
	"\v_avatar_url\"\xd3\x01\n" +
	"\x13UserPresenceSummary\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.chatto.api.v1.UserSummaryR\x04user\x12F\n" +
	"\x0fpresence_status\x18\x02 \x01(\x0e2\x1d.chatto.api.v1.PresenceStatusR\x0epresenceStatus\x12D\n" +
	"\rcustom_status\x18\x03 \x01(\v2\x1f.chatto.api.v1.CustomUserStatusR\fcustomStatus\"l\n" +
	"\x0eGetUserRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x128\n" +
	"\x06avatar\x18\x02 \x01(\v2 .chatto.api.v1.UserAvatarOptionsR\x06avatar\"p\n" +
	"\x15GetUserByLoginRequest\x12\x1d\n" +
	"\x05login\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05login\x128\n" +
	"\x06avatar\x18\x02 \x01(\v2 .chatto.api.v1.UserAvatarOptionsR\x06avatar\"}\n" +
	"\x14BatchGetUsersRequest\x12+\n" +
	"\buser_ids\x18\x01 \x03(\tB\x10\xbaH\r\x92\x01\n" +
	"\b\x01\x10d\"\x04r\x02\x10\x01R\auserIds\x128\n" +
	"\x06avatar\x18\x02 \x01(\v2 .chatto.api.v1.UserAvatarOptionsR\x06avatar\"I\n" +
	"\x0fGetUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".chatto.api.v1.UserPresenceSummaryR\x04user\"P\n" +
	"\x16GetUserByLoginResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".chatto.api.v1.UserPresenceSummaryR\x04user\"I\n" +
	"\x15BatchGetUsersResponse\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.chatto.api.v1.UserSummaryR\x05users*{\n" +
	"\x11UserAvatarFitMode\x12$\n" +
	" USER_AVATAR_FIT_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cUSER_AVATAR_FIT_MODE_CONTAIN\x10\x01\x12\x1e\n" +
	"\x1aUSER_AVATAR_FIT_MODE_COVER\x10\x022\x92\x02\n" +
	"\vUserService\x12H\n" +
	"\aGetUser\x12\x1d.chatto.api.v1.GetUserRequest\x1a\x1e.chatto.api.v1.GetUserResponse\x12]\n" +
	"\x0eGetUserByLogin\x12$.chatto.api.v1.GetUserByLoginRequest\x1a%.chatto.api.v1.GetUserByLoginResponse\x12Z\n" +
	"\rBatchGetUsers\x12#.chatto.api.v1.BatchGetUsersRequest\x1a$.chatto.api.v1.BatchGetUsersResponseB\xa6\x01\n" +
	"\x11com.chatto.api.v1B\n" +
	"UsersProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_users_proto_rawDescOnce sync.Once
	file_chatto_api_v1_users_proto_rawDescData []byte
)

func file_chatto_api_v1_users_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_users_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_users_proto_rawDesc), len(file_chatto_api_v1_users_proto_rawDesc)))
	})
	return file_chatto_api_v1_users_proto_rawDescData
}

var file_chatto_api_v1_users_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chatto_api_v1_users_proto_goTypes = []any{
	(UserAvatarFitMode)(0),         // 0: chatto.api.v1.UserAvatarFitMode
	(*UserAvatarOptions)(nil),      // 1: chatto.api.v1.UserAvatarOptions
	(*UserSummary)(nil),            // 2: chatto.api.v1.UserSummary
	(*UserPresenceSummary)(nil),    // 3: chatto.api.v1.UserPresenceSummary
	(*GetUserRequest)(nil),         // 4: chatto.api.v1.GetUserRequest
	(*GetUserByLoginRequest)(nil),  // 5: chatto.api.v1.GetUserByLoginRequest
	(*BatchGetUsersRequest)(nil),   // 6: chatto.api.v1.BatchGetUsersRequest
	(*GetUserResponse)(nil),        // 7: chatto.api.v1.GetUserResponse
	(*GetUserByLoginResponse)(nil), // 8: chatto.api.v1.GetUserByLoginResponse
	(*BatchGetUsersResponse)(nil),  // 9: chatto.api.v1.BatchGetUsersResponse
	(PresenceStatus)(0),            // 10: chatto.api.v1.PresenceStatus
	(*CustomUserStatus)(nil),       // 11: chatto.api.v1.CustomUserStatus
}
var file_chatto_api_v1_users_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.UserAvatarOptions.fit:type_name -> chatto.api.v1.UserAvatarFitMode
	2,  // 1: chatto.api.v1.UserPresenceSummary.user:type_name -> chatto.api.v1.UserSummary
	10, // 2: chatto.api.v1.UserPresenceSummary.presence_status:type_name -> chatto.api.v1.PresenceStatus
	11, // 3: chatto.api.v1.UserPresenceSummary.custom_status:type_name -> chatto.api.v1.CustomUserStatus
	1,  // 4: chatto.api.v1.GetUserRequest.avatar:type_name -> chatto.api.v1.UserAvatarOptions
	1,  // 5: chatto.api.v1.GetUserByLoginRequest.avatar:type_name -> chatto.api.v1.UserAvatarOptions
	1,  // 6: chatto.api.v1.BatchGetUsersRequest.avatar:type_name -> chatto.api.v1.UserAvatarOptions
	3,  // 7: chatto.api.v1.GetUserResponse.user:type_name -> chatto.api.v1.UserPresenceSummary
	3,  // 8: chatto.api.v1.GetUserByLoginResponse.user:type_name -> chatto.api.v1.UserPresenceSummary
	2,  // 9: chatto.api.v1.BatchGetUsersResponse.users:type_name -> chatto.api.v1.UserSummary
	4,  // 10: chatto.api.v1.UserService.GetUser:input_type -> chatto.api.v1.GetUserRequest
	5,  // 11: chatto.api.v1.UserService.GetUserByLogin:input_type -> chatto.api.v1.GetUserByLoginRequest
	6,  // 12: chatto.api.v1.UserService.BatchGetUsers:input_type -> chatto.api.v1.BatchGetUsersRequest
	7,  // 13: chatto.api.v1.UserService.GetUser:output_type -> chatto.api.v1.GetUserResponse
	8,  // 14: chatto.api.v1.UserService.GetUserByLogin:output_type -> chatto.api.v1.GetUserByLoginResponse
	9,  // 15: chatto.api.v1.UserService.BatchGetUsers:output_type -> chatto.api.v1.BatchGetUsersResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_users_proto_init() }
func file_chatto_api_v1_users_proto_init() {
	if File_chatto_api_v1_users_proto != nil {
		return
	}
	file_chatto_api_v1_presence_proto_init()
	file_chatto_api_v1_user_status_proto_init()
	file_chatto_api_v1_users_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_users_proto_rawDesc), len(file_chatto_api_v1_users_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_users_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_users_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_users_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_users_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_users_proto = out.File
	file_chatto_api_v1_users_proto_goTypes = nil
	file_chatto_api_v1_users_proto_depIdxs = nil
}
