// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/voice_calls.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for active channel call room IDs.
type ListActiveCallRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveCallRoomsRequest) Reset() {
	*x = ListActiveCallRoomsRequest{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveCallRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveCallRoomsRequest) ProtoMessage() {}

func (x *ListActiveCallRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveCallRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveCallRoomsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{0}
}

// Active channel call room IDs.
type ListActiveCallRoomsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room IDs with active calls.
	RoomIds       []string `protobuf:"bytes,1,rep,name=room_ids,json=roomIds,proto3" json:"room_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveCallRoomsResponse) Reset() {
	*x = ListActiveCallRoomsResponse{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveCallRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveCallRoomsResponse) ProtoMessage() {}

func (x *ListActiveCallRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveCallRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveCallRoomsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{1}
}

func (x *ListActiveCallRoomsResponse) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

// Request for participants in a room call.
type ListCallParticipantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room whose active call should be inspected.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallParticipantsRequest) Reset() {
	*x = ListCallParticipantsRequest{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallParticipantsRequest) ProtoMessage() {}

func (x *ListCallParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallParticipantsRequest.ProtoReflect.Descriptor instead.
func (*ListCallParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{2}
}

func (x *ListCallParticipantsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Participants in one room call.
type ListCallParticipantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Participants currently projected for the room call.
	Participants  []*CallParticipant `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallParticipantsResponse) Reset() {
	*x = ListCallParticipantsResponse{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallParticipantsResponse) ProtoMessage() {}

func (x *ListCallParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallParticipantsResponse.ProtoReflect.Descriptor instead.
func (*ListCallParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{3}
}

func (x *ListCallParticipantsResponse) GetParticipants() []*CallParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

// User currently participating in a room call.
type CallParticipant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Participant user.
	User *UserProfile `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// When the user joined this call.
	JoinedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	// Active call session ID.
	CallId        string `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallParticipant) Reset() {
	*x = CallParticipant{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallParticipant) ProtoMessage() {}

func (x *CallParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallParticipant.ProtoReflect.Descriptor instead.
func (*CallParticipant) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{4}
}

func (x *CallParticipant) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CallParticipant) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *CallParticipant) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// Request to record joining a room call.
type JoinCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room whose call is being joined.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCallRequest) Reset() {
	*x = JoinCallRequest{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCallRequest) ProtoMessage() {}

func (x *JoinCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCallRequest.ProtoReflect.Descriptor instead.
func (*JoinCallRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{5}
}

func (x *JoinCallRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Response from recording a join intent.
type JoinCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when a join fact was recorded.
	Joined        bool `protobuf:"varint,1,opt,name=joined,proto3" json:"joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCallResponse) Reset() {
	*x = JoinCallResponse{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCallResponse) ProtoMessage() {}

func (x *JoinCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCallResponse.ProtoReflect.Descriptor instead.
func (*JoinCallResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{6}
}

func (x *JoinCallResponse) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

// Request for a LiveKit token for a room call.
type GetCallTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room whose active call should be joined.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallTokenRequest) Reset() {
	*x = GetCallTokenRequest{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallTokenRequest) ProtoMessage() {}

func (x *GetCallTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallTokenRequest.ProtoReflect.Descriptor instead.
func (*GetCallTokenRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{7}
}

func (x *GetCallTokenRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// LiveKit token details for joining a room call.
type GetCallTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LiveKit JWT token.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Shared E2EE key for this active call.
	E2EeKey string `protobuf:"bytes,2,opt,name=e2ee_key,json=e2eeKey,proto3" json:"e2ee_key,omitempty"`
	// Active call session ID.
	CallId        string `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallTokenResponse) Reset() {
	*x = GetCallTokenResponse{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallTokenResponse) ProtoMessage() {}

func (x *GetCallTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallTokenResponse.ProtoReflect.Descriptor instead.
func (*GetCallTokenResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{8}
}

func (x *GetCallTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetCallTokenResponse) GetE2EeKey() string {
	if x != nil {
		return x.E2EeKey
	}
	return ""
}

func (x *GetCallTokenResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// Request to record leaving a room call.
type LeaveCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room whose call is being left.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCallRequest) Reset() {
	*x = LeaveCallRequest{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCallRequest) ProtoMessage() {}

func (x *LeaveCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCallRequest.ProtoReflect.Descriptor instead.
func (*LeaveCallRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveCallRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Response from recording a leave intent.
type LeaveCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when a leave fact was recorded.
	Left          bool `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCallResponse) Reset() {
	*x = LeaveCallResponse{}
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCallResponse) ProtoMessage() {}

func (x *LeaveCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_voice_calls_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCallResponse.ProtoReflect.Descriptor instead.
func (*LeaveCallResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_voice_calls_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveCallResponse) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

var File_chatto_api_v1_voice_calls_proto protoreflect.FileDescriptor

const file_chatto_api_v1_voice_calls_proto_rawDesc = "" +
	"\n" +
	"\x1fchatto/api/v1/voice_calls.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19chatto/api/v1/users.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\x1aListActiveCallRoomsRequest\"8\n" +
	"\x1bListActiveCallRoomsResponse\x12\x19\n" +
	"\broom_ids\x18\x01 \x03(\tR\aroomIds\"?\n" +
	"\x1bListCallParticipantsRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"b\n" +
	"\x1cListCallParticipantsResponse\x12B\n" +
	"\fparticipants\x18\x01 \x03(\v2\x1e.chatto.api.v1.CallParticipantR\fparticipants\"\x93\x01\n" +
	"\x0fCallParticipant\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.chatto.api.v1.UserProfileR\x04user\x127\n" +
	"\tjoined_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12\x17\n" +
	"\acall_id\x18\x03 \x01(\tR\x06callId\"3\n" +
	"\x0fJoinCallRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"*\n" +
	"\x10JoinCallResponse\x12\x16\n" +
	"\x06joined\x18\x01 \x01(\bR\x06joined\"7\n" +
	"\x13GetCallTokenRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"`\n" +
	"\x14GetCallTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\be2ee_key\x18\x02 \x01(\tR\ae2eeKey\x12\x17\n" +
	"\acall_id\x18\x03 \x01(\tR\x06callId\"4\n" +
	"\x10LeaveCallRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"'\n" +
	"\x11LeaveCallResponse\x12\x12\n" +
	"\x04left\x18\x01 \x01(\bR\x04left2\xe7\x03\n" +
	"\x10VoiceCallService\x12l\n" +
	"\x13ListActiveCallRooms\x12).chatto.api.v1.ListActiveCallRoomsRequest\x1a*.chatto.api.v1.ListActiveCallRoomsResponse\x12o\n" +
	"\x14ListCallParticipants\x12*.chatto.api.v1.ListCallParticipantsRequest\x1a+.chatto.api.v1.ListCallParticipantsResponse\x12K\n" +
	"\bJoinCall\x12\x1e.chatto.api.v1.JoinCallRequest\x1a\x1f.chatto.api.v1.JoinCallResponse\x12W\n" +
	"\fGetCallToken\x12\".chatto.api.v1.GetCallTokenRequest\x1a#.chatto.api.v1.GetCallTokenResponse\x12N\n" +
	"\tLeaveCall\x12\x1f.chatto.api.v1.LeaveCallRequest\x1a .chatto.api.v1.LeaveCallResponseB\xab\x01\n" +
	"\x11com.chatto.api.v1B\x0fVoiceCallsProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_voice_calls_proto_rawDescOnce sync.Once
	file_chatto_api_v1_voice_calls_proto_rawDescData []byte
)

func file_chatto_api_v1_voice_calls_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_voice_calls_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_voice_calls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_voice_calls_proto_rawDesc), len(file_chatto_api_v1_voice_calls_proto_rawDesc)))
	})
	return file_chatto_api_v1_voice_calls_proto_rawDescData
}

var file_chatto_api_v1_voice_calls_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chatto_api_v1_voice_calls_proto_goTypes = []any{
	(*ListActiveCallRoomsRequest)(nil),   // 0: chatto.api.v1.ListActiveCallRoomsRequest
	(*ListActiveCallRoomsResponse)(nil),  // 1: chatto.api.v1.ListActiveCallRoomsResponse
	(*ListCallParticipantsRequest)(nil),  // 2: chatto.api.v1.ListCallParticipantsRequest
	(*ListCallParticipantsResponse)(nil), // 3: chatto.api.v1.ListCallParticipantsResponse
	(*CallParticipant)(nil),              // 4: chatto.api.v1.CallParticipant
	(*JoinCallRequest)(nil),              // 5: chatto.api.v1.JoinCallRequest
	(*JoinCallResponse)(nil),             // 6: chatto.api.v1.JoinCallResponse
	(*GetCallTokenRequest)(nil),          // 7: chatto.api.v1.GetCallTokenRequest
	(*GetCallTokenResponse)(nil),         // 8: chatto.api.v1.GetCallTokenResponse
	(*LeaveCallRequest)(nil),             // 9: chatto.api.v1.LeaveCallRequest
	(*LeaveCallResponse)(nil),            // 10: chatto.api.v1.LeaveCallResponse
	(*UserProfile)(nil),                  // 11: chatto.api.v1.UserProfile
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
}
var file_chatto_api_v1_voice_calls_proto_depIdxs = []int32{
	4,  // 0: chatto.api.v1.ListCallParticipantsResponse.participants:type_name -> chatto.api.v1.CallParticipant
	11, // 1: chatto.api.v1.CallParticipant.user:type_name -> chatto.api.v1.UserProfile
	12, // 2: chatto.api.v1.CallParticipant.joined_at:type_name -> google.protobuf.Timestamp
	0,  // 3: chatto.api.v1.VoiceCallService.ListActiveCallRooms:input_type -> chatto.api.v1.ListActiveCallRoomsRequest
	2,  // 4: chatto.api.v1.VoiceCallService.ListCallParticipants:input_type -> chatto.api.v1.ListCallParticipantsRequest
	5,  // 5: chatto.api.v1.VoiceCallService.JoinCall:input_type -> chatto.api.v1.JoinCallRequest
	7,  // 6: chatto.api.v1.VoiceCallService.GetCallToken:input_type -> chatto.api.v1.GetCallTokenRequest
	9,  // 7: chatto.api.v1.VoiceCallService.LeaveCall:input_type -> chatto.api.v1.LeaveCallRequest
	1,  // 8: chatto.api.v1.VoiceCallService.ListActiveCallRooms:output_type -> chatto.api.v1.ListActiveCallRoomsResponse
	3,  // 9: chatto.api.v1.VoiceCallService.ListCallParticipants:output_type -> chatto.api.v1.ListCallParticipantsResponse
	6,  // 10: chatto.api.v1.VoiceCallService.JoinCall:output_type -> chatto.api.v1.JoinCallResponse
	8,  // 11: chatto.api.v1.VoiceCallService.GetCallToken:output_type -> chatto.api.v1.GetCallTokenResponse
	10, // 12: chatto.api.v1.VoiceCallService.LeaveCall:output_type -> chatto.api.v1.LeaveCallResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_voice_calls_proto_init() }
func file_chatto_api_v1_voice_calls_proto_init() {
	if File_chatto_api_v1_voice_calls_proto != nil {
		return
	}
	file_chatto_api_v1_users_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_voice_calls_proto_rawDesc), len(file_chatto_api_v1_voice_calls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_voice_calls_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_voice_calls_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_voice_calls_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_voice_calls_proto = out.File
	file_chatto_api_v1_voice_calls_proto_goTypes = nil
	file_chatto_api_v1_voice_calls_proto_depIdxs = nil
}
