// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/notification_preferences.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRoomNotificationPreferenceRequest, GetRoomNotificationPreferenceResponse, SetRoomNotificationLevelRequest, SetRoomNotificationLevelResponse } from "./notification_preferences_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Reads and updates per-room notification preferences for the current user.
 *
 * @generated from service chatto.api.v1.NotificationPreferencesService
 */
export const NotificationPreferencesService = {
  typeName: "chatto.api.v1.NotificationPreferencesService",
  methods: {
    /**
     * Returns the current user's explicit and effective notification level for a
     * room. Use this before rendering room notification controls so the UI can
     * distinguish inherited defaults from an explicit room override.
     *
     * @generated from rpc chatto.api.v1.NotificationPreferencesService.GetRoomNotificationPreference
     */
    getRoomNotificationPreference: {
      name: "GetRoomNotificationPreference",
      I: GetRoomNotificationPreferenceRequest,
      O: GetRoomNotificationPreferenceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sets the current user's explicit notification level for a room and returns
     * the resulting stored and effective levels.
     *
     * @generated from rpc chatto.api.v1.NotificationPreferencesService.SetRoomNotificationLevel
     */
    setRoomNotificationLevel: {
      name: "SetRoomNotificationLevel",
      I: SetRoomNotificationLevelRequest,
      O: SetRoomNotificationLevelResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

