// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/presence.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Live presence status a client can report for the current user.
 *
 * Offline is not a reportable status. Clients that want the user to appear
 * offline should stop reporting presence and let the server's live presence
 * record expire.
 *
 * @generated from enum chatto.api.v1.PresenceStatus
 */
export enum PresenceStatus {
  /**
   * No presence status was specified.
   *
   * @generated from enum value: PRESENCE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The user is actively available.
   *
   * @generated from enum value: PRESENCE_STATUS_ONLINE = 1;
   */
  ONLINE = 1,

  /**
   * The user is connected but away or idle.
   *
   * @generated from enum value: PRESENCE_STATUS_AWAY = 2;
   */
  AWAY = 2,

  /**
   * The user does not want notifications while this live status is active.
   *
   * @generated from enum value: PRESENCE_STATUS_DO_NOT_DISTURB = 3;
   */
  DO_NOT_DISTURB = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(PresenceStatus)
proto3.util.setEnumType(PresenceStatus, "chatto.api.v1.PresenceStatus", [
  { no: 0, name: "PRESENCE_STATUS_UNSPECIFIED" },
  { no: 1, name: "PRESENCE_STATUS_ONLINE" },
  { no: 2, name: "PRESENCE_STATUS_AWAY" },
  { no: 3, name: "PRESENCE_STATUS_DO_NOT_DISTURB" },
]);

/**
 * Request to report the current user's live presence status.
 *
 * @generated from message chatto.api.v1.ReportPresenceRequest
 */
export class ReportPresenceRequest extends Message<ReportPresenceRequest> {
  /**
   * Live status to report for the authenticated user.
   *
   * @generated from field: chatto.api.v1.PresenceStatus status = 1;
   */
  status = PresenceStatus.UNSPECIFIED;

  /**
   * True when this report comes from a deliberate user selection rather than
   * automatic idle/refresh reporting. Automatic reports do not overwrite an
   * active manually selected Away or Do Not Disturb status from another client.
   *
   * @generated from field: bool user_selected = 2;
   */
  userSelected = false;

  constructor(data?: PartialMessage<ReportPresenceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ReportPresenceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(PresenceStatus) },
    { no: 2, name: "user_selected", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReportPresenceRequest {
    return new ReportPresenceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReportPresenceRequest {
    return new ReportPresenceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReportPresenceRequest {
    return new ReportPresenceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReportPresenceRequest | PlainMessage<ReportPresenceRequest> | undefined, b: ReportPresenceRequest | PlainMessage<ReportPresenceRequest> | undefined): boolean {
    return proto3.util.equals(ReportPresenceRequest, a, b);
  }
}

/**
 * Result of reporting live presence.
 *
 * @generated from message chatto.api.v1.ReportPresenceResponse
 */
export class ReportPresenceResponse extends Message<ReportPresenceResponse> {
  /**
   * Status accepted and stored by the server.
   *
   * @generated from field: chatto.api.v1.PresenceStatus status = 1;
   */
  status = PresenceStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<ReportPresenceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ReportPresenceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(PresenceStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReportPresenceResponse {
    return new ReportPresenceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReportPresenceResponse {
    return new ReportPresenceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReportPresenceResponse {
    return new ReportPresenceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReportPresenceResponse | PlainMessage<ReportPresenceResponse> | undefined, b: ReportPresenceResponse | PlainMessage<ReportPresenceResponse> | undefined): boolean {
    return proto3.util.equals(ReportPresenceResponse, a, b);
  }
}

