// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/presence.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ReportPresenceRequest, ReportPresenceResponse } from "./presence_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Lets clients report the authenticated user's current live presence.
 *
 * @generated from service chatto.api.v1.PresenceService
 */
export const PresenceService = {
  typeName: "chatto.api.v1.PresenceService",
  methods: {
    /**
     * Reports the current user's live presence status. This state is transient:
     * clients should refresh it periodically while visible, and should stop
     * calling this RPC when the user chooses to appear offline.
     *
     * @generated from rpc chatto.api.v1.PresenceService.ReportPresence
     */
    reportPresence: {
      name: "ReportPresence",
      I: ReportPresenceRequest,
      O: ReportPresenceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

