// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/room_timeline.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRoomEventsAroundRequest, GetRoomEventsAroundResponse, GetRoomEventsRequest, GetRoomEventsResponse, GetThreadEventsAroundRequest, GetThreadEventsAroundResponse, GetThreadEventsRequest, GetThreadEventsResponse } from "./room_timeline_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Reads room and thread timeline pages.
 *
 * @generated from service chatto.api.v1.RoomTimelineService
 */
export const RoomTimelineService = {
  typeName: "chatto.api.v1.RoomTimelineService",
  methods: {
    /**
     * Returns one page of room timeline events, including related user data needed
     * to render the page.
     *
     * @generated from rpc chatto.api.v1.RoomTimelineService.GetRoomEvents
     */
    getRoomEvents: {
      name: "GetRoomEvents",
      I: GetRoomEventsRequest,
      O: GetRoomEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns a room timeline window centered around a specific event. Use this to
     * open a permalink, search result, or notification target in context.
     *
     * @generated from rpc chatto.api.v1.RoomTimelineService.GetRoomEventsAround
     */
    getRoomEventsAround: {
      name: "GetRoomEventsAround",
      I: GetRoomEventsAroundRequest,
      O: GetRoomEventsAroundResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns one page of events in a message thread. Initial pages include the
     * thread root message; cursor pages return replies in the requested direction.
     *
     * @generated from rpc chatto.api.v1.RoomTimelineService.GetThreadEvents
     */
    getThreadEvents: {
      name: "GetThreadEvents",
      I: GetThreadEventsRequest,
      O: GetThreadEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns a thread timeline window centered around a specific event. Use this
     * to open a reply from a notification or search result in context.
     *
     * @generated from rpc chatto.api.v1.RoomTimelineService.GetThreadEventsAround
     */
    getThreadEventsAround: {
      name: "GetThreadEventsAround",
      I: GetThreadEventsAroundRequest,
      O: GetThreadEventsAroundResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

