// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/server_state.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Authenticated server profile and branding fields.
 *
 * @generated from message chatto.api.v1.ServerProfile
 */
export class ServerProfile extends Message<ServerProfile> {
  /**
   * Display name of the Chatto server.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Optional server logo URL.
   *
   * @generated from field: optional string logo_url = 2;
   */
  logoUrl?: string;

  /**
   * Optional server banner URL.
   *
   * @generated from field: optional string banner_url = 3;
   */
  bannerUrl?: string;

  /**
   * Optional welcome message.
   *
   * @generated from field: optional string welcome_message = 4;
   */
  welcomeMessage?: string;

  /**
   * Optional message of the day.
   *
   * @generated from field: optional string motd = 5;
   */
  motd?: string;

  /**
   * Optional server description.
   *
   * @generated from field: optional string description = 6;
   */
  description?: string;

  constructor(data?: PartialMessage<ServerProfile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ServerProfile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "logo_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "banner_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "welcome_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "motd", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerProfile {
    return new ServerProfile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerProfile {
    return new ServerProfile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerProfile {
    return new ServerProfile().fromJsonString(jsonString, options);
  }

  static equals(a: ServerProfile | PlainMessage<ServerProfile> | undefined, b: ServerProfile | PlainMessage<ServerProfile> | undefined): boolean {
    return proto3.util.equals(ServerProfile, a, b);
  }
}

/**
 * Permission-derived server capabilities for the authenticated user.
 *
 * @generated from message chatto.api.v1.ServerViewerCapabilities
 */
export class ServerViewerCapabilities extends Message<ServerViewerCapabilities> {
  /**
   * Whether the user has at least one server-admin permission.
   *
   * @generated from field: bool has_any_admin_permission = 1;
   */
  hasAnyAdminPermission = false;

  /**
   * Whether the user may manage server configuration.
   *
   * @generated from field: bool can_manage_server = 2;
   */
  canManageServer = false;

  /**
   * Whether the user may create a channel room at server scope.
   *
   * @generated from field: bool can_create_room = 3;
   */
  canCreateRoom = false;

  /**
   * Whether the user may manage at least one room.
   *
   * @generated from field: bool can_manage_rooms = 4;
   */
  canManageRooms = false;

  /**
   * Whether any joined channel room has unread messages.
   *
   * @generated from field: bool has_unread_rooms = 5;
   */
  hasUnreadRooms = false;

  constructor(data?: PartialMessage<ServerViewerCapabilities>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ServerViewerCapabilities";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "has_any_admin_permission", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "can_manage_server", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "can_create_room", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "can_manage_rooms", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "has_unread_rooms", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerViewerCapabilities {
    return new ServerViewerCapabilities().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerViewerCapabilities {
    return new ServerViewerCapabilities().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerViewerCapabilities {
    return new ServerViewerCapabilities().fromJsonString(jsonString, options);
  }

  static equals(a: ServerViewerCapabilities | PlainMessage<ServerViewerCapabilities> | undefined, b: ServerViewerCapabilities | PlainMessage<ServerViewerCapabilities> | undefined): boolean {
    return proto3.util.equals(ServerViewerCapabilities, a, b);
  }
}

/**
 * Request for authenticated server state.
 *
 * @generated from message chatto.api.v1.GetServerStateRequest
 */
export class GetServerStateRequest extends Message<GetServerStateRequest> {
  constructor(data?: PartialMessage<GetServerStateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetServerStateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerStateRequest {
    return new GetServerStateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerStateRequest {
    return new GetServerStateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerStateRequest {
    return new GetServerStateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerStateRequest | PlainMessage<GetServerStateRequest> | undefined, b: GetServerStateRequest | PlainMessage<GetServerStateRequest> | undefined): boolean {
    return proto3.util.equals(GetServerStateRequest, a, b);
  }
}

/**
 * Authenticated server state used by the web client and public API clients.
 *
 * @generated from message chatto.api.v1.GetServerStateResponse
 */
export class GetServerStateResponse extends Message<GetServerStateResponse> {
  /**
   * Server profile and branding.
   *
   * @generated from field: chatto.api.v1.ServerProfile profile = 1;
   */
  profile?: ServerProfile;

  /**
   * Whether Web Push notifications are fully configured.
   *
   * @generated from field: bool push_notifications_enabled = 2;
   */
  pushNotificationsEnabled = false;

  /**
   * Optional VAPID public key for Web Push registration.
   *
   * @generated from field: optional string vapid_public_key = 3;
   */
  vapidPublicKey?: string;

  /**
   * Optional LiveKit URL for voice calls.
   *
   * @generated from field: optional string livekit_url = 4;
   */
  livekitUrl?: string;

  /**
   * Whether direct email/password registration is enabled.
   *
   * @generated from field: bool direct_registration_enabled = 5;
   */
  directRegistrationEnabled = false;

  /**
   * Whether video processing is enabled.
   *
   * @generated from field: bool video_processing_enabled = 6;
   */
  videoProcessingEnabled = false;

  /**
   * Maximum general upload size in bytes.
   *
   * @generated from field: int64 max_upload_size = 7;
   */
  maxUploadSize = protoInt64.zero;

  /**
   * Maximum video upload size in bytes.
   *
   * @generated from field: int64 max_video_upload_size = 8;
   */
  maxVideoUploadSize = protoInt64.zero;

  /**
   * Message edit window in seconds.
   *
   * @generated from field: int32 message_edit_window_seconds = 9;
   */
  messageEditWindowSeconds = 0;

  /**
   * Permission-derived state for the authenticated user.
   *
   * @generated from field: chatto.api.v1.ServerViewerCapabilities viewer_capabilities = 10;
   */
  viewerCapabilities?: ServerViewerCapabilities;

  constructor(data?: PartialMessage<GetServerStateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetServerStateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "profile", kind: "message", T: ServerProfile },
    { no: 2, name: "push_notifications_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "vapid_public_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "livekit_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "direct_registration_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "video_processing_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "max_upload_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "max_video_upload_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "message_edit_window_seconds", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "viewer_capabilities", kind: "message", T: ServerViewerCapabilities },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerStateResponse {
    return new GetServerStateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerStateResponse {
    return new GetServerStateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerStateResponse {
    return new GetServerStateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerStateResponse | PlainMessage<GetServerStateResponse> | undefined, b: GetServerStateResponse | PlainMessage<GetServerStateResponse> | undefined): boolean {
    return proto3.util.equals(GetServerStateResponse, a, b);
  }
}

