// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/user_status.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * Custom status shown on a user profile, separate from presence.
 *
 * @generated from message chatto.api.v1.CustomUserStatus
 */
export class CustomUserStatus extends Message<CustomUserStatus> {
  /**
   * Short emoji marker displayed with the status.
   *
   * @generated from field: string emoji = 1;
   */
  emoji = "";

  /**
   * User-written status text.
   *
   * @generated from field: string text = 2;
   */
  text = "";

  /**
   * Optional time after which clients should stop showing the status.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<CustomUserStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.CustomUserStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CustomUserStatus {
    return new CustomUserStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CustomUserStatus {
    return new CustomUserStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CustomUserStatus {
    return new CustomUserStatus().fromJsonString(jsonString, options);
  }

  static equals(a: CustomUserStatus | PlainMessage<CustomUserStatus> | undefined, b: CustomUserStatus | PlainMessage<CustomUserStatus> | undefined): boolean {
    return proto3.util.equals(CustomUserStatus, a, b);
  }
}

/**
 * Request to set or replace the current user's custom status.
 *
 * @generated from message chatto.api.v1.SetCustomStatusRequest
 */
export class SetCustomStatusRequest extends Message<SetCustomStatusRequest> {
  /**
   * Short emoji marker displayed with the status.
   *
   * @generated from field: string emoji = 1;
   */
  emoji = "";

  /**
   * User-written status text.
   *
   * @generated from field: string text = 2;
   */
  text = "";

  /**
   * Optional future time after which clients should stop showing the status.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<SetCustomStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.SetCustomStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetCustomStatusRequest {
    return new SetCustomStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetCustomStatusRequest {
    return new SetCustomStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetCustomStatusRequest {
    return new SetCustomStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetCustomStatusRequest | PlainMessage<SetCustomStatusRequest> | undefined, b: SetCustomStatusRequest | PlainMessage<SetCustomStatusRequest> | undefined): boolean {
    return proto3.util.equals(SetCustomStatusRequest, a, b);
  }
}

/**
 * Result of setting the current user's custom status.
 *
 * @generated from message chatto.api.v1.SetCustomStatusResponse
 */
export class SetCustomStatusResponse extends Message<SetCustomStatusResponse> {
  /**
   * Stored custom status after validation and normalization.
   *
   * @generated from field: chatto.api.v1.CustomUserStatus status = 1;
   */
  status?: CustomUserStatus;

  constructor(data?: PartialMessage<SetCustomStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.SetCustomStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "message", T: CustomUserStatus },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetCustomStatusResponse {
    return new SetCustomStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetCustomStatusResponse {
    return new SetCustomStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetCustomStatusResponse {
    return new SetCustomStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetCustomStatusResponse | PlainMessage<SetCustomStatusResponse> | undefined, b: SetCustomStatusResponse | PlainMessage<SetCustomStatusResponse> | undefined): boolean {
    return proto3.util.equals(SetCustomStatusResponse, a, b);
  }
}

/**
 * Request to clear the current user's custom status.
 *
 * @generated from message chatto.api.v1.ClearCustomStatusRequest
 */
export class ClearCustomStatusRequest extends Message<ClearCustomStatusRequest> {
  constructor(data?: PartialMessage<ClearCustomStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ClearCustomStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClearCustomStatusRequest {
    return new ClearCustomStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClearCustomStatusRequest {
    return new ClearCustomStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClearCustomStatusRequest {
    return new ClearCustomStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClearCustomStatusRequest | PlainMessage<ClearCustomStatusRequest> | undefined, b: ClearCustomStatusRequest | PlainMessage<ClearCustomStatusRequest> | undefined): boolean {
    return proto3.util.equals(ClearCustomStatusRequest, a, b);
  }
}

/**
 * Result of clearing the current user's custom status.
 *
 * @generated from message chatto.api.v1.ClearCustomStatusResponse
 */
export class ClearCustomStatusResponse extends Message<ClearCustomStatusResponse> {
  /**
   * Current custom status after the operation. Usually absent after a clear.
   *
   * @generated from field: chatto.api.v1.CustomUserStatus status = 1;
   */
  status?: CustomUserStatus;

  constructor(data?: PartialMessage<ClearCustomStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ClearCustomStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "message", T: CustomUserStatus },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClearCustomStatusResponse {
    return new ClearCustomStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClearCustomStatusResponse {
    return new ClearCustomStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClearCustomStatusResponse {
    return new ClearCustomStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClearCustomStatusResponse | PlainMessage<ClearCustomStatusResponse> | undefined, b: ClearCustomStatusResponse | PlainMessage<ClearCustomStatusResponse> | undefined): boolean {
    return proto3.util.equals(ClearCustomStatusResponse, a, b);
  }
}

