// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/users.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { PresenceStatus } from "./presence_pb.js";
import { CustomUserStatus } from "./user_status_pb.js";

/**
 * Fit mode used when generating transformed user avatar URLs.
 *
 * @generated from enum chatto.api.v1.UserAvatarFitMode
 */
export enum UserAvatarFitMode {
  /**
   * The fit mode was not specified.
   *
   * @generated from enum value: USER_AVATAR_FIT_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Preserve the whole source image within the requested bounds.
   *
   * @generated from enum value: USER_AVATAR_FIT_MODE_CONTAIN = 1;
   */
  CONTAIN = 1,

  /**
   * Fill the requested bounds, cropping when needed.
   *
   * @generated from enum value: USER_AVATAR_FIT_MODE_COVER = 2;
   */
  COVER = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(UserAvatarFitMode)
proto3.util.setEnumType(UserAvatarFitMode, "chatto.api.v1.UserAvatarFitMode", [
  { no: 0, name: "USER_AVATAR_FIT_MODE_UNSPECIFIED" },
  { no: 1, name: "USER_AVATAR_FIT_MODE_CONTAIN" },
  { no: 2, name: "USER_AVATAR_FIT_MODE_COVER" },
]);

/**
 * Avatar transform parameters for user profile reads.
 *
 * @generated from message chatto.api.v1.UserAvatarOptions
 */
export class UserAvatarOptions extends Message<UserAvatarOptions> {
  /**
   * Avatar width in pixels.
   *
   * @generated from field: int32 width = 1;
   */
  width = 0;

  /**
   * Avatar height in pixels.
   *
   * @generated from field: int32 height = 2;
   */
  height = 0;

  /**
   * Avatar crop/fit behavior.
   *
   * @generated from field: chatto.api.v1.UserAvatarFitMode fit = 3;
   */
  fit = UserAvatarFitMode.UNSPECIFIED;

  constructor(data?: PartialMessage<UserAvatarOptions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UserAvatarOptions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "width", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "height", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "fit", kind: "enum", T: proto3.getEnumType(UserAvatarFitMode) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserAvatarOptions {
    return new UserAvatarOptions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserAvatarOptions {
    return new UserAvatarOptions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserAvatarOptions {
    return new UserAvatarOptions().fromJsonString(jsonString, options);
  }

  static equals(a: UserAvatarOptions | PlainMessage<UserAvatarOptions> | undefined, b: UserAvatarOptions | PlainMessage<UserAvatarOptions> | undefined): boolean {
    return proto3.util.equals(UserAvatarOptions, a, b);
  }
}

/**
 * Lightweight public user data for cache-backed render surfaces.
 *
 * @generated from message chatto.api.v1.UserSummary
 */
export class UserSummary extends Message<UserSummary> {
  /**
   * Stable user ID.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Login name.
   *
   * @generated from field: string login = 2;
   */
  login = "";

  /**
   * Display name, when set.
   *
   * @generated from field: string display_name = 3;
   */
  displayName = "";

  /**
   * True when the user account has been deleted.
   *
   * @generated from field: bool deleted = 4;
   */
  deleted = false;

  /**
   * Avatar image URL, when available.
   *
   * @generated from field: optional string avatar_url = 5;
   */
  avatarUrl?: string;

  constructor(data?: PartialMessage<UserSummary>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UserSummary";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "login", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "avatar_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserSummary {
    return new UserSummary().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserSummary {
    return new UserSummary().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserSummary {
    return new UserSummary().fromJsonString(jsonString, options);
  }

  static equals(a: UserSummary | PlainMessage<UserSummary> | undefined, b: UserSummary | PlainMessage<UserSummary> | undefined): boolean {
    return proto3.util.equals(UserSummary, a, b);
  }
}

/**
 * Lightweight public user data plus live profile state.
 *
 * @generated from message chatto.api.v1.UserPresenceSummary
 */
export class UserPresenceSummary extends Message<UserPresenceSummary> {
  /**
   * Public identity fields.
   *
   * @generated from field: chatto.api.v1.UserSummary user = 1;
   */
  user?: UserSummary;

  /**
   * Current live presence status.
   *
   * @generated from field: chatto.api.v1.PresenceStatus presence_status = 2;
   */
  presenceStatus = PresenceStatus.UNSPECIFIED;

  /**
   * Custom profile status, when set.
   *
   * @generated from field: chatto.api.v1.CustomUserStatus custom_status = 3;
   */
  customStatus?: CustomUserStatus;

  constructor(data?: PartialMessage<UserPresenceSummary>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UserPresenceSummary";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: UserSummary },
    { no: 2, name: "presence_status", kind: "enum", T: proto3.getEnumType(PresenceStatus) },
    { no: 3, name: "custom_status", kind: "message", T: CustomUserStatus },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserPresenceSummary {
    return new UserPresenceSummary().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserPresenceSummary {
    return new UserPresenceSummary().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserPresenceSummary {
    return new UserPresenceSummary().fromJsonString(jsonString, options);
  }

  static equals(a: UserPresenceSummary | PlainMessage<UserPresenceSummary> | undefined, b: UserPresenceSummary | PlainMessage<UserPresenceSummary> | undefined): boolean {
    return proto3.util.equals(UserPresenceSummary, a, b);
  }
}

/**
 * Request one user by stable user ID.
 *
 * @generated from message chatto.api.v1.GetUserRequest
 */
export class GetUserRequest extends Message<GetUserRequest> {
  /**
   * Required user ID.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * Optional avatar URL transform parameters. Omit for the original avatar URL.
   *
   * @generated from field: chatto.api.v1.UserAvatarOptions avatar = 2;
   */
  avatar?: UserAvatarOptions;

  constructor(data?: PartialMessage<GetUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "avatar", kind: "message", T: UserAvatarOptions },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserRequest {
    return new GetUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserRequest {
    return new GetUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserRequest {
    return new GetUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserRequest | PlainMessage<GetUserRequest> | undefined, b: GetUserRequest | PlainMessage<GetUserRequest> | undefined): boolean {
    return proto3.util.equals(GetUserRequest, a, b);
  }
}

/**
 * Request one user by login identifier.
 *
 * @generated from message chatto.api.v1.GetUserByLoginRequest
 */
export class GetUserByLoginRequest extends Message<GetUserByLoginRequest> {
  /**
   * Required login identifier.
   *
   * @generated from field: string login = 1;
   */
  login = "";

  /**
   * Optional avatar URL transform parameters. Omit for the original avatar URL.
   *
   * @generated from field: chatto.api.v1.UserAvatarOptions avatar = 2;
   */
  avatar?: UserAvatarOptions;

  constructor(data?: PartialMessage<GetUserByLoginRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetUserByLoginRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "login", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "avatar", kind: "message", T: UserAvatarOptions },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserByLoginRequest {
    return new GetUserByLoginRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserByLoginRequest {
    return new GetUserByLoginRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserByLoginRequest {
    return new GetUserByLoginRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserByLoginRequest | PlainMessage<GetUserByLoginRequest> | undefined, b: GetUserByLoginRequest | PlainMessage<GetUserByLoginRequest> | undefined): boolean {
    return proto3.util.equals(GetUserByLoginRequest, a, b);
  }
}

/**
 * Request lightweight summaries for a set of stable user IDs.
 *
 * @generated from message chatto.api.v1.BatchGetUsersRequest
 */
export class BatchGetUsersRequest extends Message<BatchGetUsersRequest> {
  /**
   * Required user IDs. Unknown IDs are omitted from the response.
   *
   * @generated from field: repeated string user_ids = 1;
   */
  userIds: string[] = [];

  /**
   * Optional avatar URL transform parameters. Omit for the original avatar URL.
   *
   * @generated from field: chatto.api.v1.UserAvatarOptions avatar = 2;
   */
  avatar?: UserAvatarOptions;

  constructor(data?: PartialMessage<BatchGetUsersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetUsersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "avatar", kind: "message", T: UserAvatarOptions },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetUsersRequest {
    return new BatchGetUsersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetUsersRequest {
    return new BatchGetUsersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetUsersRequest {
    return new BatchGetUsersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetUsersRequest | PlainMessage<BatchGetUsersRequest> | undefined, b: BatchGetUsersRequest | PlainMessage<BatchGetUsersRequest> | undefined): boolean {
    return proto3.util.equals(BatchGetUsersRequest, a, b);
  }
}

/**
 * Public authenticated user profile response.
 *
 * @generated from message chatto.api.v1.GetUserResponse
 */
export class GetUserResponse extends Message<GetUserResponse> {
  /**
   * Requested user.
   *
   * @generated from field: chatto.api.v1.UserPresenceSummary user = 1;
   */
  user?: UserPresenceSummary;

  constructor(data?: PartialMessage<GetUserResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetUserResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: UserPresenceSummary },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserResponse {
    return new GetUserResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserResponse {
    return new GetUserResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserResponse {
    return new GetUserResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserResponse | PlainMessage<GetUserResponse> | undefined, b: GetUserResponse | PlainMessage<GetUserResponse> | undefined): boolean {
    return proto3.util.equals(GetUserResponse, a, b);
  }
}

/**
 * Public authenticated user profile response for login lookup.
 *
 * @generated from message chatto.api.v1.GetUserByLoginResponse
 */
export class GetUserByLoginResponse extends Message<GetUserByLoginResponse> {
  /**
   * Requested user.
   *
   * @generated from field: chatto.api.v1.UserPresenceSummary user = 1;
   */
  user?: UserPresenceSummary;

  constructor(data?: PartialMessage<GetUserByLoginResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetUserByLoginResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: UserPresenceSummary },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserByLoginResponse {
    return new GetUserByLoginResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserByLoginResponse {
    return new GetUserByLoginResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserByLoginResponse {
    return new GetUserByLoginResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserByLoginResponse | PlainMessage<GetUserByLoginResponse> | undefined, b: GetUserByLoginResponse | PlainMessage<GetUserByLoginResponse> | undefined): boolean {
    return proto3.util.equals(GetUserByLoginResponse, a, b);
  }
}

/**
 * Lightweight batch user summary response.
 *
 * @generated from message chatto.api.v1.BatchGetUsersResponse
 */
export class BatchGetUsersResponse extends Message<BatchGetUsersResponse> {
  /**
   * Found users. The server preserves first-seen request order and de-duplicates
   * repeated IDs.
   *
   * @generated from field: repeated chatto.api.v1.UserSummary users = 1;
   */
  users: UserSummary[] = [];

  constructor(data?: PartialMessage<BatchGetUsersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetUsersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: UserSummary, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetUsersResponse {
    return new BatchGetUsersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetUsersResponse {
    return new BatchGetUsersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetUsersResponse {
    return new BatchGetUsersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetUsersResponse | PlainMessage<BatchGetUsersResponse> | undefined, b: BatchGetUsersResponse | PlainMessage<BatchGetUsersResponse> | undefined): boolean {
    return proto3.util.equals(BatchGetUsersResponse, a, b);
  }
}

