// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/users.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchGetUsersRequest, BatchGetUsersResponse, GetUserByLoginRequest, GetUserByLoginResponse, GetUserRequest, GetUserResponse } from "./users_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Provides authenticated public user directory lookups.
 *
 * @generated from service chatto.api.v1.UserDirectoryService
 */
export const UserDirectoryService = {
  typeName: "chatto.api.v1.UserDirectoryService",
  methods: {
    /**
     * Gets a user by stable ID. Returns NOT_FOUND when the ID is unknown.
     *
     * @generated from rpc chatto.api.v1.UserDirectoryService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets a user by login. Returns NOT_FOUND when the login is unknown.
     *
     * @generated from rpc chatto.api.v1.UserDirectoryService.GetUserByLogin
     */
    getUserByLogin: {
      name: "GetUserByLogin",
      I: GetUserByLoginRequest,
      O: GetUserByLoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets public user records for multiple users referenced by event-focused
     * payloads.
     *
     * @generated from rpc chatto.api.v1.UserDirectoryService.BatchGetUsers
     */
    batchGetUsers: {
      name: "BatchGetUsers",
      I: BatchGetUsersRequest,
      O: BatchGetUsersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

